### ISSUE TITLE
strange user assignments?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1000]
As I was looking at the sources in #999 I noticed some VERY suspicious user-source relationships. I happen to know that the sources in Helsinki are being worked on by users 251662, 251663 and 251678--who I don't see at all in the recently modified sources list. Instead I see 251612 and 251613, who I didn't think had been logged in in some time, and aren't to my knowledge involved in that project, and all the Finnish sources seem to have been "last modified by" @jacobdgm. 

I find this odd...

**Comment by jacobdgm** [comment]
Can you list the IDs of a few of these sources?

**Comment by annamorphism** [comment]
714693, 714807, 711232, 711225, 711223, 711204.

Now that I'm looking at the list I'm also a little suspicious of a number of other sources (713041, 713037, 713033) that aren't created by who I thought created them...

**Comment by annamorphism** [comment]
What I notice is that the affected users are all pretty recent accounts, and their replacements are mostly ones with fake emails attached.  
So for example source 714807 was made by user 251612 on OldCantus; the source is still attached to the userID 251612, but the actual user associated with that user ID is somebody else (one of the fake accounts), while the actual user of that OldCantus ID is now userID 251662. 
Strangely I have not heard any complaints from these users about not being able to access their sources, but maybe they just haven't tried yet...

**Comment by jacobdgm** [comment]
huh - my guess as to what happened:
- a year ago, we synced users between OldCantus and NewCantus
- then, we merged users and indexers, creating a bunch of new dummy users
- new user accounts were created on OldCantus, and then sources were assigned to these new user accounts. The IDs for these accounts sometimes collided with IDs for indexer/dummy users on CantusDB
- we synced data from OldCantus to NewCantus. When we updated sources assigned to the new users on OldCantus, NewCantus checked to see whether a user account matching the user ID existed in NewCantus. If it did (i.e. if there was a dummy indexer/user with a matching user ID in NewCantus), we assigned that user to the source.

It might make most sense to sort this out manually. Unless I've overlooked something, we can go through all the users with @fakeemail.com accounts, and check to make sure that they don't have any "Sources Assigned to User". If they do, we check with OldCantus to see which user account they _should_ be associated with, add the sources to the proper user account, and remove them from the dummy account.
@annamorphism, does this sound like the right approach? Would it make sense for you to do this (since you have a better sense for who should belong to what source than I do)? I'd also be happy to do it - let me know.

**Comment by annamorphism** [comment]
I also have a pretty good idea of who is a new-ish user added on OldCantus. So yes, I can go through this.

**Comment by annamorphism** [comment]
Wait--the problem is actually a little different. The fakeemail users don't have sources assigned to them as such, but their names show up as "created by"--so the OldCantus userID associated with that source got pulled into NewCantus and then "translated" into the name, as it were, instead of first getting mapped to the newCantus ID and then turned into a name. The source assignments, though, seem to have moved along with the users. On the other hand, affected sources have both their old and new users in the assigned editor box, with the same name: 
<img width="807" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/dee53b07-ffdb-4f3d-a953-13c9ce1daf42">
I'm assuming one of these is the OldCantusID of that user and one is the NewCantus one, but I don't know which one is which...
Anyway, I'm not sure I know how to fix what displays for "created by" through the admin menu, but I could make a list of affected sources/users. It seems like this problem doesn't affect access, which is good in the short term, but does mean the sources are incorrectly attributed, which is bad in the long term.

**Comment by annamorphism** [comment]
And today I got my first email wondering why some person nobody knew was listed as a "contributor" on their source.  I think there are 17 sources affected, but I don't know how to change the "created by" information to be associated with the new cantus user and not the old one.

**Comment by jacobdgm** [comment]
> I'm assuming one of these is the OldCantusID of that user and one is the NewCantus one, but I don't know which one is which...

When I was manually importing recently-created users, I came across duplicated names like this, and it seems to be a bug - if you go to change a user's name, you can only find one of them in the Users app in the Admin area. And then if you change the name of one of them, _both_ instances are changed on the source page. So I'm pretty sure there is just one "Hilkka-Liisa Vuori", I'm just not sure why it's appearing twice.

(maybe we're taking the queryset of users, and the queryset of users who are indexers, and concatenating them without checking for duplicates? Let me look into this...)

**Comment by jacobdgm** [comment]
Just following up on this - the duplicated names in the admin interface had to do with single user accounts belonging to multiple permission groups. But the issue at hand has to do with users being synced at one time while user-source assignments were synced significantly later. @annamorphism, do you have all the information you need to sort this out? Is there anything else I can do to help with this?

**Comment by annamorphism** [comment]
@jacobdgm no I 'm not sure we do. The duplicate names turned out to be a red herring (and spun off into the now-solved #1021). I can't change who shows up as a "contributor" to source 714693, and the fake user who shows up has no sources assigned to her I can modify either. The problem is somewhere in the pipeline that led to the created-by information, and I am not sure I can fix it.

**Comment by jacobdgm** [comment]
@annamorphism and I just talked about this - @annamorphism is going to create a csv (or similar) with two columns: one with source ID, and one with the User ID of the NewCantus user who authored the source. I'll write a script to go through the sources and assign them to these proper users.

**Comment by annamorphism** [comment]
I have made two sheets relevant to this problem. https://docs.google.com/spreadsheets/d/1DtUbkPBmrxYP3om-3ZmHNvsnfmBEbGR6dLrap16rZRE/edit?usp=sharing
One is a list of affected sources with the creatorID they *should* be associated with.
I feel fairly confident these 17 sources are the only affected ones, so if the "created by" information on these is changed we will be all set. 
The second sheet  is a list of users whose IDs were changed from OldCantus to NewCantus (which created the list of sources, and which may be helpful for other information moved from one place to the other e.g. chant creator information.) 
Method:
In principle anybody with an OldCantus UserID above 251599 was affected (which is the lowest ID assigned to a fake email) but for whatever reason 251599 through 251609 were not assigned, as were, apparently, 251628, 251629, 251634, 251635, 251636, and 251637. (I have included these in the sheet in strikethrough just in case I have simply overlooked the reason for these apparently unassigned IDs; if they are indeed unassigned, we can delete these rows.)  A few other IDs in this range were assigned for testing purposes to users who never got a NewCantus ID (or in one case, already had a different ID); these also can be deleted from the list. 
This leaves 27 affected users, whose NewCantus ID I looked up.  
I then looked up all the sources created since the last update, and included any that were created by affected users on the list of sources to change.

**Comment by jacobdgm** [comment]
So just to confirm, the algorithm I'm thinking of:

```
looking at anna's spreadsheet, second page - create a list of OldCantus user IDs

for every chant in the database:
  if its created_by is in the list of OldCantus user IDs:
    change its created_by to the corresponding NewCantus user ID

and we follow the same process for sources
```

So, if we find a chant in the database whose `created_by` is `251610`, we change it to `251660`. @annamorphism, this sounds correct, yes?

Update: I just checked, and all sequences are created by the User with id=1. So we only need to remap chants and sources.

**Comment by annamorphism** [comment]
@jacobdgm yes! this is basically the algorithm I did manually, and which a computer would do much better...

**Comment by annamorphism** [comment]
I received an email about this this morning, so although it's a fairly small thing I'm assigning it high priority.

**Comment by jacobdgm** [comment]
I managed to finish a script on Tuesday to assign sources'/chants' `created_by` to their proper user. For now, it just does a dry run, identifying which objects would be affected and printing what it would do, but it can be very easily reworked to actually reassign the objects' created_by-ship. It identified 17 sources that would be affected (which matches the number @annamorphism noted in her spreadsheet) and several thousand chants. Remaining steps to solve this:

- [x] I'll download an up-to-date copy of the database from Production and load it on my local machine.
- [x] I'd like @annamorphism to glance at the output of the dry run version of my script. If everything seems to be correct, I'll convert the script to really reassign creatorship of all the objects on my local machine.
- [ ] Once we verify that it did what we expected it to do, we open a pull request to add the command to the code base.
- [ ] Once this command makes it onto the Staging server, we copy the database from Production and put it on Staging. We run the command and verify that it does what we expect it to do.
- [ ] Once the command makes it onto the Production server, we can optionally do one last dry run, and then run it to actually reassign the objects. Once we've done this, we're done!

The first of these steps can happen as early as Thu Oct 12, when I'm back in the lab.
