### ISSUE TITLE
question: why is "add new source" on the edit-chants page?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1004]
On the full-text editor/"edit-chants" page, you get the option to create a new source after the explainer text of how to click the edit button. I know the short answer is that this is there because it was in OldCantus but...what I actually always want from this page is an easy way to make new CHANTS, and today I wondered if this button (which I have always ignored, because I never want to go making new sources from within a source) was actually intended to be that once upon a time?

**Comment by lucasmarchd01** [comment]
I'm not exactly sure why adding chants is not an option on the full-text editor page, it certainly makes more sense than having the add source option. I can't check which OldCantus, but maybe it would be best to have both the option to add sources and chants on this page? Would it also make sense to have an "add chant" option on the chant-proofread page? Right now there is neither an option to create a source or a chant.

**Comment by annamorphism** [comment]
@lucasmarchd01 yes I think it would make sense to have an option to create chants on the proofread page as well!
