### ISSUE TITLE
Discrepancies between sequential and numerical order in Folio sorting

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1010]
It seems that the sorting algorithm might treat the folio identifiers as strings, leading to lexicographic rather than numeric sorting. This creates discrepancies when there are leading/trailing zeros or differences in the number of digits used. Treating the identifiers as numerical values, rather than strings, will ensure that the sorting adheres to the expected numerical order.

![image](https://github.com/DDMAL/CantusDB/assets/71031342/b0557236-c4cb-473c-9f6d-2ca140761d49)

**Comment by dchiller** [comment]
I think this might have been solved already at some point? I can't find an instance of this happening on production and just tried to construct one on staging to no avail. Closing for now...if we find it again, we can re-open.
