### ISSUE TITLE
Chant Detail page: we should display `differentia_db` field

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1014]
in an email from Debra:

> [a contributor] has noticed that the newer DifferentiaDB field isn't showing on the first chant screen (see screenshot). The field is there on the entry-form, but we would like it visible too, please.
>
> I would like both of these fields ("Differentia" and "DifferentiaDB") since there is information in the old "Differentia" field that is valuable. We might be able to change this for the next iteration of CantusDB, but at the moment, having both fields visible would be fantastic.

At the very least, we should provide the code stored in the `differentia_db` field, and provide a link to the relevant page on differentiaedatabase.ca. For bonus points, we should figure out how to get the volpiano to go with the code from the relevant API on the Differentiae Database.

**Comment by annamorphism** [comment]
agreed! the other day I was trying to compare differentia codes and had to go to OldCantus to do it, which is not ideal. Just the codes without the Volpiano would be a big improvement, if getting the API is going to hold things up.
