### ISSUE TITLE
Include "Edit" button on source pages for logged-in contributors

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#102]
If a contributor/proofreader/etc. is logged in, there should be an "Edit" button built into the template for each source that that user has permission to edit.

Context: when I worked as a transcriber for Cantus, I remember needing to follow a very specific series of links to reach the edit page for whatever manuscript I was working on at the time - if I navigated to the source page via search or clicked on the wrong link pointing to the source page, I would reach a dead-end where I would be on the page associated with the correct source, but had no option to edit the source. I remember being coached when I was first being oriented, along the lines of "click on _this_, even though it may seem reasonable to click on _that_", and still getting tripped up and confused after having being coached in this way - this should be an easy fix!

**Comment by annamorphism** [comment]
There is already an edit button for each source; what's a little weird is that there are two paths that take you to fractionally different edit forms. (This is bizarre, please do not replicate.)

For example, there is an edit button for this source, and also for its chant contents. 
![image](https://user-images.githubusercontent.com/67451875/171062500-054f0d6e-213e-41af-ad72-aff7b87989ba.png)

![image](https://user-images.githubusercontent.com/67451875/171062480-1de5ca41-e679-4e90-bbaf-77b1ca9a3574.png)

However, there is also a "source edit" button: 
![image](https://user-images.githubusercontent.com/67451875/171062559-84f83141-947b-4090-821d-a28af0464409.png). 

One edit page looks like this:

![image](https://user-images.githubusercontent.com/67451875/171062645-248d1335-3c2d-4bbd-9205-a1bff60eb86d.png)


and the other like this (which also lets you edit syllabification, though the first does not!)
![image](https://user-images.githubusercontent.com/67451875/171062733-3d38afd8-644e-49b7-aaf9-8d1b8e036eca.png)

**Comment by jwang44** [comment]
To me it looks like these two chant-edit interfaces can be harmonized into one with the edit-syllabification feature. @jiwoojeongjj (the creator of the chant-edit page on new Cantus), any thoughts or questions on this?

**Comment by jwang44** [comment]
This came up in our pair-programming discussion today. Apparently, the first interface: https://cantus.uwaterloo.ca/node/243157/edit and the second interface https://cantus.uwaterloo.ca/edit-volpiano/699578 are using almost the same form, but different sidebars. 

The first interface (accessed via the chant detail page) has the source information in the sidebar. 
![Screen Shot 2022-06-01 at 17 22 33](https://user-images.githubusercontent.com/54256124/171504119-a61b47a1-d17c-4ad9-ab3e-30dbc3b2fcd3.png)

The second interface (accessed via my-sources) has a list of all chants in the sidebar.
![Screen Shot 2022-06-01 at 17 24 10](https://user-images.githubusercontent.com/54256124/171504323-e1134fd7-3f07-4709-aa82-e6bdf2dfa88f.png)

@jacobdgm mentioned that these two interfaces might be used for different purposes. The first one is good for quickly fixing errors spotted on the chant detail page. The second one is good for systematically editing a series of chants within a manuscript, going from top to bottom. 

We plan to make the two forms look exactly the same (same fields, same layout) but with different sidebars. And the two forms are still accessed at different URLs, just like in the old Cantus.

**Comment by jacobdgm** [comment]
I have a suggestion: we should implement an `edit-chant` (singular) page, and also an `edit-chants` (plural) page.

- `edit-chant` would correspond to the current `currentnode/<chant ID>/edit` path - it should be reachable from any corresponding chant-detail page. Its purpose would be for doing things like making one-off corrections to individual chants. It would have a save button at the bottom of the page. Its url path would be something like `~/edit-chant/<chant ID>`.
- `edit-chants` would correspond to the current `edit-volpiano/<source ID>` path - it should be reachable from the corresponding source-detail page. Its purpose would be for transcribers/proofreaders working sequentially through all the chants in a source. It would have the sidebar with the column of EDIT buttons, and it would have a save-and-next-chant button at the bottom of the page. Its url path would be something like `~/edit-chants/<source ID>`. It would include the suggested-full-text feature as described in [issue 167](https://github.com/DDMAL/CantusDB/issues/167).

on the `edit-chant` (sing) page, we could have an "Edit surrounding chants" link which would lead to the corresponding `edit-chants` (pl) page.

Anyways, it looks like there are two similar-but-distinct editing-related tasks (1: making isolated edits, and 2: updating records sequentially), for which there are two different-but-similar pages. If this is indeed the purpose for these two pages, it's understandable that we're confused, since their URLs don't provide any information on their purposes (both of the current `node/12345/edit` and `edit_volpiano` edit chants, and you can edit the volpiano field on each page). The above suggestion would preserve the current functionality while clarifying what the different pages are meant to do.

**Comment by annamorphism** [comment]
@jacobdgm I quite like this idea, though I wonder if having the paths be one letter off would be confusing. It would certainly less confusing than it is now, though!

**Comment by jacobdgm** [comment]
@annamorphism - this is a good point. Here's a way that we could possibly implement it, with the URL indicating more clearly the purpose of the page:

spot edits: `~/edit-chant/?chant=<chant ID>`
working through manuscript: `~/edit-chants/?source=<source ID>`
