### ISSUE TITLE
Adding/changing Source `image_link` sometimes doesn't work

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1028]
I tried to manually update the `image_link` for the Salzinnes MS (123723), and encountered difficulties saving the updated image link. On the Source Edit page, I would update the link and press save. I would not get any success/error messages, but upon clicking "Image gallery" in the sidebar, I would be taken to the URL that was previously saved in the field. I observed this behavior on both staging and production.

On Staging, I also tried editing it in the Admin Area. I got a success message upon saving, but the image link still wasn't updated.

I was able to successfully update the link on Staging by going into the django shell, getting the Source by its id, setting its image link, and saving. But users should be able to do this on the Source Edit page or in the admin area.

On staging, I tried updating the image link for a different, test source, and it worked fine. We've only observed this bug for Salzinnes.

I don't know what could be causing this behavior. Would be worth investigating further.

(update: on Production, trying to update it on the Source Edit page worked this time)

**Comment by annamorphism** [comment]
That is strange...I tried editing something else that already had a link (in case it had something to do with links that were brought over from old cantus instead of created on New) and that worked fine too.

**Comment by jacobdgm** [comment]
Tried again, still cannot recreate. Closing.
