### ISSUE TITLE
We should display Differentiae Database volpiano snippets

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1030]
A follow-on to #1014 - I sent an email to Jan asking about what API CD uses to get volpiano snippets from Differentiae Database, and it turns out there's no API - Jan has an extra table in OldCantus where these snippets are stored. He sent us a database dump with all the information he has.

It seems that this table was created once and has rarely/never been touched since. I asked Debra, and it sounds like the data in DD doesn't change very often (for better or for worse - I understand @annamorphism may have some opinions on this).

I'm thinking the best approach could be to create a new `Differentia` model in our database to store volpiano snippets for display on the Chant Detail page. From time to time (perhaps once a year), we can sync data with DD, perhaps by asking them for a CSV.

The model would look something like this (based on what I can see at https://differentiaedatabase.ca/index):

```python
class Differentia(BaseModel):
    differentia_id = models.CharField()  # values like `129a` get stored here
    melodic_transcription = models.CharField()  # values like `1--k-k-l-j-k-h--4` get stored here
    # mode - differentia database stores information on mode, but we don't expect to ever need to display it
    # saeculorum - DD stores a volpiano snippet about the "saeculorum" part of the differentia, but we don't expect to ever need to display it
    # amen - DD stores a volpiano snippet about the "amen" part of the differentia, but we don't expect to ever need to display it
```

**Does creating a new model like this seem like a reasonable course of action?** In the absence of any dissenting voices within the next ~24h, I'll go ahead and start implementing this.

**Comment by jacobdgm** [comment]
For reference, the SQL dump Jan sent me looks like this:

```SQL
SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `aa_diff_volpiano`;
CREATE TABLE `aa_diff_volpiano` (
  `code` varchar(20) NOT NULL,
  `volpiano` varchar(100) NOT NULL,
  `mode` varchar(100) NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `aa_diff_volpiano` (`code`, `volpiano`, `mode`, `id`) VALUES
('100b',	'1--k-k-k-k-h-gh--4',	'Mode 8',	1),
('101a',	'1--k-k-j-hj-h-g--4',	'Mode 3',	2),
('101b',	'1--k-k-kj-hj-h-g--4',	'Mode 3',	3),
('101c',	'1--k-k-j-hj-h-gg--4',	'Mode 3',	4),
('101d',	'1--k-k-kj-hj-hg-g--4',	'Mode 3',	5),
('101f',	'1--k-kj-hj-j-h-g--4',	'Mode 3',	6),
('101h',	'1--k-k-kkj-hj-h-g--4',	'Mode 3',	7),
.
.
.
('T99z',	'1--f-f-d-f-g-ff--4',	'Mode 8',	1272),
('T9a',	'1--m-m-k-ln-l-k--4',	'Mode 6',	1273);
```

As you can see, there are about 1300 ~= 10^3 different differentiae.

**Comment by lucasmarchd01** [comment]
Related to #774
