### ISSUE TITLE
`json_node_export` API is different in NewCantus

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1031]
Discovered in the course of a subdiscussion of an [unrelated issue](https://github.com/DDMAL/CantusDB/issues/940#issuecomment-1717821372) and [investigating the failing tests when Cantus Ultimus was modified to use links to NewCantus](https://github.com/DDMAL/cantus/pull/765).

The json object returned by the `json_node_export` API (at least for sources) has a different structure in Old and NewCantus. See the export for source `123981` in [OldCantus](https://cantus.uwaterloo.ca/json-node/123981) and [NewCantus](https://cantusdatabase.org/json-node/123981). It looks to me like the response from the OldCantus API is provided in the returned object at the key `json_info` and adds a bunch of other (at times duplicate) top-level keys. 

I don't know how many entities other than Cantus Ultimus use this API, so it is fairly easy to adjust what we do to the new format. I would at least add a note to this effect in the wiki (since it seems like a lot to modify the API to conform to OldCantus without knowing anyone else is using it), as what is currently there makes it sound like you should just be able to point to the new url. Maybe to [relevant entry](https://github.com/DDMAL/CantusDB/wiki/APIs#json_node_export) add something like an italicized "Note: Field names in the response object have changed between the `json-node` API and this API."

A related side note: I see there are other issues (eg. #840, #564) in an ongoing discussion about this API endpoint and whether or not it is used, how and whether or not to update the API to work with the ID assignment scheme in NewCantus. Cantus Ultimus *does* need this API to obtain source metadata, but could, of course, switch to a new API if one were available in NewCantus. So, for one, I don't know when we will have a published source in NewCantus with an ID > 1000000, but as it currently stands we would need this API to support that source.

**Comment by dchiller** [comment]
Another side note, this one unrelated: It seems that Drupal and Django handle duplicate slashes (`/`) in URLs differently. In OldCantus, `https://cantus.uwaterloo.ca//json-node/123981` (note the two slashes after the domain) provides the same response as `https://cantus.uwaterloo.ca/json-node/123981` while in NewCantus `https://cantusdatabase.org//json-node/123981` leads to a 404 error. We had been using these malformed urls in Cantus Ultimus, so while they worked with the OldCantus domain, when we switched to the NewCantus base domain, they started failing. 

I've changed CantusUltimus so that we don't send requests to these bad url's anymore (ie. the NewCantus behaviour seems correct to me) but thought it an funny find!

**Comment by jacobdgm** [comment]
So the `json_node_export` API returns all the fields for the object in question. Some of our internal variable names are different from those on OldCantus, so the keys are different. I've added a note to this effect, as you suggested.

> It looks to me like the response from the OldCantus API is provided in the returned object at the key `json_info` and adds a bunch of other (at times duplicate) top-level keys.

This is basically true - `json_info` stores the response we received from OldCantus during the syncing process, just in case we discover there's some important bit of information that wasn't fully imported from OldCantus after the old site is brought down. So the the value in `json_info` will be the same as the old `json-node` API (but if the chant has been edited on NewCantus, the value will be out of date. And if the chant was initially created on NewCantus, it won't have any `json_info`.

**Comment by jacobdgm** [comment]
Now that the documentation/wiki has been updated (and since adding support for duplicate slashes is probably not necessary), I'm going to close this.

**Comment by dchiller** [comment]
Thanks for the info. I've updated Cantus Ultimus accordingly. (And yes, don't support double slashes)
