### ISSUE TITLE
Make proofread boxes available in edit pages

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1032]
From Debra (email 12 Sept 2023):

> if possible I would like the little blue checkboxes that I click when I proofread a record visible in my "edit" view. (They can also be any version of a "yes/no" box or fill-in, as long as I can mark a record proofread as I go through the source.)

Screenshot from chant edit page in OldCantus

<img width="754" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/0b47a11a-21b1-41d0-b963-9e51c1f9b44c">

According to Debra, these boxes (or something like them) are available in the Taxonomy Manager (I don't have permission to view, so have not seen what they look like there myself), but not in the edit pages, making it a two-window task to proofread/edit and then mark as proofread.

**Comment by annamorphism** [comment]
For completeness:
 These boxes appear in the proofread pages: 
<img width="868" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/77e3e472-bae4-491e-80f0-df557bc868fc">

They do not appear in the edit page (which are a good deal easier to access): 
<img width="910" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/5cda55c9-a52e-4810-86b4-c26e15655ec4">

They do also appear in the Taxonomy manager like so:
<img width="1012" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/1367dd63-aef6-4351-ad3d-e7b30f4c33a2">

**Comment by annamorphism** [comment]
I believe Debra has also requested in the past some sort of way of checking off that all the other information (like genre, position, etc.) about a chant was proofread, while we are on the topic of little boxes...
