### ISSUE TITLE
We could merge the Chant Edit and Chant Proofread pages

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1034]
related to #1032, it might be a good idea to merge the Chant Edit and Chant Proofread pages. Currently, the Proofread page has all the same fields as the Edit page, plus checkboxes for the three "proofread" booleans and a dropdown allowing the user to select a "proofread by" (aside: I wonder whether there is any reason that a user would select anyone other than themself as a "proofread by").

It would be simpler to include all the fields on the Chant Edit template, but only display the "proofread" checkboxes if the user has permission to proofread that particular chant. If we did this, we could get rid of the Proofread page entirely.

I suggested this to Debra as a thing to discuss when she's in town in mid-October.

Are there any reasons not to merge these two pages? Is there any situation where a user will want access to _both_ the Proofread and the Edit page for a particular chant?

**Comment by annamorphism** [comment]
I think this sounds good! In fact it sounds much like the set up on OldCantus (except that in that case there were links to "proofread" pages that didn't actually work).

**Comment by lucasmarchd01** [comment]
We should also consider updating these fields if a chant has been edited. For example, if a user without proofreading permission goes to edit and save a chant that has already been proofread, the checkboxes should then reset to false (unchecked) until a user with proofread permissions checks them again. 

This is also linked to issue #170

**Comment by jacobdgm** [comment]
I emailed Debra about this:

> Just to summarize, to ensure I'm understanding correctly:
> - **We'll get rid of the Chant Proofread page**, and add its functionality to the Chant Edit page.
> - On the Chant Edit page, **we'll display the proofread checkboxes to:**
>   - **Project managers**
>   - **Editors who have been assigned to the source**
>   - Contributors with edit access for a source will be able to access the Chant Edit page, but will not see the proofread checkboxes.

and she responded:

> That sounds great!
> 
> I'm so glad to hear that you can enable the checkboxes for higher levels of contributors while keeping the page view available for contributors to continue to edit.
> 
> This is what we wanted in Old Cantus and it was tricky for Drupal to understand what we were trying to do.

So it sounds like we're on the right track with this proposed merger of the Chant Proofread and Edit pages! Increasing priority from Low to Medium.
