### ISSUE TITLE
Source Edit page missing "liturgical occasions" field

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1051]
On OldCantus one of the fields when creating a source was "liturgical occasions."
![image](https://github.com/DDMAL/CantusDB/assets/67451875/e04cadd0-c0b6-4ae4-bda6-24adf7cb185c)

This does not seem to be present in NewCantus. I don't think this difference is documented in the list of known differences between OldCantus and New, so I don't remember if this was by design or not. I'm guessing not, since it also means there is no way for an editor to edit existing "liturgical occasions" on manuscripts created on OldCantus, unless I'm totally crazy.

**Comment by jacobdgm** [comment]
I don't think this omission was intentional. I'll get to work adding this.
