### ISSUE TITLE
We should have a tool to periodically check if NewCantus Production has gone down

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1070]
On another server someplace, we should set up a tool to periodically check if the NewCantus website has gone down and send an email to the maintainers.

Priority medium-high.

**Comment by ahankinson** [comment]
https://sentry.io/welcome/
https://grafana.com/products/cloud/

Grafana Cloud has a free tier that includes a multi-site checker so you can test your uptime and performance from multiple data centers around the globe.

**Comment by jacobdgm** [comment]
@dchiller just noting that I'm looking into this.

I've created free accounts on sentry.io, grafana.com and newrelic.com - while I'm pretty confident all three of them could do what we need them to do (i.e. occasionally ping a specified URL, and send an email if there's an error), all of them seem complicated to set up, designed to integrate with other tools that we don't use to do things that we don't need. I'll continue looking into this tomorrow, but if there's a simple tool to do what we need, I've not found it yet.

**Comment by jacobdgm** [comment]
for tomorrow: https://geekflare.com/monitor-website-uptime/ may be useful

**Comment by ahankinson** [comment]
The grafana monitor is super simple. We can look at this when we have our zoom call later.

**Comment by jacobdgm** [comment]
> The grafana monitor is super simple. We can look at this when we have our zoom call later.

This will be a good thing to look into and talk about - thanks!

As I said, I'm quite confident Grafana can do what we want it to - I'm just having a difficult time finding what I need in the documentation among the many other features they offer.

@fujinaga indicated at a meeting yesterday that this is very high priority, particularly for Cantus Ultimus, but also for Cantus Database. Considering this, my inclination is to find something very simple to use temporarily, and upgrade to something like Grafana and Sentry once we have the time to set them up thoughtfully.

**Comment by jacobdgm** [comment]
@softcat477 told me we already have this functionality for Rodan, so she's adding cantus.simssa.ca and cantusdatabase.org to the cron job that's already set up there. Thanks, @softcat477!

**Comment by softcat477** [comment]
So the cronjob is already up, and it accesses [cantus.simssa.ca](cantus.simssa.ca) and [cantusdatabase.org](cantusdatabase.org) every `0:00/06:00/12:00/18:00` and sends a simple email notification ONLY on failure. This is just a temporary solution to get the service up in 30 minutes. Will work on setting up a full monitor stack on Arbutus for all ddmal projects very soon.

**Comment by softcat477** [comment]
So the cronjob is already up, and it accesses cantus.simssa.ca and cantusdatabase.org every 0:00/06:00/12:00/18:00 and sends a simple email notification ONLY on failure. This is just a temporary solution to get the service up in 30 minutes. Will work on setting up a full monitor stack on Arbutus for all ddmal projects very soon.

**Comment by jacobdgm** [comment]
This is excellent - I really appreciate you setting this up, @softcat477!

Would it be possible to test more frequently, say every 60 minutes (or even more frequently)?

**Comment by softcat477** [comment]
done 🫡 (monitor every 5 mins)

**Comment by jacobdgm** [comment]
excellent! thank you!
