### ISSUE TITLE
We need a workflow for attaching CantusUltimus links to records

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1072]
a subset of #940, and a slightly simpler problem, because we know that URLs on CantusUltimus correspond to URLs on CantusDB in a consistent way.

This can probably be put together as a management command - whenever a manuscript is "published" on CU, we can run this command on the corresponding source in CantusDB and it will update the image links for all the chants in the source.

I'll get to work on this presently - should not be very difficult.

**Comment by ahankinson** [comment]
Shouldn't the images for GB-Ob Can Lit 202 be linked to the holding institution, rather that CU?

**Comment by jacobdgm** [comment]
> Shouldn't the images for GB-Ob Can Lit 202 be linked to the holding institution, rather that CU?

My understanding is that, whenever we have a published version of the MS up on CU, we should link there. Perhaps @fujinaga can comment further?

@dchiller - looking at a few pages on CU, I don't see a link to the holding institution for the images anywhere. Does this exist? If not, it would probably be a good thing to add - this way people could go from CantusDB to CU for a feature-rich view of the folio, and then go directly to wherever the images are hosted in case they want to download them or something.

**Comment by dchiller** [comment]
> My understanding is that, whenever we have a published version of the MS up on CU, we should link there. Perhaps @fujinaga can comment further?

This is also my understanding based on @fujinaga 's comment here: https://github.com/DDMAL/CantusDB/issues/940#issuecomment-1711038114

> Does this exist?

Not in a public-facing way. 

> then go directly to wherever the images are hosted in case they want to download them or something.

They can download directly from Cantus Ultimus. We should have an image credit system. But a link...to where? Maybe the example I know best just happens to be the most complicated one, but take Salzinnes: should it link to IDEM/the Alamire Foundation (they host the images)? Should it link to St Mary's University? Your comment suggests this is image-focused, yeah?

**Comment by annamorphism** [comment]
> They can download directly from Cantus Ultimus. We should have an image credit system. But a link...to where? Maybe the example I know best just happens to be the most complicated one, but take Salzinnes: should it link to IDEM/the Alamire Foundation (they host the images)? Should it link to St Mary's University? Your comment suggests this is image-focused, yeah?

Salzinnes is indeed a complicated case, and has also linked to CU within Cantus for a long time (always??). But for, say, the Hartker antiphoner, CantusDB has long pointed people to e-codices, and I can imagine people wanting/expecting to be directed there (where it is also easier to find other books from St-Gall or whatever). I actually think this is not a CU problem but rather that CantusDB should provide both a link to the holding library (maybe in the source description?) *and* to the richer features on CU, but that would be something to discuss with Debra (off-the-cuff on my part!).

**Comment by dchiller** [comment]
> But for, say, the Hartker antiphoner, CantusDB has long pointed people to e-codices, and I can imagine people wanting/expecting to be directed there (where it is also easier to find other books from St-Gall or whatever).

Yeah, this makes sense.

> I actually think this is not a CU problem but rather that CantusDB should provide both a link to the holding library (maybe in the source description?) and to the richer features on CU, but that would be something to discuss with Debra (off-the-cuff on my part!).

This is definitely an interesting idea...makes a lot of sense.

**Comment by ahankinson** [comment]
The IIIF manifests usually have a `requiredStatement` that are required, by the spec, to be shown by viewers. This usually specifies the institution that provides the images. 

There is also a `provider` section that can give more information about the source of the manifest.

https://iiif.io/api/presentation/3.0/#requiredstatement

IIIF v2 had `attribution` and `logo` sections.

**Comment by dchiller** [comment]
Wow...thank you! I didn't realize Cantus Ultimus was not up to standard in this way. Made an issue at DDMAL/cantus#786.
