### ISSUE TITLE
Admin area, change chant page: "title" field should be hidden

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1075]
The "title" field is only used for sequences and never for chants, so this field should be hidden from the Chant Change page in the Admin area.

Debra sent us a message asking us what this field was for, so since this is a simple fix, we should hide this field before it causes further confusion.

**Comment by annamorphism** [comment]
i have yet to find a sequence that actually uses this "title" field, so I am still wondering what it is supposed to be for. @jacobdgm can you possibly dredge up an example where this is non-empty?

**Comment by jacobdgm** [comment]
> i have yet to find a sequence that actually uses this "title" field, so I am still wondering what it is supposed to be for. @jacobdgm can you possibly dredge up an example where this is non-empty?

```python
>>> w_title = Sequence.objects.filter(title__isnull=False)
>>> w_title.count()
17281
>>> five_w_title = w_title[:5]
>>> five_w_title
<QuerySet [<Sequence: "Maiestati sacrosancte militans ... Sic versetur laus in ore" (631688)>, <Sequence: "[Fulgens preclarum] ... ovanter prelia" (624019)>, <Sequence: "Sanctissimi virginis votiva festa" (630952)>, <Sequence: "Xpe tua agmina iubilant" (620478)>, <Sequence: "Sit iocunda deo nosto laus" (620479)>]>
>>> Sequence.objects.all().count()
17281 # note that this implies every single Sequence object has a title
```

You can verify this by looking at any Change Sequence page in the Admin area.

With one class of exception, `sequence.title` is the same as `sequence.incipit`. There are 940 exceptions, where `sequence.incipit` is `None`, and `sequence.title` is `"[...]"`.
