### ISSUE TITLE
Source Detail Page/Sidebar: Allow for multiple image views (Cantus Ultimus and host institution)

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1079]
In an email from Debra:

> For the Cantus Ultimus sources, Jennifer and I would like those to be one of the optional "views" in the RH menu. See the screenshot and imagine that "View on Cantus Ultimus" is one of the ways to see the material.
> 
> We might rename these links (because someone coming new to the site might not know the difference between them), but 1 would go to all chants in ms order in a view that shows the fields we have deemed more important with the benefit of a full text (can it be the MS spelling if it is included instead of the first full text?) and Volpiano melody; 2 would go to the "phonebook style" listing (for those of you who know what a phonebook was) where you can easily scan/scroll through the entire thing and see it all lined up (this remains one of the views by request of many researchers - we can't ever take this one away); and 3 would be a link to the Cantus Ultimus version (in a new window, of course, so the user can get back to CantusDB if they want).
> 
> For the other sources in CD & CU, I would like to keep the image libraries pointing to the archive where they are stored (i.e., Gallica, e-codices, etc.) so we continue to credit the correct people.
> 
> Does this all make sense?
> We want to interconnect CD & CU as much as possible now, especially since we have control over the coding of both sites. Back and forth between the two makes a lot of sense to me, and if we can get the additional menu option in CD for the CU sources, we can promote those within CD more, since I expect researchers who don't know about CU yet will love that they can get the Cantus data onscreen beside the images.

@annamorphism responded, summarizing thus:

> OK, so you're imagining the connectivity happening at the level of the source, but not with individual chant records linking to their Cantus Ultimus counterparts (except for Salzinnes).  That seems doable! We can make it a "feature request." (I think in principle—Jacob and Dylan can correct me here-- the chant records could also have an "image link" and a "view on Cantus Ultimus" link, if we wished, which might give even more interconnectivity—or would that be too much of a good thing? Or maybe it's harder to program than I imagine.)

**Comment by jacobdgm** [comment]
It would be easy to add this field while keeping the "image gallery" link intact.

I agree with @annamorphism that it could be a good idea (and it would not be very difficult) to add a "view on Cantus Ultimus" link to Chant Detail pages (and thus to the Chant model).

**Comment by dchiller** [comment]
On source detail page (see sidebar on upper right)

<img width="1185" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/413cfb59-9845-4f9a-bb01-58db41410f1e">

On source browse chants page (see sidebar on upper right)

<img width="1323" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/dc3f5035-18dc-47d5-9964-43d356c590ca">

From the top of the sidebar list of links, we want:

1. "View all chants" -- this stays...
2. "View full inventory" -- this stays...
3. "View inventory with images" -- this links to Cantus Ultimus, where possible
4. "View images on external site" -- this links to the host institution, if possible
... continue with the rest of the links

**Comment by lucasmarchd01** [comment]
Adding a plan for implementation details before moving forward:

- [ ] Add a new URLField on the Source model `cantus_ultimus_link` that points to the manuscript on Cantus Ultimus where possible
- [ ] Populate this field by creating and running a management command that goes through all sources/chants and adds a link to the corresponding manuscript/chant page on Cantus Ultimus
    - I choose to do it this way instead of a migration operation to populate these fields in case the script needs to be run again. We could potentially just modify the `add_cantus_ultimus_links` command.
- [ ] Add the "View inventory with images" and "View images on external site" links to the sidebar on relevant pages.
- [ ] Add a link to view a chant on Cantus Ultimus on the Chant Detail page where possible, otherwise the host institution (we actually don't need a new field in this case)

Referencing #429 and #1418

**Comment by dchiller** [comment]
> * Add a new URLField on the Source model `cantus_ultimus_link` that points to the manuscript on Cantus Ultimus where possible

The nice thing is that we no longer need to do this, because we've harmonized the ID's of Cantus Ultimus sources with CantusDB ID's. So, if the CantusDB ID is `123456` the "cantus_ultimus_link" will always be `https://cantus.simssa.ca/manuscript/123456/`


Similarly, you can link directly to a chant on CU with the right query parameters: `folio` and `chant`. `folio` would correspond to the `folio` field of a CantusDB chant, and `chant` would correspond to the `c_sequence` of a CantusDB chant. 

So, to go to the 5th chant on folio `034r` of source `123456`, you could construct the link as:
"cantus.simssa.ca/manuscript/123456/?folio=034r&chant=5"

**Comment by lucasmarchd01** [comment]
> The nice thing is that we no longer need to do this, because we've harmonized the ID's of Cantus Ultimus sources with CantusDB ID's. So, if the CantusDB ID is 123456 the "cantus_ultimus_link" will always be https://cantus.simssa.ca/manuscript/123456/

Right! I noticed this while working on the issue. I wasn't 100% sure about this question though: if there is a source on Cantus Ultimus (and CD), can we say for certain that there will be a mapping of _every_ chant in CD to CU? Or will there be instances of missing chants?

We still need a way of checking if the source exists on CU, what I had done previously was in the management command send a request to CU for every source, see if it exists, and then populate the new field. Instead if we aren't using the new field there are a couple of options:

- We could do a request in the view each time a source page loads to see if it exists on CU before displaying the "View inventory with images" link
- We could have the "View inventory with images" link display on every source regardless if it exists on CU or not, which will lead the user to a 404 for sources that don't exist on CU.

We would still need the management command to populate the `image_link` field on the `Chant` model. Which option sounds more reasonable for sources?

**Comment by dchiller** [comment]
> if there is a source on Cantus Ultimus (and CD), can we say for certain that there will be a mapping of _every_ chant in CD to CU?

Yes, I think we can say this. There is, I guess, the possibility that there would for whatever reason only be images available for part of a source, but where the whole source had been inventoried in CantusDB -- there have been no cases that I've seen where that is true and I'm not sure in that case we'd put it on CU anyway, so I think we can assume that it won't happen (or that if it does at some point in the future, some additional changes would need to be made).

I'll just tag @fujinaga and @annamorphism here in case they have thoughts about this.

**Comment by dchiller** [comment]
> We still need a way of checking if the source exists on CU, what I had done previously was in the management command send a request to CU for every source, see if it exists, and then populate the new field.

Yes, good point. When I was talking to Debra about this, we had discussed just having a checkbox on a source in the Admin panel -- there are only a dozen-ish sources on CU at the moment, and any additional ones would be added incrementally, so the thought was that it wouldn't be an issue to do manually.



> * We could do a request in the view each time a source page loads to see if it exists on CU before displaying the "View inventory with images" link

This is an idea (the one below it where the links would have 404's seems less ideal)...so it seems like the options are: (1) designate the sources that are on CU manually, (2) check all sources for whether or not they are on CU at some interval, or (3) check a source every time it is viewed.

A con of 2 is that if you happen to run this and you are unlucky (CU is momentarily not responding), you'd have the links disappear until it was run next -- so you'd either have to build something robust against that or just take the risk.

**Comment by lucasmarchd01** [comment]
> Yes, good point. When I was talking to Debra about this, we had discussed just having a checkbox on a source in the Admin panel -- there are only a dozen-ish sources on CU at the moment, and any additional ones would be added incrementally, so the thought was that it wouldn't be an issue to do manually.

This makes sense! In that case I like option 1. We can add a boolean field `exists_on_cantus_ultimus` to the `Source` model that can be checked whether or not to display the CU link and manually add all the existing sources.

Another thought about the `Chant` level links -- Do we want to preserve the original host institution links in the `image_link` field, or are we replacing that link entirely with the CU link if it exists? Because we could use `Chant.source.exists_on_cantus_ultimus` to display the CU link on the Chant detail page but still have the host institution link stored the database. It might be confusing to users though when they go to edit a chant and find that the image link doesn't match, so it could be better to just replace them.

**Comment by dchiller** [comment]
> This makes sense! In that case I like option 1. We can add a boolean field `exists_on_cantus_ultimus` to the `Source` model that can be checked whether or not to display the CU link and manually add all the existing sources.

Ok, makes sense to me!

> Do we want to preserve the original host institution links in the `image_link` field, or are we replacing that link entirely with the CU link if it exists?

Hmmm... this is a good question. My initial thought is to keep them since we've already gone to the trouble to get them? And I could see replacing them in the full inventory table a la #1418 but deciding to have both links again on the Chant Detail page (where there are two) for #429.

**Comment by annamorphism** [comment]
> Yes, I think we can say this. There is, I guess, the possibility that there would for whatever reason only be images available for part of a source, but where the whole source had been inventoried in CantusDB -- there have been no cases that I've seen where that is true and I'm not sure in that case we'd put it on CU anyway, so I think we can assume that it won't happen (or that if it does at some point in the future, some additional changes would need to be made).

There is a mini-case of this in the Gottschalk fragments, actually--there are I think two chants that were readable from a strip of parchment stuck to a book cover, and so got put in the inventory, but for which we do not (yet) have images (the strips in question are much harder to take a picture of than the rest of the page, and live in a different institution.) That is a pretty weird case, though, so I wouldn't build in too much to account for this one exception (basically, this should only be an issue for composite/fragmented sources, and we may want to handle those differently in the future anyway.)

**Comment by annamorphism** [comment]
illustration for reference--the first complete chant is "locutus est", and we can see the very last word of the preceding chant, but "Aedificavit Noe" listed on the right is not in fact visible in the picture. 
<img width="1146" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/1694fcda-cb51-48f9-8c1c-a87b4edff029">

**Comment by dchiller** [comment]
Thanks Anna! The other thing to add is that if you do pass a `folio` or `chant` parameter to Cantus Ultimus that doesn't exist, you are still given a `200` reponse (if the folio exists but the chant doesn't, you are sent to that folio but with no chant open; if the folio doesn't exist, you are sent to the first image) -- so even in this Gottschalk case, there would be know way to know that the chant wasn't "on" CU by sending a request to CU. And in this case, too, the chant actually does "exist" on CU, it's just not in an image -- and CU doesn't track anything about images on a chant by chant basis, only on a folio-by-folio one. So... if I go to https://cantus.simssa.ca/manuscript/123609/?folio=052v&chant=1, the "Aedificavit" chant will open, even though it isn't in that image.

All of which is to say that I think that going with (1) where we designate a source's existence on CU manually on a source-by-source basis still makes the most sense. And then what we might consider changing is what happens on CU if a non-existent parameter is passed if we think it might be confusing/frustrating to users to get no message -- e.g. maybe a little pop-up that communicates that the folio wasn't found but we are sending you to the first page or the chant wasn't found but we are sending you to the folio.
