### ISSUE TITLE
source descriptions lose formatting

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1085]
the other day, making a source description, I noticed this field is no longer WYSIWYG as it was on OldCantus--I had to add html tags to get paragraph breaks, which was a little annoying (especially since I didn't know I would need to until after the fact.)
Today I noticed that this also affected some source descriptions of already existing sources:
https://cantus.uwaterloo.ca/source/693689:
<img width="473" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/2e1560e8-6f84-45e4-8197-33b0d273f458">
vs
https://cantusdatabase.org/source/693689:
<img width="589" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/4f0648a1-ae86-4479-a4c9-baf5030f5d85">

**Comment by jacobdgm** [comment]
Huh, I see what you mean.

We have a special WYSIWYG editor for creating news articles which we could use here, but that would be overkill if I understand correctly - the issue is just that line breaks should be preserved, correct?

**Comment by jacobdgm** [comment]
let me look into whether there's an easy way to preserve line breaks when displaying fields containing lots of text. I'd be really surprised if this was not a problem other people have already encountered and solved.

**Comment by annamorphism** [comment]
@jacobdgm The source linked here is still a big block of text; so is e.g. https://cantusdatabase.org/source/710572 even though in the edit page there are breaks 
<img width="764" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/97401c88-48b5-4130-b688-69042ef7fcd9">
<img width="736" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/d5ac2b7b-3e60-478c-8ffe-212f467afd49">

Is this expected?

**Comment by jacobdgm** [comment]
All that's happening is that this change has not yet made its way to the staging or production servers. It's behaving as expected on my local setup.
