### ISSUE TITLE
stray "1" when no results searching sources

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1088]
When one browses sources and there are no searches, one sees the following:

<img width="973" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/647414ee-b8a1-46d7-8185-2b2eab8ef5dd">

The equivalent search of chants doesn't have this stray bolded 1.

**Comment by jacobdgm** [comment]
fascinating! curious as to what could be causing this...
