### ISSUE TITLE
sort headers don't work 

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1089]
When in chant search, the headers of each column LOOK like you can sort by them, and clicking on them gives you a dutiful little arrow pointing up or down. It doesn't, however, actually sort anything:

<img width="1086" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/57175726-095d-4631-9cec-609c5ac8ef51">

https://cantusdatabase.org/chant-search/?search_bar=notum%20fecit&order=office&sort=desc

**Comment by jacobdgm** [comment]
Looking into this a bit now, this seems to work in some contexts, but not others?

- https://cantusdatabase.org/chant-search/?op=contains&keyword=principium%20et (query returns 43 results, so they all fit on one page) - All the column headers seem to work as expected (though I can't test the Genre column header for this search, as all the results are antiphons).
- However, looking at a search with more results https://cantusdatabase.org/chant-search/?op=contains&keyword=princip, something weird is going on. Sorting by melody, we get two melodyless chants appearing up top when melodyful chants should be at the top of the list: https://cantusdatabase.org/chant-search/?op=contains&keyword=princip&order=has_melody&sort=asc

**Comment by jacobdgm** [comment]
Something is certainly still messed up in the initial Notum Fecit search you posted, @annamorphism.

**Comment by lucasmarchd01** [comment]
I think I've identified why @annamorphism's initial search using https://cantusdatabase.org/chant-search/?search_bar=notum%20fecit&order=office&sort=desc didn't work.

If a user searches for chants using the global search bar (which adds the `?search_bar=` parameter), the logic that filters the queryset using the column headers (Line 388) is completely skipped:
https://github.com/DDMAL/CantusDB/blob/fcf31afe26527180e7ede0afa80e8bb760830806/django/cantusdb_project/main_app/views/chant.py#L346-L392

So if the user uses the "keyword search" on the chant search page (which adds `?op=contains&keyword=` to the URL) then everything works as expected.

> However, looking at a search with more results https://cantusdatabase.org/chant-search/?op=contains&keyword=princip, something weird is going on. Sorting by melody, we get two melodyless chants appearing up top when melodyful chants should be at the top of the list: https://cantusdatabase.org/chant-search/?op=contains&keyword=princip&order=has_melody&sort=asc

In my mind, sorting by ascending order makes sense to place the melodyless chants first, however, I think that most people would expect the descending order to be the default behaviour when the melody header is clicked.
