### ISSUE TITLE
Some sidebars don't display properly

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1091]
For some reason St-Gall 390 (https://cantusdatabase.org/source/123717) has the sidebar at the bottom of the page in italics, like so:

<img width="1175" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/6f3657db-2824-4ba6-80c3-9fc9400b548f">

Many other manuscripts I tried display the sidebar correctly, so I don't know what's wrong with this one.

**Comment by jacobdgm** [comment]
see also https://cantusdatabase.org/source/123672, which @dchiller

**Comment by jacobdgm** [comment]
see also related issues #849, #472

**Comment by annamorphism** [comment]
I don't notice a problem on https://cantusdatabase.org/source/123672 --am I crazy?

**Comment by annamorphism** [comment]
BUT I just noticed that the same problem source from earlier (St-Gall 390, https://cantusdatabase.org/source/123717) puts not only the sidebar, but in fact the whole footer in italics:
<img width="926" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/8f5b9a37-9de5-44b7-8803-fa5e0372f51e">

**Comment by dchiller** [comment]
> I don't notice a problem on https://cantusdatabase.org/source/123672 --am I crazy?

So interesting! I definitely get it on that source...across multiple browsers

**Comment by jacobdgm** [comment]
> ...puts not only the sidebar, but in fact the whole footer in italics:

To the extent that there exist charming bugs-- this is a charming bug :) 🐛

**Comment by dchiller** [comment]
I think we can consider this closed. I don't get this issue on any of the aforementioned sources anymore, and I suspect that it was solved in the course of our templating changes in #1488 (and maybe #1537?)
