### ISSUE TITLE
We should update our DNS configuration to not use a wildcard for subdomains

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1095]
note that you can visit https://subdomain-i-just-made-up.cantusdatabase.org. This should not be allowed.

We discovered this is a problem by looking in the Google search console, where we saw that Google is trying to index mass.cantusdatabase.org (which was temporarily set up for a short while several years ago). We need to prevent people (/agents, including Google's crawlers), so that Google doesn't try to send users to this site within its search results.

**Comment by ahankinson** [comment]
At the same time you can set up configurations for your dev and staging sites so that you can deploy dev.cantusdatabase and stage.cantusdatabase.

**Comment by jacobdgm** [comment]
This is now fixed!
