### ISSUE TITLE
we applied a hotfix to production for `touch_ci_json_con_api`

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1098]
and we need to implement a proper fix. This issue under construction.

**Comment by annamorphism** [comment]
is this the issue with the concordances? depending on the time frame of this fix, can we have the interim message display something like "the concordances feature is currently under construction" rather than "Cantus encountered an error...". One makes it look like something is wrong (I have had somebody report it to me) while the other is a little clearer that we know about it.

**Comment by jacobdgm** [comment]
we can apply another hot fix if you think it's important. I hope we can get to this soon, so I might favour properly fixing this as soon as we can, rather than making more changes directly on the production machine.

**Comment by annamorphism** [comment]
that's fine! I would rather have things properly fixed, but if the solution does end up being "not do concordances until things are sorted at Cantus Index" then we should signal that to users.

**Comment by jacobdgm** [comment]
I think we'll be fine to fetch concordances from CI before too long (the cached ones - we definitely need a more robust solution for requesting refreshes).

Thinking about this over the "weekend", one component issue of the heavy traffic we were passing on to CI is that we were not waiting for CI to recalculate concordances before returning a response:
- if, when someone requested a chant detail page, we waited for CI to update its stored concordances before returning a response, then whatever bot was crawling our site would have had to move more slowly.
- with the approach we had implemented until recently, however, we returned a response much more quickly than it took for the CI databases to process their API requests. This allowed the crawler to quickly visit many pages, causing all the requests to CI to pile up.

For requesting updated concordances, I think there are two approaches that could work similarly well:
- First is that we implement a "refresh concordances" button that sends a request to CI's /refresh endpoint, waits for a response, and then reloads the page (or, dynamically updates the content in the table). Debra said this is less than ideal, so maybe let's consider a second approach.
- Second, we keep a local copy of concordances for all CantusIDs, which we automatically update from time to time. If we want to do this, we should get to work on #410. I'm going to bump the priority on this one from low to high.

**Comment by jacobdgm** [comment]
Some notes to myself: I've been thinking that, as an initial step, it would be a good idea to configure nginx to do some rate limiting (i.e., throttling) of requests from any particular IP address. Looking at the network requests while loading the homepage, I see 13 requests made for resources (e.g., images etc.) hosted on cantusdatabase.org. So we'd need to ensure that bursts of traffic are allowed - based on the number of requests I observed, 20-25 could be a good number of requests to allow in a burst.

**Comment by jacobdgm** [comment]
This has been addressed by #1142. Closing.
