### ISSUE TITLE
Created sources not showing up in "sources created by user"

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#110]
I added a new source after logging in. However, when checking back on the my-sources page, I don't see that source in the "sources created by user" list to the right of the page. It is also not listed under "my sources". 
As I'm the one who created the source, I think it's reasonable to associate that source to me in some way. This needs to be implemented.

**Comment by jiwoojeongjj** [comment]
- The original CantusDB does not have any sources listed under "sources created by user" either. Also, would it not be redundant to have the same list under both "my sources" and "sources created by user"?
- As for the second question: I believe to implement this, we would have to update the Source model to add a ForeignKey field that associates the source object with a user. Are you fine with me updating the model for this modification?

**Comment by jwang44** [comment]
If you create a source on the old Cantus, does it show up under "sources created by user"? I think it should. It makes much more sense if the sources created by the user are actually listed under "sources created by user". I think we should implement it like this, regardless of what the old Cantus does. 

It is not redundant because they are not the same list. 
"My sources" should have the source that the user has any kind of `write` access to. This includes the sources they created, edited, or proofread. 
"Sources created by user" should only have the sources they created. 

To associate a source object with the user who created it, I suggest using the `inventoried_by` field. If this later turns out to be inaccurate, we'll change it then.

**Comment by jiwoojeongjj** [comment]
The current `inventoried_by` field relates to the Indexer model. Should I update this field to relate to the User model?

**Comment by jwang44** [comment]
Yes. Please do. Thanks

**Comment by annamorphism** [comment]
in case it helps:
In Old Cantus, what you create is added to "Sources created by User" automatically. It doesn't show up under "My sources" until your name is added under "Current editor" on the source page (note: this is *not* a required field.)  So, on the one hand, My Sources includes many sources the editor might have access to, but didn't personally create (a very common scenario); and on the other hand, "sources created by user" might include sources you created, but for some reason aren't editing. (To be honest, I don't know why the creator isn't an editor by default.) 
Images of what this list looks like for me in Old Cantus with a dummy source (note: I had to add myself as an editor separately).

![image](https://user-images.githubusercontent.com/67451875/171061510-5f1dd3d0-1e1e-4245-b868-352e599174f3.png)

![image](https://user-images.githubusercontent.com/67451875/171061595-cc05de5c-c3cf-4b79-a764-ce94e89019ae.png)

after adding myself under "editor": 
![image](https://user-images.githubusercontent.com/67451875/171061570-b14c5899-8049-4336-a225-af42f3581730.png)

**Comment by jwang44** [comment]
Hey Anna. Thanks for this information. Very helpful!

>  It doesn't show up under "My sources" until your name is added under "Current editor" on the source page

Does a source show up under "My sources" when I'm not a "current editor" but a "proofreader"?

Related question: when a source is "inventoried by" a person, does it mean that person created that source?

**Comment by annamorphism** [comment]
Good questions, @jwang44 ! 
The roles of "inventoried by" and "proofreader" don't seem to be ones I can assign (or if I can, I've never learned how)--everybody I put in shows up as "editor". And although I am proofreading several things, I don't think I have the status of "proofreader" anywhere! However, everything to which I have been added as a secondary editor shows up under My Sources. 

A person can inventory a source without necessarily creating it. See below, where a team of people inventoried the source, but presumably only one person created it. 
![image](https://user-images.githubusercontent.com/67451875/171233422-a452c011-b26a-4362-8a2f-c38b13d0bb9c.png)
It's even possibly that somebody not listed created the source but then didn't inventory it. Basically, a source has a unique creator, which is internal information--who made this node?--but many possible editors, who have access under My Sources. The "inventoried by" and "proofreader" labels are basically external facing, so viewers know who did what, but are not (as far as I know) relevant to how one can interact with the website.

**Comment by jiwoojeongjj** [comment]
Thanks for the screenshots, Anna! They were very useful in creating the "Sources created by user" container on the right.
