### ISSUE TITLE
Chant suggestions are showing empty boxes

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1106]
On the chant create page sidebar, suggestions based on the previous chant are currently not working because of our recent changes on production that stop our requests to Cantus Index.

We should either hide these suggestion boxes or display a message that says this tool is currently unavailable until we restore our communications with Cantus Index.

![image](https://github.com/DDMAL/CantusDB/assets/71031342/0fdc2f52-ec90-4297-99d7-4609b66058ef)

**Comment by jacobdgm** [comment]
This is almost certainly related to us turning off requests to CI.
