### ISSUE TITLE
add DDMAL, McGill, LinkedMusic and DACT logos to footer

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1109]
Request from @fujinaga to put the DDMAL (and McGill and LinkedMusic?) logo(s) in the footer.

**Comment by fujinaga** [comment]
Yes, please add McGill and LinkedMusic logos as well.

On Oct 27, 2023, at 11:38, Anna ***@***.***> wrote:

﻿

Request from @fujinaga<https://github.com/fujinaga> to put the DDMAL (and McGill and LinkedMusic?) logo(s) in the footer.

**Comment by jacobdgm** [comment]
Do we leave the UW and Dalhousie logos, because Debra is still associated with both (and Jennifer with Dal)? What about the Margot logo?

**Comment by jacobdgm** [comment]
And should the DACT logo be added as well?

**Comment by fujinaga** [comment]
Yes, DACT logo as well.

**Comment by fujinaga** [comment]
Keep existing logo as they are.

**Comment by lucasmarchd01** [comment]
Closing with #1482, where we had specific instructions on how to update the footer.
