### ISSUE TITLE
Some redirects return `302` when they should probably return `301`

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1110]
In my excavations of the CantusDB logs, I discovered that responses to some requests that I think are permanent redirect are actually returning `302` responses. 

In particular, `/node/<id>` and `/office` return `302`'s rather than `301`'s. My understanding is that both of these redirects are permanent for the purpose of harmonizing Old and NewCantus URLs.

**Comment by jacobdgm** [comment]
And `301` indicates a permanent redirect, correct?

We should be a bit careful - in something relating to DataLake earlier today, we were talking about renaming, say, `/sources` to `/source`. We've already switched `/genre` to redirect to `/genres`, so we should be careful not to swap things back and forth.

**Comment by jacobdgm** [comment]
Redirects that should be permanent, I think:
- `sites/default/files/csv/<str:source_id>.csv` -> `source/<str:source_id>/csv/`
- `node/<int:pk>` -> source, chant, sequence, etc. detail page
- `indexer/<int:pk>` -> the relevant user page
- `sites/default/files/documents/1. Quick Guide to Liturgy.pdf`, `sites/default/files/documents/2. Volpiano Protocols.pdf`, ..., `sites/default/files/HOW TO - manuscript descriptions-Nov6-20.pdf` -> the relevant static files

some which we may not be certain about:
- `/genre` -> `/genres` (but maybe this one is properly permanent?)
- `/office` -> `/offices` (ditto)
- (somehow, `/feasts` has always been `/feasts`...)

**Comment by dchiller** [comment]
> And `301` indicates a permanent redirect, correct?

Yes

**Comment by jacobdgm** [comment]
Looks like this will be trivial to implement once we're very confident of our list of permanent redirects. `return redirect(reverse("csv-export", args=[source_id]))` becomes `return redirect(reverse("csv-export", args=[source_id]), permanent=True)`

**Comment by jacobdgm** [comment]
Going to make an executive decision and say we're currently happy with all of our redirects, and that we should communicate that they are permanent. This will just require someone going through all the `redirects` in our views and adding a `permanent=True` kwarg.

**Comment by dchiller** [comment]
Looks like this was solved in #1582...closing
