### ISSUE TITLE
Melody Search tool is buggy

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1128]
The [Search Chants by Melody](https://cantusdatabase.org/melody/) tool is buggy. When the window is narrow, the level of the moving notehead gets displaced from the y position of the cursor, and the staff spills onto a second line. In some situations, the entire tool lags/freezes. We need to figure out what's going wrong and fix it.

**Comment by annamorphism** [comment]
same as #1127

**Comment by jacobdgm** [comment]
I think this is now fixed, via #1130 (though I'm not certain that the lagginess has been addressed)

Going to close this; we can reopen it if necessary.
