### ISSUE TITLE
create link to differentia database

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1137]
In an email, Debra requested the chant-edit pages (and chant-detail pages) to include a link to differentiaedatabase that opens in a new tab, so that the user can more easier search for differentiae while editing or proofreading. This was in OldCantus, like so:
 
<img width="499" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/b1aa90e6-7117-48bd-a947-5446bff27589">

From this conversation it emerged we would also in the longer term like to have a tool to enter without having to go to an external site (see #436 ), but this doesn't have to be a priority right now.

**Comment by jacobdgm** [comment]
> the chant-edit pages (and chant-detail pages)

I'm assuming you mean the Chant Edit and Create (rather than Detail) pages

**Comment by annamorphism** [comment]
> I'm assuming you mean the Chant Edit and Create (rather than Detail) pages

Yes, I think I did...on  the Detail page there is a link to the differentia in question, which is better than a link to the homepage of the differentiae database.
