### ISSUE TITLE
We should implement the CantusIdentifier model

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1143]
With #1141, we have added the CantusIdentifier model to our database. Once we have a way of getting concordances from CI, we can start using this model to store CI data and use it internally instead of making requests to CI. 
Here are potential uses and benefits of using the CantusIdentifier model:

_Originally posted by @jacobdgm in https://github.com/DDMAL/CantusDB/issues/410#issuecomment-1731370051_

> An email I just got from Jan re: #1029 has got me thinking about this again. The potential effects of creating this include:
> - CantusIDs would be a controlled vocabulary - when creating/editing chants, users would have to select from a list of existing CantusIDs instead of entering one freehand (thus limiting the possibility of typos)
>   - we can also ensure that when a user selects a Cantus ID, the chant's Genre is automatically set to the genre associated with the CantusID
>   - we would need to talk with Debra about how new CantusIDs are created - if a user is indexing a manuscript, will they ever need to invent a new CantusID? Would such a CantusID need to be added to CantusIndex first before it can be selected in CantusDB
> - It would be easy/efficient to cache concordances from CantusIndex, since these concordances belong to specific CantusIDs and not to specific chants. This would also allow us to continue to display concordances even in case of a temporary outage on CantusIndex
> - For the Input Tool, this would allow us to store canonical texts and genres for all CantusIDs
> - For the previous two points, performance would probably also be improved, because we won't need to send requests to CantusIndex in order to load our pages - we'd just need to query our own database.

**Comment by jacobdgm** [comment]
As I just said in #410, I believe we've decided not to add such a new model to the database. We can get most of the potential benefits of a new model by other means, and in doing so, avoid potential data integrity issues in case something goes wrong with CI. Closing.
