### ISSUE TITLE
We need some method to track which Cantus IDs have been merged

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1158]
Directly related to https://github.com/DDMAL/CantusDB/issues/877. For each Chant object in the database, it would be a good idea to keep track of each `cantus_id` it has had in the past. In case there is a problem with Cantus Index's https://cantusindex.org/json-merged-chants API, this would allow us to roll back erroneous changes.

There are several ways I can imagine setting this up.

One way would be to create a `CantusIDMergeEvent` model. I imagine it looking something like:
```python
class CantusIDMergeEvent(BaseModel):
    old_cantus_id = CharField() # or ForeignKey to CantusIdentifier model?
    new_cantus_id = CharField() # or ForeignKey to CantusIdentifier model?
    applied = BoolField() # has the merge been applied yet, y/n
    date_applied = DateTimeField() # if this merge has been applied, when did it happen
    ci_timestamp = CharField() # we've asked Jan to attach a timestamp to each merge event in the
        # json-merged-chants API, which we're hoping we can use as a unique identifier. This would
        # be the time that the merge was submitted on CantusIndex, i.e., when it was posted in the
        # json-merged-chants API
    applied_by = ForeignKey(model=User)

    chants = OneToMany(model=Chant)
    sequences = OneToMany(model=Sequence)
    # when a merge occurs, we use these two fields to record which chants/sequences were affected

    # we could consider adding a apply() and revert() methods, which would switch the `cantus_id` of
    # chant/sequence in the `chants`/`sequences` from `old_cantus_id` to `new_cantus_id` and back

    # N.B.: an apply() method would certainly require more thought - is `chants` calculated when a new
    # merger gets posted to CI's API, or when we commit the merge?
    # In any case, you get the general idea.
```

Since we're worried about Cantus IDs being changed programmatically when new merge events get posted to https://cantusindex.org/json-merged-chants (see https://github.com/DDMAL/CantusDB/pull/1141#issuecomment-1812749551 etc.), it would be easy to create a view that lists all the chants/sequences that would be affected by a given Merge Event, and would allow Debra to approve the merge. I'm hoping this would not be too much work for Debra to press "approve" on CD as well as on CI, and this would ensure that there's always a human in the loop when we're applying changes specified by Cantus Index.

Worth noting: this record will need to be attached to individual Chant/Sequence objects, and not to CantusIdentifier objects themselves (in case we go ahead with implementing them - see https://github.com/DDMAL/CantusDB/pull/1141 and https://github.com/DDMAL/CantusDB/issues/410). In case mutiple IDs get folded into a single ID and we need to roll back a single merge event, we'll need to know which of the chants associated with the new ID needs to be reset to the earlier ID.

**Comment by ahankinson** [comment]
This looks very complicated to get right. 

Store the chant ids as strings.
Use Django reversion to store model changes.

If something goes wrong, the history can be seen through the version history and reverted.

You can create a non-model based view that will analyze the output of the merge API and give a list of chants to be updated. Nothing actually needs to be stored in the database for this to happen. Simply query your database for chants matching the old id, and offer to update the chant to the new id. You could do “bulk approve” if you want, otherwise an “update chant” next to each change would serve as an implicit approval (I’m hoping only certain users would have access to this view)

**Comment by jacobdgm** [comment]
I asked Debra about a bulk approve page for each merger, and she said that it wouldn't work for her workflow.

**Comment by jacobdgm** [comment]
> Store the chant ids as strings.

i.e., you're suggesting that we do create a CantusIDMergeEvent, but that we keep track of the chants that were affected as a list of strings?

> Use Django reversion to store model changes.

i.e., if we have the list of IDs, a someone could look at all the chants and set them back to what they were before the merge event? This would also reset any other edits that may have been made since, correct?
