### ISSUE TITLE
Review OpenStack Security Groups

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1159]
I was just looking through the openstack security groups and noticed a few port-specific routes in the "default" group. Since this group gets applied to every machine instance, services such as web servers should have their own security group so that we can apply them only to the servers that need them.

I have created a new security group, `allow-www-world` that allows 80 and 443 on both IPv4 and IPv6. I would like to add this security group to the cantusdb-production instance, and remove the corresponding rules in the `default` group. However, it would be better if someone on the DDMAL admin team did this so that they could ensure it doesn't break anything in the process.

Additionally there are a number of SSH access IP addresses that should be moved from the default group. I reviewed some but left ones that looked like they were set up for a specific purpose. If nobody knows what they are, I will delete them.

**Comment by jacobdgm** [comment]
@kqct, @softcat477, are either of you able to look into this? If not, can you please unassign yourself from this issue?

If not: I don't fully understand this issue yet, but I can do some research into this.

**Comment by dchiller** [comment]
I don't know what any of the ssh rules in the `default` group are for (I believe anyone in DDMAL takes advantage of one of the rules in the `cantus-staging-access` group for access). So maybe those are related to other instances on Jennifer's allocation?


In terms of making the switch to the `allow-www-world` the idea is just to make sure that someone is on hand to notice if something goes wrong on Cantus Database? It's the same rule, just in a different group, right?

**Comment by ahankinson** [comment]
> It's the same rule, just in a different group, right?

Yep! In fact, I just added cantusdb-production to the new group. Since there are no objections, I'll remove the other rules and hope it doesn't break anything. (It shouldn't).

**Comment by ahankinson** [comment]
Done, and everything seems to work. Closing.
