### ISSUE TITLE
When LetsEncript certificate expires, it only emails one person

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1200]
![Screenshot 2023-12-07 at 11 52 03 AM](https://github.com/DDMAL/CantusDB/assets/58090591/e1c06c95-f8b3-4732-b31f-a7aa95bef85c)

I got this email a couple of days ago. To my knowledge, none of the other maintainers of CantusDB (@lucasmarchd01, @dchiller) got this email.

Hopefully, we get https://github.com/DDMAL/CantusDB/issues/870 set up properly eventually, but until that time, it would be ideal if more people than just me got this email. We should ensure it gets sent to someone who is going to be working on CantusDB for a length of time into the future.

For the time being, I updated the certificate manually, so we should be good to go until early March. I'm going to write some documentation on the wiki on how to manually update the certificate so that it's simple to do.

**Comment by dchiller** [comment]
As far as I can tell, the only person who is going to get the email is the person whose LetsEncrypt account is used for the certificate. We also do have a cron job set-up to do certificate renewal, so in theory (ha!), no one should ever get this email!

To close this issue, I think we should just update the email used by lego to no longer be @jacobdgm's. And then going forward, upon any change of personnel or email, this should be done.

**Comment by dchiller** [comment]
I've done a bit more poking around with lego and it looks like theoretically there should be a way to add an email (it seems supported by Let'sEncrypt and certbot but not really by lego - lol).

I think with https://github.com/dact-chant/ansible.cantus-db/pull/32 and our automatic set-up we should be okay for now, but I'll leave this issue open in case we can make more headway on it later.

**Comment by dchiller** [comment]
We're not gonna make headway -- group of us at the LinkedMusic meeting Oct 2024
