### ISSUE TITLE
We should return a 404 response when a user arrives at `/chants/` without query parameters

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1201]
...rather than the 500 Server Error that currently occurs.

The Chant List page, with the path `/chants`, expects a query parameter, `?source=` in order to load the page. This all works fine unless a user visits a source and then presses the `Log in` button. The path of the page they're currently on is preserved as a query parameter (e.g., if you are on https://cantusdatabase.org/chants/?source=711225 and press "Log in", the URL of the next page is https://cantusdatabase.org/login/?next=/chants/. Note that the necessary `?source` parameter is not preserved. Upon finishing the login process, you land at https://cantusdatabase.org/chants/, which generates the 500 error.

It might make sense to rework the URL of the Chant List page to something that works better as a URI (`/source/<source id>/chants`?) and set up redirects for backwards compatibility. I'll open a separate issue for this, but we should not hit a 500 error when no query parameters are included.

**Comment by ahankinson** [comment]
The correct response is a [400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400). This is a client error, since the request is missing required information. 

And definitely +1 to replacing it with a proper URI. That will be very useful for the LinkedMusic project.
