### ISSUE TITLE
Records count

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#122]
Copied from email from Debra Lacoste:
"it would be FANTASTIC on New Cantus to have a running count somewhere of how many records we have in the database. It can be the number of all records or just the proofread ones, or maybe both."

**Comment by annamorphism** [comment]
doesn't this already exist under https://cantusdatabase.org/content-statistics ? or does it not keep a running tally?

**Comment by jwang44** [comment]
Yes. A very similar functionality already exists in our "content-statistics" or "items-count" page, but this page is by default invisible to the public (as in old Cantus).

**Comment by jacobdgm** [comment]
http://206.12.93.196/content-statistics

**Comment by dchiller** [comment]
@jacobdgm @lucasmarchd01 In poking around, I noticed this in NewCantus staging was visible under the "About" menu even though I wasn't logged in. It then prompted me to log in, but it looks from the above discussion like this might not be the intended behavior.

<img width="1440" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/5d3a75e8-6c82-4fb5-8b8a-55c7b01366f0">
