### ISSUE TITLE
Source Detail: Siglum column should be to the right of Source column

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1223]

**Comment by annamorphism** [comment]
will the table then become ordered by default by the Source field (which is now the left-most column?) (This seemed to be in the email discussion and I remain a bit skeptical that it is actually desirable...)

**Comment by jacobdgm** [comment]
We can order by whichever field we want - the ordering of the columns makes no difference on the ordering of search results. I'll maybe open a separate issue to change the ordering of the sources on this page.
