### ISSUE TITLE
Source List page: we should order sources by Title instead of by Siglum

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1227]
Related to #1223 - on the Source List page, Debra and Jennifer have requested that we order sources by their title rather than by their siglum - currently, all the sources located in Austria (i.e. whose sigla begin with `A-`) are placed front-and-centre, whereas ordering by title would allow sources in other countries to show up on the first page.

**Comment by annamorphism** [comment]
it would also mean the sources on the browse page show up in a different order from how they are presented basically everywhere else on the site (or on Cantus Index for that matter, or the practice on DIAMM ...). Good news for anyone looking for Aachen Domarchiv G 20 I suppose, but sounds kind of confusing for anyone else...

**Comment by annamorphism** [comment]
(which is to say I would actually hold off on this and work on making the individual columns sortable as a higher priority...)

**Comment by dchiller** [comment]
Closing this. Given changes to source identification, the completion of #1569, and the continuing need for #1217, I think this is no longer relevant.
