### ISSUE TITLE
We don't have tests for our Chant Edit View

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1229]
Discovered while working on #1225, we don't have any tests for our Chant Edit View.

**Comment by lucasmarchd01** [comment]
Tests for the Chant Edit view are contained in the `SourceEditChantsViewTest`. I think that the url path for this view is a bit confusing, maybe we should consider matching the name to the url or vice-versa.
```
    path(
        "edit-chants/<int:source_id>",
        SourceEditChantsView.as_view(),
        name="source-edit-chants",
    ),
```

**Comment by jacobdgm** [comment]
Aha! Right, I renamed this view to to `SourceEditChantsView` a year and a half ago because the only ID in the URI was a source ID. I keep on thinking of it (and referring to it) as our Chant Edit view. @lucasmarchd01, @ahankinson @dchiller - would it be better to change it back to `ChantEditView`?
