### ISSUE TITLE
NewCantus volpiano treats bar lines and underlay differently from before

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1234]
Something is different about how NewCantus handles bar lines from OldCantus, e.g compare old and new https://cantusdatabase.org/chant/669059;

![image](https://github.com/DDMAL/CantusDB/assets/67451875/ac0a1633-99e5-4a13-9040-ce0cd59ff35b)

![image](https://github.com/DDMAL/CantusDB/assets/67451875/b9655192-fe31-4936-b20a-84277188764f)

A lot of Alleluia chants seem to have been affected by this change e.g. https://cantusdatabase.org/chant/642479

![image](https://github.com/DDMAL/CantusDB/assets/67451875/d7a2bc18-7a2e-41d5-8250-685a9a2b90ec)

I suppose we could find and fix every one of these, or change whatever it is about the Volpiano rules that makes this show up all weird and misaligned. (Tagging @dchiller since I believe he was looking into other Volpiano rules at some point.)

**Comment by dchiller** [comment]
Thanks! Yes, this should be fixed shortly

**Comment by annamorphism** [comment]
Possibly related: 
In NewCantus, if a chant does not end with "---" before a gap, the Volpiano displays as only a second treble clef. 
If it ends with 6------6 and no final ---, the Volpiano duplicates (!)
Behold (chant has since been corrected, so I won't link to it).
![image](https://github.com/DDMAL/CantusDB/assets/67451875/1b1f4b64-5ff0-48aa-8426-03504310ef30)

![image](https://github.com/DDMAL/CantusDB/assets/67451875/b744bace-c173-42f4-9b1c-d87932f990c5)

**Comment by dchiller** [comment]
This is also very odd behaviour! But I think should not be a problem anymore either. 

My hope is that https://github.com/DDMAL/volpiano-display-utilities/pull/26 is the last remaining thing to merge before we can put the new alignment procedures into play!

**Comment by jacobdgm** [comment]
I believe this has been fixed. Going to close, but tagging @dchiller - please glance over this to ensure it's actually done.

**Comment by dchiller** [comment]
I agree that this is complete in the sense -- these types of chants are well-aligned in NewCantus.
