### ISSUE TITLE
Staging and Production are both down

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1246]
A few minutes ago, I realized I can't access either staging or production:

https://www.cantusdatabase.org
http://staging.cantusdatabase.org

I can't ssh into the Production VM. I'm able to get as far as the jumpbox, but then I get this:

```
channel 0: open failed: connect failed: Operation timed out
stdio forwarding failed
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

I can't access either site via its IP address, so I don't think this is a DNS problem: http://206.12.88.113 (staging), http://206.12.93.196 (production)

Does anyone know what's going on?

**Comment by jacobdgm** [comment]
Ah. I see that Arbutus is down. When it comes back up, someone check that everything is working as it should be, and then close this.

**Comment by dchiller** [comment]
cantusdatabase.org seems to be back up for me, but since arbutus is still down, I'm going to leave this open for now.

**Comment by dchiller** [comment]
Arbutus is back, and it looks like cantusdatabase.org is functioning.
