### ISSUE TITLE
base_chant `diff_db` field and `Differentia` model need documentation

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1249]
I noticed that neither are documented in the code or the wiki. This makes it hard to figure out what's what, especially given that there a multiple *very* similarly named fields running around related to differentiae.

**Comment by lucasmarchd01** [comment]
Documentation for the [Differentia Model](https://github.com/DDMAL/CantusDB/wiki/Differentia-Model) and [diff_db field](https://github.com/DDMAL/CantusDB/wiki/BaseChant-Model#Fields) are now available.
