### ISSUE TITLE
json-activity

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#126]
OldCantus has a json-activity tool/API that we may want to implement.

- https://cantus.uwaterloo.ca/json-activity - by default, seems to show month-year pairings (each corresponding to one month within the current year) as keys and integers as values (guessing that they are edit counts?)
- https://cantus.uwaterloo.ca/json-activity?all displays something different: keys are years from 2010 to present, and values are dictionaries with keys "all" and "cid"

In an email, Debra Lacoste was unsure of what this feature is supposed to do: "HMMM. NO IDEA. I'LL THINK ABOUT IT AND LET YOU KNOW IF I REMEMBER ANYTHING ABOUT THIS. MAYBE THE NUMBER OF NEW CHANTS ADDED WITHIN EACH MONTH? DO YOU HAVE ANY OTHER WAY TO COUNT THAT TO SEE IF THESE ARE THE NUMBERS?" As it doesn't seem like a vital feature, I'm labelling this as a "wontfix"

**Comment by annamorphism** [comment]
Suspect it's supposed to give something analogous to what is on http://cantusindex.org/stat : 
![image](https://user-images.githubusercontent.com/67451875/171250912-3e735ef8-5820-451b-bdc7-5f3035d325ae.png)

**Comment by igneus** [comment]
> Suspect it's supposed to give something analogous to what is on http://cantusindex.org/stat

Quite probably the endpoint is interface for CantusIndex to collect data for this table.

(It's somewhat suspicious that there don't seem to be any issues in this project that would address the integration with CantusIndex. Is it planned at all?)

**Comment by jacobdgm** [comment]
Phew, this comment flew in under the radar!

> (It's somewhat suspicious that there don't seem to be any issues in this project that would address the integration with CantusIndex. Is it planned at all?)

#378 comes to mind. The idea that the two should work well together is always there in the background; the main idea at this stage is that NewCantus should do everything OldCantus does, i.e. any bits of integration already present should still work. Perhaps @fujinaga can comment further?

**Comment by fujinaga** [comment]
Yes, the integration of Cantus Database, Cantus Index, and Cantus Ultimus is one of the major  tasks of the LinkedMusic project.
