### ISSUE TITLE
It would be a good idea to save separate configuration files for staging vs. production

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1269]
This will simplify the deployment of changes to staging in particular.

Plan of action: for every file in https://github.com/DDMAL/CantusDB/wiki/Getting-Started-with-Development#docker-set-up (i.e., `docker-compose.yml` and `config/nginx/conf.d/cantusdb.conf`)
I should also review `cron.txt`, but I'm pretty sure this won't need any changes now that #1273 is complete.

Our deployment instructions can then be updated to be things like "run `cat docker-compose.yml.staging > docker-compose.yml`" rather than a series of "on the line that begins {thus}, replace {this} with {that}"s

**Comment by dchiller** [comment]
I think the only thing that changes here is the nginx configuration...in which case something like what we did with VIM (templating) might be even better! (see https://github.com/DDMAL/VIM/tree/develop/nginx -- `nginx.conf` and `vim.conf.template`)

**Comment by jacobdgm** [comment]
and `cron.txt`!
