### ISSUE TITLE
We should configure Staging to have the same directory structure as Production

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1273]
While @dchiller and I were working on fixing backups and certificate renewals, and updating the documentation for deploying new code to Staging and Production, it became clear that many things would become simpler if we configured Staging to have the same directory structure as Production.

Currently, the clone of `CantusDB` is located at `/home/ubuntu/code/` on Production and at `/home/cantusdb/` on Staging. Most (all?) of the cron commands, thus, need to be differently configured to run properly on Staging vs. on Production.

While this will take a little while to set up (likely <60m), this will be an easy fix - we just need someone to make a new clone of the repo within the proper directory, delete the old clone, and follow the steps outlined in https://github.com/DDMAL/CantusDB/wiki/Getting-Started-with-Development.

Once this is set up, it will become much easier to test new changes on that staging server, and facilitate the implementation of #1269, which will allow us to streamline our update-the-staging-server process.

**Comment by jacobdgm** [comment]
Ideally, this is completed before we next deploy new code to the Staging server - this will allow us to update and test changes to the crontab.

**Comment by ahankinson** [comment]
There should be new servers being built? And it would be a perfect job for Ansible to do this.
