### ISSUE TITLE
Postgres configurations are not active

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1283]
On the servers, values of the postgres configs are different than what's in the postgres conf... (Showing production here)

![image](https://github.com/DDMAL/CantusDB/assets/11023634/8380c196-18ed-4ecf-9dd7-baf123fe9cfa)

![image](https://github.com/DDMAL/CantusDB/assets/11023634/1c021e4c-7dee-4faf-9e6c-6ab0f54e4839)

`/var/lib/postgresql/data/postgres.conf` looks nothing like what's committed to the repo.

I wonder whether these databases were ever updated with the new configs//these looks like they are being overwritten every time?

**Comment by jacobdgm** [comment]
I just updated the Staging server to include this change, and looking at the active postgres configuration running there now, I can confirm that this worked. Thanks for catching and fixing this, @dchiller!
