### ISSUE TITLE
On staging, cron is not working

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1290]
After having merged #1284 and deployed those changes to staging yesterday, the database backups should have saved at least once by now, and the cached concordances should have updated at ~4h this morning. Neither has occurred.

**Comment by jacobdgm** [comment]
Also, I can't find backups at all. We probably lost the staging backups when I addressed #1273, but I can't find new backups on the VM, or in either of the django or postgres containers (though they shouldn't be saved inside a container, should they?)

**Comment by dchiller** [comment]
Database back-ups are on staging? 

<img width="599" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/16d513e8-1c75-4b49-849c-b78b3ac92540">

**Comment by dchiller** [comment]
![Uploading image.png…]()

**Comment by jacobdgm** [comment]
aha. i wasn't looking in the right place, evidently...

**Comment by jacobdgm** [comment]
in any case, updating the concordances is certainly not working.
