### ISSUE TITLE
Users assigned to Bower sources should be able to edit sequences in those sources

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1294]
Currently, only project managers can edit sequences. Debra requests that editors should be able to be assigned to Bower sources and edit the sequences contained therein.

**Comment by jacobdgm** [comment]
Most of the work to fix this will be in [`permissions.py`](https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/main_app/permissions.py) - It will require changing `user_can_edit_sequences` to look more like `user_can_edit_chants_in_source`.

**Comment by jacobdgm** [comment]
I didn't get any correspondence about this requested change. Does this seem more like a high-, medium- or low-priority issue, @dchiller?

**Comment by dchiller** [comment]
Came out of something Debra requested yesterday...will forward now to you @jacobdgm and @lucasmarchd01 so you have the context.

**Comment by dchiller** [comment]
Sorry, forgot to mention this 

> Does this seem more like a high-, medium- or low-priority issue, @dchiller?

I think high?

**Comment by annamorphism** [comment]
@jacobdgm I am pretty sure somebody is about to embark on a project to clean up some of the Bower stuff; they can probably postpone it some (since I think it is a side project) but better to have it sooner rather than later.

**Comment by dchiller** [comment]
Yes, @annamorphism, per Debra's instructions I gave her Debra-level access yesterday so that she could start work. When we get this up we will remove her Debra-level access and just keep her on as an "editor" of the Bower sources.
