### ISSUE TITLE
We should configure repo for deployment to Staging and Production using Ansible

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1296]
Further to #1269, we can streamline the Staging and Production deployment even more by using Ansible.

**Comment by jacobdgm** [comment]
I said I would work on this, but it looks like you may have already begun to attend to this @dchiller in your work on #1303. I'm going to assign you and me; feel free to unassign either of us if you think it makes sense.

**Comment by dchiller** [comment]
Closing this. Further ansible and deployment-related issues can be made on the DACT `ansible.cantus-db` repo
