### ISSUE TITLE
In source description sidebar, we should display a useful placeholder when a user's full_name is not set

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1310]
On our User Detail page, we display "User" when a user's `full_name` is not set.

We should consider doing something similar in the sidebar that can be found on the Source/Chant Detail page as well. In the screenshot below, Inventoried by is set to user 251687, whose email is set but who has no full_name.

![Screenshot 2024-02-13 at 9 16 04 AM](https://github.com/DDMAL/CantusDB/assets/58090591/2634802f-ce12-4965-9030-2e14a43f2876)

**Comment by ahankinson** [comment]
You should add the User’s ID to the label so that you can add least see if two inventories were created by the same user or different users.
