### ISSUE TITLE
We need to update our concordances export API for new specification

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1323]
In an email from Jan, who's working to use our [concordances API](https://github.com/DDMAL/CantusDB/wiki/APIs#concordances) on Cantus Index:

> There is a small issue with parsing your JSON: 
> You have a 'data' element and a Cantus ID element ("004650" in the following snippet) which is not necessary and not compatible with the current CI parser. 
> ```
> ["data":{"004650":[{"siglum":"A-KR VI\/258","srclink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/source\/123660\/","chantlink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/chant\/307346\/","folio":"060r","sequence":11,"incipit":"Rex autem David cooperto","feast":"De Regum","genre":"A","office":"H","position":"9","cantus_id":"004650","image":null,"mode":"?","full_text":null,"melody":null,"db":"CD"},{"siglum":"SI-Lna 19 (olim 18)","srclink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/source\/123659\/","chantlink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/chant\/356859\/","folio":"021v","sequence":2,"incipit":"Rex autem David cooperto","feast":"De Regum","genre":"A","office":"H","position":"10","cantus_id":"004650","image":null,"mode":"8","full_text":null,"melody":null,"db":"CD"},
>```
> 
> Is it possible to remove these elements and keep only what follows?
> ```
> [{"siglum":"A-KR VI\/258","srclink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/source\/123660\/","chantlink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/chant\/307346\/","folio":"060r","sequence":11,"incipit":"Rex autem David cooperto","feast":"De Regum","genre":"A","office":"H","position":"9","cantus_id":"004650","image":null,"mode":"?","full_text":null,"melody":null,"db":"CD"},{"siglum":"SI-Lna 19 (olim 18)","srclink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/source\/123659\/","chantlink":"https:\/\/[cantusdatabase.org](http://cantusdatabase.org/)\/chant\/356859\/","folio":"021v","sequence":2,"incipit":"Rex autem David cooperto","feast":"De Regum","genre":"A","office":"H","position":"10","cantus_id":"004650","image":null,"mode":"8","full_text":null,"melody":null,"db":"CD"},
>```
> 
> I understand that it's possible to develop a unique code for parsing the specific CD data format on my side, but for a sustainable solution, it would be beneficial if all CI-connected databases used the same system and format. 
> 
> Please let me know if you have some serious reasons for including the mentioned elements.

In a resulting email chain, it was noted that if we got rid of `"data"`, it would result in us losing `"metadata"`, the latter of which might be useful. @dchiller noted that we could include this data in a response header rather than including it in the file.

It sounds as if Jan just wants an array of all the chants, in no particular order, and not grouped by Cantus ID. Whatever we decide to do with `"data"` and `"metadata"`, this will be an easy change to make.

**Comment by jacobdgm** [comment]
If we stop grouping by Cantus ID, perhaps `/concordances` stops being an accurate URI, since it just becomes a list of all published chants in the database. We could implement an updated version without touching what's currently there, and it could live at `/chants/json`? (this could also be a step forward toward implementing #1305, where we could create `/sources/json`, `/genres/json`, etc.)

**Comment by dchiller** [comment]
> If we stop grouping by Cantus ID, perhaps `/concordances` stops being an accurate URI, since it just becomes a list of all published chants in the database.

Hmmm...good point. Maybe we can clarify with Jan that we don't want to group? I agree with your reading of his email request that it looks like he doesn't want grouping, but since it then becomes just a list of all chants I become confused by what we are trying to achieve here...

**Comment by jacobdgm** [comment]
Necessary next step: clarify with Jan what format he wants. Once we've done that, we can just implement it.

**Comment by jacobdgm** [comment]
> If we stop grouping by Cantus ID, perhaps `/concordances` stops being an accurate URI, since it just becomes a list of all published chants in the database. We could implement an updated version without touching what's currently there, and it could live at `/chants/json`? (this could also be a step forward toward implementing #1305, where we could create `/sources/json`, `/genres/json`, etc.)

It occurs to me that we will only be including certain information for each chant, whereas we would want a `/chants/json` API to include basically all the information for each chant. So `/concordances` should remain.

**Comment by jacobdgm** [comment]
Having checked in with Jan, he confirmed that the file should be a simple list - not grouped by Cantus ID, and not within a "data" element:

> I agree with "an array of JSON objects, each representing one chant in the database, and not in any particular order - you don't want them to be grouped by Cantus ID?" - yes. 
> 
> "data" and "metadata" elements - In the case of these very large datasets, parsing would be easier if the data were structured as a single-level array, without any additional elements. 
> 
> Checking the Date/Last-Modified in the response headers is a great idea - I believe we will not need any other metadata!

**Comment by jacobdgm** [comment]
Current plan for order of operations:
- update our `update_cached_concordances` command, and open PR to merge that change into develop
- test the changes currently on the staging server (#1326)
- deploy the updated API to staging, and show it to Jan for his approval.
