### ISSUE TITLE
"Getting started with new Cantus DB development" wiki is gone

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1335]
The wiki page for [Getting Started with Development](https://github.com/DDMAL/CantusDB/wiki/Getting-Started-with-Development) is now gone. I'm not sure if @jacobdgm you were working on updating this from our last conversation since we realized the documentation wasn't up to date? Maybe there should be a message in the meantime that displays as a work in progress.

**Comment by jacobdgm** [comment]
Oh dear! If it was me that did this, it was certainly not on purpose. Current working hypothesis is that I accidentally clicked "Delete" when I meant to press "Discard changes".

It looks like there's a separate git history for the wiki, so it should be possible to restore this file. Looking into it now. If it was me - sorry!

**Comment by jacobdgm** [comment]
oh! I renamed it "Deploying CantusDB", but forgot to update links to the page elsewhere in the wiki. Let me go through the other pages to fix this.
