### ISSUE TITLE
Save a data dump of OldCantus in Digital Alliance storage

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1366]
In order to preserve the data as is was at EOL of Cantus DB on the UWaterloo servers, we should transfer a copy of the database at that point to a storage location on DRAC.

**Comment by jacobdgm** [comment]
I'm pretty sure I don't have access to the OldCantus server. @jwang44, is this a thing you could do without much trouble?

**Comment by jwang44** [comment]
I'm not sure whether I still have access, but I will check today or tomorrow. 
After I get the sql file, where would you like me to send it?

**Comment by jacobdgm** [comment]
Thank you, @jwang44!

@timothydereuse, does @jwang44 have access to the DDMAL cloud whatever-it-is? Are there instructions for how to access this?

If that doesn't work out, you could probably just upload it to your `~` directory on the staging server, and we can download it from there.

**Comment by dchiller** [comment]
> Thank you, @jwang44!

Yes, thank you!

> does @jwang44 have access to the DDMAL cloud whatever-it-is?

Iff @jwang44 has access to Ich's Arbutus allocation.

> Are there instructions for how to access this?

On the wiki... which I guess I also don't know if @jwang44 has access to? 

@jwang44 I think you should transfer in whatever way is easiest for you (@jacobdgm's suggestion sounds good) and we will make sure it gets where it needs to go.

**Comment by jwang44** [comment]
Sounds good. I'll just `scp` it to the staging server. I'll reply here with the path when it's done.

**Comment by jwang44** [comment]
The database dump has been made. But I cannot connect to the jump box in the lab, therefore cannot upload it to the staging server. Is the jump box still alive? 

The wiki is not working for me either. I used to have access, but for some reason now I have no internet connection once connected to McGill VPN.

**Comment by dchiller** [comment]
@jwang44 

I don't know about the wiki/vpn...

But the location of the jumpbox did change at some point in the past 6-ish months, so if that may be the issue if you haven't logged in in that time. 

Try `HostName jumpbox.simssa.ca` rather than whatever IP you may have in your ssh arguments...

**Comment by jwang44** [comment]
It's official. I have lost access to the jumpbox. 
Since we might still collaborate more in the future, I think it makes sense to set up or fix my access properly. 
Linking this to https://github.com/DDMAL/Operations/issues/95 for record keeping.

**Comment by jwang44** [comment]
OK. Seems my config was out of date and I was using the wrong key. 
I have access now, and the database dump has been uploaded to staging at `/home/ubuntu/cantus_prod_240319.sql.gz`
Let me know if you need anything else.

**Comment by dchiller** [comment]
Thanks @jwang44 !!

**Comment by dchiller** [comment]
I've uploaded this to storage on Ich's arbutus allocation at cantusdb/oldCantus.

@jacobdgm @lucasmarchd01 I think that technically closes this issue. Anywhere else you think it should go?

**Comment by jacobdgm** [comment]
Thank you, @dchiller, @jwang44!

@dchiller, I just created a stub in the CantusDB Wiki at https://github.com/DDMAL/CantusDB/wiki/OldCantus - can you replace the couple of placeholders I left?

Once that's done, we can close this issue I think.

**Comment by jacobdgm** [comment]
I downloaded the .gz file, but I had to `chmod a+rw cantus_prod_240319.sql.gz` (I did this to a copy in my home folder on the staging server) in order to `scp` it onto my own machine. We might want to preemptively set the permissions more permissively to the main file in `ubuntu`'s `~`, to make it easy for future developers who may need to download the file to get it...

**Comment by dchiller** [comment]
I've added the path on that wiki stub, so I'm going to close this issue.

> We might want to preemptively set the permissions more permissively to the main file in `ubuntu`'s `~`, to make it easy for future developers who may need to download the file to get it...

Note that the staging server will be removed shortly, so I think this is only relevant to this transfer.
