### ISSUE TITLE
Change public-facing name of "Mass/Office" to "Service"

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1367]
A chant's "Mass/Office" field should become "Service". (This is a user-facing change...the underlying database field need not necessarily change).

From Debra: 

> Here are the places I see it:
> https://cantusdatabase.org/chant-search/
> https://cantusdatabase.org/offices/
> Terms menu drop-down
> the title and the first column of https://cantusdatabase.org/offices/
> on the Create Chant page: https://cantusdatabase.org/chant-create/588309 (for example)
> the header here: https://cantusdatabase.org/source/588309/inventory/ (for example)

Tagging @annamorphism for any additional areas where this shows up. 

We'll also need to update our own documentation about this field.

**Comment by annamorphism** [comment]
A chant has it both on view and create!
Possibly the actual description of "Unknown Office (à déterminer)" should say "service" as well, though this category is being phased out anyway I think. 
It's a bit weird that the URL says /offices but leads to an explanation of "services"--do we care?

**Comment by jacobdgm** [comment]
To be consistent, I feel we should update the paths as well - `/office/<id>` should become `/service/<id>`, with all the necessary redirects set up to ensure things are backwards compatible.

It may be worth looking into changing things in the code as well, to minimize developer confusion. `OfficeListView` can easily be renamed `ServiceListView`, but I'm not sure how much trouble would arise if we renamed the model itself.
