### ISSUE TITLE
CSV export erroneously uses chants' sigla, rather than the chants' source's siglum

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1379]
This is a stub; at some point I (or someone else) will get around to copying relevant discussion from the email chain into this issue.

I will note that I thought we had addressed every situation where we were using chants' sigla. Evidently we missed one; we should do a thorough search through the code to make sure there are no other places where we're displaying these values we shouldn't be displaying.

**Comment by dchiller** [comment]
Closing as duplicate of #1365
