### ISSUE TITLE
What's going on with the flatpage at `/about`?

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1380]
I wanted to visit a page other than the homepage, so I manually typed `cantusdatabase.org/about` and found this:

![Screen Shot 2024-03-19 at 16 42 23](https://github.com/DDMAL/CantusDB/assets/58090591/e16005f0-0453-4c29-9613-39f1b261554c)

We don't link to this page anywhere, do we? Why does it even exist? Shouldn't it be deleted so we can display a 404 page?

**Comment by annamorphism** [comment]
Weird! I just checked OldCantus, which does have something here but it is very silly:
<img width="670" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/33701be6-ad41-4001-a00a-f66a1630b838">

Did we at some point decide 'this should be replaced with a meaningful page' and then never replace it?

**Comment by jacobdgm** [comment]
Oh! It's because the "About" in the navbar itself was clickable, and would otherwise lead to an empty page. I think I remember Debra saying she added this bit of text in OldCantus several years ago because of this problem.

It's funny - I've been starting to learn a bit of Drupal, and even after a few days of poking around, _I_ know how I could have made "About" unclickable in OldCantus.

I think we'd be fine to delete this page even without checking in with Debra.

**Comment by jacobdgm** [comment]
After searching the codebase, as well as the code on all the other flatpages, I'm confident there are no links to `/about`. I've deleted this flatpage on both Staging and Production. This issue is resolved.
