### ISSUE TITLE
Rewrite Config Block

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1383]
https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/cantusdb/settings.py#L43-L52

The use of single `if` statements on the same variable is not correct, and it does not provide a suitable (and safe) fallback if the variable does not match. Also if no environment variable is set, the `getenv` will try to split on `None` which will make it cranky. 

A couple suggestions:

The "minimal":

```py
if PROJECT_ENVIRONMENT == "STAGING":
    ALLOWED_HOSTS = os.getenv("CANTUSDB_HOSTS_STAGING").split(" ")
    CSRF_TRUSTED_ORIGINS = os.getenv("CANTUSDB_ORIGINS_STAGING").split(" ")
elif PROJECT_ENVIRONMENT == "PRODUCTION":
    ALLOWED_HOSTS = os.getenv("CANTUSDB_HOSTS_PRODUCTION").split(" ")
    CSRF_TRUSTED_ORIGINS = os.getenv("CANTUSDB_ORIGINS_PRODUCTION").split(" ")
else:
    ALLOWED_HOSTS = os.getenv("CANTUSDB_HOSTS_DEVELOPMENT").split(" ")
    CSRF_TRUSTED_ORIGINS = os.getenv("CANTUSDB_ORIGINS_DEVELOPMENT").split(" ")
    DEBUG = True
```

The "rewrite":

```py
allowed_hosts = os.getenv(f"CANTUSDB_HOSTS_{PROJECT_ENVIRONMENT}")
trusted_origins = os.getenv(f"CANTUSDB_ORIGINS_{PROJECT_ENVIRONMENT}")

ALLOWED_HOSTS = allowed_hosts.split(" ") if allowed_hosts else []
CSRF_TRUSTED_ORIGINS = trusted_origins.split(" ") if trusted_origins else []

if PROJECT_ENVIRONMENT not in ("STAGING", "PRODUCTION"):
    DEBUG = True
```

**Comment by dchiller** [comment]
I think this is obviated by the move to ansible. See:

https://github.com/DDMAL/CantusDB/blob/0fad8e9911215e18bd67ff5b5a712a27368c80e0/django/cantusdb_project/cantusdb/settings.py#L40-L46

**Comment by jacobdgm** [comment]
Thanks for pointing this out!

A few months ago, I wrote some code handling the situation where PROJECT_ENVIRONMENT wasn't properly specified - https://github.com/DDMAL/CantusDB/blob/9057bdd71b5e7f73c0cc6e083bdaea4017edbf87/django/cantusdb_project/main_app/context_processors.py#L4-L18

I remember feeling I did a good job writing an informative error message - if someone updates Staging or Production and sees 500 errors, they can look in the logs and immediately see what the problem is. But django won't even get to `context_processors.py` with the current config settings...

**Comment by jacobdgm** [comment]
oops - we both self-assigned at the same time, @dchiller...

I think either of @ahankinson's approaches work. But I'd prefer that a suitable exception be raised if things are configured incorrectly, rather than specifying a "safe" fallback - not properly specifying production/staging/development is a big enough problem that it should not pass silently, I feel.

**Comment by dchiller** [comment]
I posted a snippet from `settings.py` in the `staging-ansible` branch above. I think once we merge that, this will be closed, so I'm not sure any additional work needs to be done. 



> But I'd prefer that a suitable exception be raised if things are configured incorrectly, rather than specifying a "safe" fallback - not properly specifying production/staging/development is a big enough problem that it should not pass silently, I feel.

Yes. With the ansible set-up, you will not be able to deploy if these are not set. I think that might be the place to error if they are not set to a valid value...that way you can't even deploy at all with an incorrect value.

**Comment by jacobdgm** [comment]
Many things were happening all at once! I just saw this:

> I think this is obviated by the move to ansible. See:
> 
> https://github.com/DDMAL/CantusDB/blob/0fad8e9911215e18bd67ff5b5a712a27368c80e0/django/cantusdb_project/cantusdb/settings.py#L40-L46

Do you think this is fine to put off until we get CantusDB ansibleized, @dchiller?

**Comment by dchiller** [comment]
> Do you think this is fine to put off until we get CantusDB ansibleized, @dchiller?

Yes... in fact, I think we can consider it ansibelized (of course, there may be future modifications but `https://staging.new.cantusdatabase.org/` was deployed with the current ansible configuration). What we need to do is just merge the `staging-ansible` changes into our pipeline, I think. Will work on that PR.

**Comment by dchiller** [comment]
Oops...I did just realize one thing: `CSRF_TRUSTED_ORIGINS` is a list, too. So I'll make that change too in the PR.

**Comment by ahankinson** [comment]
That context processor is what triggered the issue. :-) It bypasses the project settings, so even if you hardcode the value in your settings file, it still crashes and you have to rewrite the processor too. 

If you want to raise an exception for a missing value, fine, but I would suggest the place to do is in the settings processing itself, not buried in a context processor.

```py
from django.conf import settings

def determine_project_environment(request): 
     return { 
         "PROJECT_ENVIRONMENT": settings.PROJECT_ENVIRONMENT, 
     } 
```

**Comment by jacobdgm** [comment]
> If you want to raise an exception for a missing value, fine, but I would suggest the place to do is in the settings processing itself, not buried in a context processor.

Yes! The context processor was the place I was working at the time, so that's where I put the exception. But I agree, `settings.py` (or perhaps further upstream, in ansible) is the place where we should check that everything is configured properly.

**Comment by dchiller** [comment]
Looking at the current version of `settings.py` in the `develop` branch, I think this is complete.
