### ISSUE TITLE
create-chant page - very long full text in Suggestions from Previous Chant

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#139]
In the "Suggestions based on the previous chant" sidebar on the create-chant page in Old Cantus, the text of each suggested chant is trimmed once it reaches 100 characters. In New Cantus, the text of each chant is displayed in full, which can lead to buttons being widely separated from each other along the height of the page. These texts should be trimmed, so that users don't need to scroll down to find suggestions.

**Comment by jacobdgm** [comment]
This may be an easy fix. I'll look into it now

**Comment by jwang44** [comment]
Django has a template tag/filter that trims the text once it exceeds a certain threshold. Might be useful in this case. https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#truncatechars. There's also a `truncate words` alternative.

**Comment by jacobdgm** [comment]
fixed by https://github.com/DDMAL/CantusDB/pull/141 - sorry for not including "fixes". someone want to close this?
