### ISSUE TITLE
We should add logos to the Acknowledgements page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1406]
In the same email that prompted #1405, Debra made the following request:

> For the "acknowledgements" page, could one of you figure out what looks good regarding putting the logos in as well as the names of the places?
> https://cantusdatabase.org/about/acknowledgements/
> I have logos for UWaterloo, Catholic University of America, Compute Canada, SIMSSA and Western. The listing of previous funders in the acknowledgements page is in the order that I like, so if there's a way to design it to include logos, that would be great.

(all logos are included in #1405)

https://cantusdatabase.org/about/acknowledgements is a flatpage, and unlike Articles, we don't have a wysiwyg editor set up for flatpages. If I were to implement this now, I would probably upload the necessary images as static files, and then hardcode links to them in the flatpages, manually styling them in the flatpage html. But this feels a bit hacky, and would leave several static files in the repository that we don't reference anywhere in the code. It might make sense to convert this one flatpage into a full-fledged view with its own template? I'd be interested to hear others' thoughts on how best to approach this.

**Comment by lucasmarchd01** [comment]
The logos are now updated on staging! https://staging.cantusdatabase.org/about/acknowledgements/
If everything looks okay (@dchiller), I can add the changes to production as well.
![Screenshot 2024-11-22 at 12 44 34 PM](https://github.com/user-attachments/assets/5cd1132b-1970-4637-ac94-7bf94251c2fc)

**Comment by dchiller** [comment]
They look great to me on staging!
