### ISSUE TITLE
We need to reimplement the Cantus Index Search View

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1410]
This feature was turned off by #1142, and we need to turn it back on again.

https://github.com/DDMAL/CantusDB/commit/7b18c99a911bb0aac88886842af1ef011d1c6359 was the commit responsible for removing this functionality. (https://github.com/DDMAL/CantusDB/commit/49a1978e20d65d06aacf407573dc3f2b1ce7789e could also be useful for writing tests for this view)

**Comment by annamorphism** [comment]
just checking--this is the view responsible for the "Cantus Input Tool", correct?

**Comment by jacobdgm** [comment]
I believe that is correct, yes.

**Comment by jacobdgm** [comment]
Leaving a note here that whenever this gets reimplemented, I would recommend that we not simply recreate what we had pre-bytespider-incident - the previous implementation involved requesting the CI search page, parsing the HTML to grab certain values from the table CI returned, and then displaying a list of results based on the data we'd scraped. To say the least, this was a brittle implementation.

Unfortunately, I'm not aware of any API Cantus Index provides that would allow us to request the information we need. It may be worth emailing Jan to ask how this was implemented in OldCantus, and whether he could create an API that would allow us to request a list of chant texts directly.

**Comment by jacobdgm** [comment]
duplicate of #1391
