### ISSUE TITLE
Change image links on individual chants to Cantus Ultimus where possible

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1418]
After discussion with Debra, if a source is available on Cantus Ultimus, we want the image links on individual chants to be links to those folios on Cantus Ultimus. Note that this doesn't affect the various image views at the source level described in #1079

**Comment by jacobdgm** [comment]
see also #429.

I recall some discussion (though I can't find it with a very brief search) that we shouldn't just replace image links with the CU links, but that we needed to add an extra field so we could preserve the existing image links while displaying CU links in addition to those. (But perhaps this only applied to Source Detail pages?)

**Comment by dchiller** [comment]
> I recall some discussion (though I can't find it with a very brief search) that we shouldn't just replace image links with the CU links, but that we needed to add an extra field so we could preserve the existing image links while displaying CU links in addition to those. (But perhaps this only applied to Source Detail pages?)

Correct. For Source Detail pages, we want multiple views (see #1079). For individual chants, if there is an image on Cantus Ultimus, we just want the Cantus Ultimus version.
