### ISSUE TITLE
On mobile or narrow window view, search box should go to the top

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1419]
When you view Cantus Ultimus in a narrow window (or on a phone browser), the search box is placed below the general page text. It would be more convenient for this to be at the top of the page.

For example, the home page:

<img width="756" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/b9cb1f6d-e829-452c-b64b-cd281f01c3d4">

A source detail page:

<img width="738" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/8b4d158f-edfd-463a-82a7-4292ce0ca647">

**Comment by jacobdgm** [comment]
I like the aspirational "simple fix" tag :P

see also #849

**Comment by jacobdgm** [comment]
The challenge is that the search box is part of the sidebar, and using bootstrap, there's not a simple way to 
split the sidebar so some of its content goes above the main panel and some of it goes below.
