### ISSUE TITLE
Handle `LatinError` exception in views that use volpiano display utilities

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1423]
https://github.com/DDMAL/volpiano-display-utilities/pull/52 introduces the raising of `LatinError` when non-latin characters are passed in a word to be syllabified.

Views in CantusDB that use volpiano display utilities should handle this error. In particular, if entered text results in this error, users should be prompted to fix their text.

**Comment by annamorphism** [comment]
out of curiosity, what does this do for e.g. chants with Greek letters in them? Or that end in a hyphen, "this chant is a fragme-" ?

**Comment by dchiller** [comment]
> out of curiosity, what does this do for e.g. chants with Greek letters in them?

This would return a `LatinError` for a chant with greek letters in it. When non-Latin characters become valid on Cantus DB, we will have to update with new "syllabification" logics for any supported language + character set. 

> Or that end in a hyphen, "this chant is a fragme-" ?

This would be syllabified as "this chant is a frag-me-". In other words, this PR doesn't change anything about how hyphens are handled, as long as they are valid CantusDB strings.

**Comment by annamorphism** [comment]
I'm getting repeated emails about bracketing mistakes resulting in 500 errors (admittedly, from the same user)--is this fix due to be on production soon?

**Comment by lucasmarchd01** [comment]
@dchiller has this been resolved by #1487?

**Comment by dchiller** [comment]
Let me check on this... I can't remember.
