### ISSUE TITLE
Chant Create: Suggested Chants feature needs to be optimized

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1424]
When putting together #1422, I had to set the number of suggested chants at 3 (instead of 5, as it had been previously). Even so, adding this feature has increased the load time on the Chant Create page by an order of magnitude.

The slowdown is caused by the fact that we're sending a bunch of requests to CI, and waiting for each response to come back before sending the next request.

There are a few ways I can think of to optimize this:
- parallelize the request.get calls to CI's `/json-cid` endpoint, using a library like `threading`
- implement a cache system to save CI's responses and only send a new request if our cached response is out of date by a certain amount of time

**Comment by annamorphism** [comment]
my gut feeling leans toward caching--they're only suggested chants anyway, so they need to be mostly-right but not up-to-the-minute accurate. And if the helpful suggestion takes too long it ceases to be a helpful timesaver...

**Comment by dchiller** [comment]
Jan has made a fix to the API that will greatly simplify the number of calls needed to obtain these suggestions (in short, we'll just need to make one API call to cantus index, rather than 4). I'll implement a fix.
