### ISSUE TITLE
Django debug toolbar is not working

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1457]
I just noticed that while working in my development environment (devcontainer setup), the Django debug toolbar doesn't show. Perhaps this was as a result of #1454?

**Comment by lucasmarchd01** [comment]
I've got it to work by running `request.META["REMOTE_ADDR"]` to one of our views, which has exposed the port 172.24.0.4 as the IP host in the django container. So if I add this IP to `INTERNAL_IPS` it fixes the issue, but this solution is hardcoding the IP address which isn't really useful. Is there a way of making this dynamic in settings.py?

**Comment by lucasmarchd01** [comment]
This works too, but not sure if it will be the same for everyone:
```
if DEBUG:
    import socket
    ip = socket.gethostbyname(socket.gethostname())
    INTERNAL_IPS += [ip[:-1] + "4"]
    INSTALLED_APPS.append("debug_toolbar")
    # debug toolbar must be inserted as early in the middleware as possible
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
```

**Comment by dchiller** [comment]
I was frustrated by this too the other day!

**Comment by dchiller** [comment]
Was just about to post the same thing: 

```python
    import socket

    INTERNAL_IPS = [
        ".".join(socket.gethostbyname("host.docker.internal").split(".")[:-1]) + ".1"
    ]

```

**Comment by dchiller** [comment]
What's odd to me is that this is similar to what the `debug_toolbar` already has in its callback: 

https://github.com/jazzband/django-debug-toolbar/blob/7271cac9eacb7870200d6bc965c84eb91ba36714/debug_toolbar/middleware.py#L19-L38

**Comment by lucasmarchd01** [comment]
Interesting. I remember when setting this up seeing this warning in their documentation:
https://github.com/jazzband/django-debug-toolbar/issues/1854

But now it's gone. I think their solution assumed that the docker IP would always end with 1, but it ends in 4 for our (or my) case which is why it didn't work.

**Comment by lucasmarchd01** [comment]
Now, while using the debug toolbar to try and see how many SQL queries are being made, I get the following error:
```
AttributeError at /
'Connection' object has no attribute 'status'
```
I think this is probably linked to https://github.com/jazzband/django-debug-toolbar/issues/1754. We have `django_debug_toolbar = "3.8.1"` in our dev dependencies and `psycopg  3.1.18` which are incompatible.
