### ISSUE TITLE
We should have a fallback when DRAC server is down

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1465]
@fujinaga has mentioned that we should have a fallback when the DRAC servers go down. We should ideally re-route the DNS to a different server (github pages?) so that a message can be displayed to the user elegantly. Is this possible? 

DRAC will have outages on **May 22** (6:30 AM - 10:30 AM PT) and **June 5** (6:30 AM - 10:30 AM PT), so we should try and find a solution before one of these dates to test it.

**Comment by ahankinson** [comment]
You will need a DNS provider that provides automatic failover, and that will detect when your site goes down to route traffic to an alternate. There are some real problems with this, though; see: https://serverfault.com/questions/60553/why-is-dns-failover-not-recommended

You can do it manually, but given the normal propagation time for DNS is ~1hr, your site may be back up again before the records propagate. So this is only really useful for known, extended outages.

A second option is to host your site on a load balancer in a public cloud service, like Amazon. This LB can detect when your normal backend is "down" and route traffic accordingly. However, there are some significant drawbacks to this too:

 - Additional complexity in your frontend setup
 - The need to subscribe (and pay) for the server outside of DRAC
 - There is the possibility that the LB may interpret a long request time as an 'outage' and route traffic to your outage page. This means that some users may be incorrectly served the outage page, and you would not know unless they complained.

**Comment by dchiller** [comment]
Ok, I think my hot take is that we don't do this. 

There are 3 scenarios I can think of where a CantusDB server would be "down".

1. Planned DRAC outage
So, this is a la what happened yesterday and what is scheduled to happen on June 5th. We knew about these in advance, we put a notice about it up on the site, and they seem infrequent enough that I just don't see the value for these cases. Websites sometimes need maintenance, and CantusDB is important, but I think being down for an hour or two with plenty of advance warning is fine.

2. Updating the server
In the bigger scheme of things, this is a miniscule amount of time (5-ish minutes every few weeks). And I think there is lower-hanging fruit here: the thing that takes time here is the Docker build and start-up. Imagine if all we had to do was restart gunicorn and maybe the nginx server?

3. Unplanned DRAC outage
This is where I can see the biggest argument for going to any lengths for this. On the other hand... if DRAC is unexpectedly down for a few hours (there's an issue, but it is something that they can solve relatively quickly), then we are roughly in the same position as point 1 (we didn't notify users, but how often does this actually happen and for how long). And if it's for longer: we have data back-ups, we have ansible, and we have a good GH practices, all of which are designed to make it possible for us to spin up a new CantusDB server on AWS or something quite quickly...

I realize that I am in some ways shrugging off CantusDB being down ("it's just a chant website, does it really matter if it's down for a few hours") ... I don't take it lightly that we should do what we can to minimize downtime, but I think we can continue to take steps to do this without moving to AWS or something to set up a load balancer.

**Comment by fujinaga** [comment]
You’ve convinced me. You may close this issue.

On May 23, 2024, at 22:18, Dylan Hillerbrand ***@***.***> wrote:

﻿

Ok, I think my hot take is that we don't do this.

There are 3 scenarios I can think of where a CantusDB server would be "down".

  1.  Planned DRAC outage
So, this is a la what happened yesterday and what is scheduled to happen on June 5th. We knew about these in advance, we put a notice about it up on the site, and they seem infrequent enough that I just don't see the value for these cases. Websites sometimes need maintenance, and CantusDB is important, but I think being down for an hour or two with plenty of advance warning is fine.

  2.  Updating the server
In the bigger scheme of things, this is a miniscule amount of time (5-ish minutes every few weeks). And I think there is lower-hanging fruit here: the thing that takes time here is the Docker build and start-up. Imagine if all we had to do was restart gunicorn and maybe the nginx server?

  3.  Unplanned DRAC outage
This is where I can see the biggest argument for going to any lengths for this. On the other hand... if DRAC is unexpectedly down for a few hours (there's an issue, but it is something that they can solve relatively quickly), then we are roughly in the same position as point 1 (we didn't notify users, but how often does this actually happen and for how long). And if it's for longer: we have data back-ups, we have ansible, and we have a good GH practices, all of which are designed to make it possible for us to spin up a new CantusDB server on AWS or something quite quickly...

I realize that I am in some ways shrugging off CantusDB being down ("it's just a chant website, does it really matter if it's down for a few hours") ... I don't take it lightly that we should do what we can to minimize downtime, but I think we can continue to take steps to do this without moving to AWS or something to set up a load balancer.
