### ISSUE TITLE
Links to external images?

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1467]
Looking at this source:

https://cantusdatabase.org/source/123687

The "link to external images" points to CU. When clicking that it says that MSS has been moved, but this MS does not appear in the list of MSS on CU. 

It does appear here, though: https://digital.bodleian.ox.ac.uk/objects/8e4ae570-9fab-40b4-a83e-fe6bf8752daa/

**Comment by dchiller** [comment]
Turns out this was a data entry issue .... we added the link to CU last fall, but subsequently removed the source from CU because it had no melodies. I've updated the image_link field in Cantus DB.
