### ISSUE TITLE
"My sources" page and sidebar should be ordered by date updated

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1468]
How are sources supposed to show up in "My sources"? I am an editor for some sources but they don't seem to be in "my sources", so what determines this?

**Comment by dchiller** [comment]
It looks like the logic is that it includes sources that were either (a) created by you or (b) for which you are listed as a "current editor".

Could you give me an example of such a source, and then I can look at which "role" you have with the source that isn't one of these two?

**Comment by annamorphism** [comment]
wait, I found the sources I thought I was lacking after all--weirdly, buried in different places in my (very long) list of sources, even though I thought I was added to both as an editor at the same time pretty recently (so I was expecting them together and near the surface.)  So the logic is sound, it's actually a question of the order things are presented to the user (probably the most recently modified should be at the top?)

**Comment by lucasmarchd01** [comment]
There is also the "Sources created by user" sidebar. To me it makes more sense to keep it ordered by date created instead of date updated, but we can easily change that as well.

**Comment by dchiller** [comment]
> There is also the "Sources created by user" sidebar. To me it makes more sense to keep it ordered by date created instead of date updated, but we can easily change that as well.

Ok, in testing on staging it looks like #1472 changed the ordering of the "Sources created by user" sidebar, but not the main source list on the "My Source" page.

**Comment by lucasmarchd01** [comment]
See https://github.com/DDMAL/CantusDB/pull/1500.

The sidebar on the My Sources page should be changed back to ordering by date created and the list in the table should be ordered by date updated
