### ISSUE TITLE
Duplicate results show up in source search

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1480]
From Debra:

> https://cantusdatabase.org/sources/?segment=4063&general=&indexing=klassen&provenance=&century=&fullSource=
> 
> I searched for the name of an indexer and I have many duplicates being returned (of the same thing). Is this finding every instance of that name in a file? Could it instead find the name but only return the source once?

**Comment by annamorphism** [comment]
weird little bug! why is US-Cai 1911.142b here nine times, when the indexer is only listed on it three times...?

**Comment by dchiller** [comment]
Good question...I'm not sure.
