### ISSUE TITLE
Contributor changes to a chant after proofreading overwrite proofreading fields

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1491]
To replicate: 

- Log in as a proofreader of a source and edit a chant in that source by marking any of the "proofread" checkboxes, or adding someone to the `proofread_by` field, or by specifying a chant range.
- Log in as a contributor (ie. someone without proofread access to that source), and then make any edit to the chant.
- Log back in as the proofreader and see that all of your changes to those fields (proofread checkboxes, the `proofread_by` field, and the chant range field) have been overwritten. 

In emails with Debra, it sounds like the following would be preferable:
- contributor changes should never overwrite the `proofread_by` or `chant_range` fields
- the checkboxes are only "unchecked" by a contributor change if the contributor has actually changed something in one of the related fields ("volpiano proofread" gets unchecked only if the "volpiano" has changed, and so on)

**Comment by annamorphism** [comment]
right--I think for some time we've been circling around the balance of having the proofreading status be accurate, without constantly having to re-proofread things. This seems like a good solution.

**Comment by dchiller** [comment]
Indeed ... and this current bug makes it not accurate and makes people constantly re-proof thing, so we're currently living in the worst of all possible worlds.
