### ISSUE TITLE
Break up admin.py

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1510]
Currently all the admin section config is in one file, admin.py. 

It would be handy to break this out into individual files for each model, so that the config for that model is stored in one place. 

I would be happy to open a PR for this, if @dchiller and @lucasmarchd01 are OK with the change.

**Comment by dchiller** [comment]
Fine with me

**Comment by dchiller** [comment]
Closed with #1513 (there was previously a different issue linked to that PR)
