### ISSUE TITLE
Allow superusers access to all edit forms

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1527]
When trying to compare my local changes to the edit forms to the production version, I got a '403 Permission Denied" error when trying to access the edit form, despite the fact that I am set as a superuser in the admin, and can actually edit everything anyway. 

It would be useful if superusers could also access all the edit forms by default. 

I think this could be done pretty easily -- add: 

```
if user.is_superuser:
    return True
```

To these functions:

https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/main_app/permissions.py

Does that sound reasonable?

**Comment by dchiller** [comment]
What edit form was this? I think this makes sense, but as far as I know, "project managers" should be able to do this... you, for example, have the exact same permissions as Debra, Anna, and others currently, so I'm worried if there are things you are getting a 403 on?

**Comment by ahankinson** [comment]
I assigned myself that as a workaround. :-D

**Comment by dchiller** [comment]
Phew! This seems fine to me then
