### ISSUE TITLE
Chants without Cantus ID in Feast display are probably not correct

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1540]
Currently, the chants in the feast list will display chants that do not have a `cantus_id` value in the left column; e.g., 

https://cantusdatabase.org/feast/1581

The third entry, "Egredietur*" shows 107 chants. (On my machine it shows 96, but I think I'm working from a slightly older dataset.)

However, if you look at the code that generates this list:

https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/main_app/views/feast.py#L49-L57

You see that it's iterating over the `cantus_id` value and generating a count from that value. This means that when `cantus_id` is `None`, the `count` represents all the chants where `cantus_id` is `None`. 

If the following SQL query is run, this will give you all the chants attached to this feast where the Cantus ID is not specified:

```sql
SELECT incipit
FROM main_app_chant AS cs
WHERE cs.feast_id = 1581
  AND cs.cantus_id IS NULL;
```

This gives the exact same number.

So, I guess my question is:

 - Should chants with no Cantus ID be displayed in this list?
 - If so, how do we count how many? (We can't do it by Cantus ID...)
 
Related to this, I'm working on an optimization for the feast table, because this view generates several hundred SQL queries.

**Comment by annamorphism** [comment]
I think this may be the mysterious issue I made a note of in #1136 ! Glad to finally understand it.

My initial feeling is that these can probably be left out of the list--the blank really shouldn't be there anyway, since we now have an ID for cases like this one where the ID can't be determined. (That said, tracking down all these cases and assigning them to it is also a challenge (how to find chants with no ID?), not to mention a good bit of work...)

But even in some imagined future where they all were assigned to 900000 (=ID unknown), it would probably be less useful to know that there are 107 unidentified chants than that there are 73 versicles "Egredietur dominus de loco" (008043), 61 "Egredietur virga de radice" (008044), and one otherwise unidentified chant beginning "Egredietur". So I'll think on it.

**Comment by ahankinson** [comment]
Yep, that's the same issue! Even though this is a duplicate, we should probably leave both open for now? 

Leaving it out of the list is the easiest. There's also a lot of "garbage" chants in the list of chants attached to a feast but with a NULL value for the cantus ID, so I'm not sure we simply want to display them at the end. 

Some gems attached to Feast 1581 (Dom. 1 Adventus) include:

```
-- --*
Mise*?
---- ------ laud--
-- --
--- ---inus (?)
LACUNA
```

As well as 17 different Alleluias...

**Comment by ahankinson** [comment]
Here's the full list. I suspect that the reason the "Egredietur*" shows up is that it seems to be the chant on this list with the lowest ID number. 

| id | incipit | cantus\_id |
| :--- | :--- | :--- |
| 548590 | -- -- | null |
| 185149 | -- --\* | null |
| 464480 | --- ---inus \(?\) | null |
| 464482 | ---- ------ laud-- | null |
| 464483 | ------- | null |
| 566493 | Ad te domine levavi animam | null |
| 710721 | Ad te domine levavi animam | null |
| 566488 | Ad te levavi animam meam | null |
| 1002849 | Ad te levavi animam meam | null |
| 1003155 | Ad te levavi animam meam | null |
| 1003475 | Alleluia | null |
| 710716 | Alleluia | null |
| 710718 | Alleluia | null |
| 1003551 | Alleluia Excita domine potentiam tuam | null |
| 596261 | Alleluia\* | null |
| 487701 | Alleluia\* | null |
| 451123 | Alleluia\* | null |
| 270105 | Alleluia\* | null |
| 596259 | Alleluia\* | null |
| 270092 | Alleluia\* | null |
| 596260 | Alleluia\* | null |
| 596258 | Alleluia\* | null |
| 270082 | Alleluia\* | null |
| 270098 | Alleluia\* | null |
| 270109 | Alleluia\* | null |
| 596255 | Alleluia\* | null |
| 596246 | Alleluia\* | null |
| 270107 | Alleluia\* | null |
| 710711 | Animam meam deus meus in | null |
| 1003552 | Benedixisti domine terram tuam avertisti | null |
| 1003479 | Benedixisti domine terras tuas | null |
| 566497 | Benedixisti domine\* | null |
| 710725 | Benedixisti\* | null |
| 444266 | Cantate domino\* | null |
| 1003576 | Confortamini et jam nolite | null |
| 1003474 | Congregate illi sanctos eius qui | null |
| 464537 | Cum appropinquasset Ihesus Iherusolimam -- | null |
| 1003555 | Cæli enarrant gloriam dei et | null |
| 688648 | De profundis\* | null |
| 1003476 | Deus tu conversus vivificabis nos | null |
| 444237 | Dicite filiae\* | null |
| 1003553 | Dicite pusillanimes confortamini et nolite | null |
| 566494 | Dirige me in veritate tua | null |
| 710713 | Dirige me inveri\* | null |
| 696507 | Dixit dominus\* | null |
| 566496 | Dominus dabit benignitatem et terra | null |
| 710724 | Dominus dabit benignitatem et terra | null |
| 464545 | Ecce dominus veniet | null |
| 710720 | Ecce iam christus quem sancti | null |
| 195027 | Ecce nomen\* | null |
| 1003577 | Ecce virgo concipiet et pariet | null |
| 641875 | Egredietur dominus\* | null |
| 178903 | Egredietur\* | null |
| 195030 | Egredietur\* | null |
| 641876 | Emitte agnum domine\* | null |
| 641874 | Ex Sion species\* | null |
| 710717 | Excita domine potentiam tuam et | null |
| 1003478 | Gaudete in domino semper iterum | null |
| 1003283 | Gloria | null |
| 1003284 | Gloria | null |
| 1003556 | Gloria patri \[...\] | null |
| 574591 | Gloria patri altissimo\* | null |
| 691097 | Gloria patri\* | null |
| 559007 | Hora est iam nos de | null |
| 1003477 | Jerusalem surge | null |
| 1002795 | LACUNA | null |
| 1003575 | Laudem domini loquetur os meum | null |
| 710719 | Levate capita vestra quia appropinquat | null |
| 571523 | Mise\*? | null |
| 560287 | Miserere --\* | null |
| 386722 | Miserere\* | null |
| 464511 | Ne timeas Maria invenisti --ciam | null |
| 1003154 | Ostende nobis domine misericordiam tuam | null |
| 566492 | Ostende nobis domine misericordiam tuam  | null |
| 1003574 | Prope est dominus omnibus invocantibus | null |
| 1003578 | Prope esto domine et omnes | null |
| 1003526 | Qui regis Israel intende qui | null |
| 1003480 | Qui sedes domine super cherubim | null |
| 1003573 | Quis ascendet in montem domini | null |
| 464510 | Quomodo in me fiet hoc | null |
| 481880 | Quomodo in me fiet hoc | null |
| 566495 | Respice in me et miserere | null |
| 710723 | Respice in me et miserere | null |
| 559772 | Rex sine fine manens, miseris | null |
| 1003554 | Rorate caeli desuper et nubes | null |
| 641873 | Rorate caeli desuper\* | null |
| 1003557 | Tollite portas principes vestras et | null |
| 710714 | Universi qui te expectant non | null |
| 566490 | Universi qui te expectant non | null |
| 1003025 | Universi qui te exspectant non | null |
| 1003153 | Vias tuas domine notas fac | null |
| 710715 | Vias tuas domine notas fac | null |
| 710712 | Vias tuas domine notas fac | null |
| 566491 | Vias tuas domine notas fac  | null |
| 566489 | Vias tuas\* | null |
| 710722 | dirige me in veritate tua | null |
