### ISSUE TITLE
some(?) hymn verse IDs causing chant-create issues (again?)

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1553]
This may be another case of #1515, but I wanted to make note of it...
 The ID 008367:01 seems to cause havoc for creating any subsequent chants. Other verses of the same hymn--or verses of other hymns--don't seem to be a problem, just this one...

**Comment by lucasmarchd01** [comment]
I can't seem to replicate the issue. What were the steps involved to produce the error?

I tried creating a new source and adding a chant with CID 008367:01, then when I add any subsequent chants it works as expected.

**Comment by annamorphism** [comment]
Strange...when I add a chant to my test source, using the ID 008367:01 and a dummy text (blablabla) I get 
![image](https://github.com/user-attachments/assets/b1b2d798-d890-4bd3-814e-7fc0ee23c280)

It makes it into the inventory though:
![image](https://github.com/user-attachments/assets/dcfb8768-29e5-4cd9-bc78-8135f5fab996)

But adding a new chant: 500 error
![image](https://github.com/user-attachments/assets/18b02e72-f7db-4a29-91db-58f3a4b6eeaf)

Deleting this chant and adding a new one with some other ID in the same way works as expected.

**Comment by annamorphism** [comment]
tried it on a different test source, just in case it was something about the source. Same thing: 
![image](https://github.com/user-attachments/assets/60e5de76-a133-4087-b35f-f08ca186bf15)

**Comment by annamorphism** [comment]
Made a brand-new source, too, and the issue still happens...?? I'm consistently able to replicate the problem...
![image](https://github.com/user-attachments/assets/efe85af8-e237-457e-928e-2193501ba998)

**Comment by lucasmarchd01** [comment]
Interesting...

Okay, I was able to replicate it now on the production site. On staging and develop, there doesn't seem to be any issues. Maybe something in the pipeline has already fixed this? I'll go and see if I can try to pinpoint which commit might be responsible for it.

We're updating production soon, so we can see if it's been resolved then.

**Comment by lucasmarchd01** [comment]
I believe https://github.com/DDMAL/CantusDB/pull/1517 should fix this issue, but we should test to make sure once it makes it to production!

**Comment by dchiller** [comment]
This is now working on production with the 15July2024 update.
