### ISSUE TITLE
Combine feasts: 2456 -> 4474 and 2094 -> 4475

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1560]
We need to: 

- ensure that all the feast data for feasts 2456 and 2094 have been transferred to 4474 and 4475 respectively
- "re-feast" all chants and sequences that have the old feast ID's so that they have the new feast ID's
- delete the old feasts

**Comment by lucasmarchd01** [comment]
I think we can set up a management command that can do this. There's one thing I've noticed:

The feast date is different for feasts 2456 and 4474, which are August 8 and August 4, respectively. Should we use the date from the old feast (2456) or the new one (4474) when merging the data?

**Comment by annamorphism** [comment]
My understanding is that the merged feast (4474) should have the 4 August date, corresponding to the new code 14080430.

**Comment by dchiller** [comment]
> I think we can set up a management command that can do this.

Great point -- I could see this as being potentially useful functionality going forward.

**Comment by lucasmarchd01** [comment]
The command has now been run successfully on staging. Once this reaches production we can run the command again and close the issue.

**Comment by dchiller** [comment]
@lucasmarchd01 Thanks! I assigned you mostly so that we could see from the issue list that this was already under control -- but thanks for testing this too!

**Comment by dchiller** [comment]
Run on production. 21 Oct 2024
