### ISSUE TITLE
Change `office` -> `service` on django admin page

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1581]

**Comment by lucasmarchd01** [comment]
Might also be a good time to consider fixing #1401 and #1402

**Comment by lucasmarchd01** [comment]
Should the "Mass / Office" on the Genre List page also be switched to "Mass / Service"?

**Comment by dchiller** [comment]
> Should the "Mass / Office" on the Genre List page also be switched to "Mass / Service"?

Like this page? https://cantusdatabase.org/genres/

Good q...perhaps worth an email to Debra or maybe @annamorphism knows...
