### ISSUE TITLE
Create a DB backup for RISM integration

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1587]
For RISM integration, we want a DB backup (updated weekly) that drops some unnecessary tables from CantusDB. 

@ahankinson has mocked up this command to use.

`docker compose exec -T postgres pg_dump -U cantusdb -d cantusdb -T auth* -T users* -T reversion* | gzip > /home/cantusdb/cantusdb_export.gz`

We'll want a cron job and then an endpoint to access.

**Comment by ahankinson** [comment]
> We'll want a cron job and then an endpoint to access.

This can be stored somewhere that is accessible over SSH. My plan is to create a dedicated service user that can SSH in and download the dump.
