### ISSUE TITLE
Clarify terminology: "Mass / Office" vs. "Mass / Service" on genre list page

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1588]
A question for @annamorphism,

After making the final changes in #1582, there remains one more instance of "office" on CantusDB on the genre list page.
https://cantusdatabase.org/genres/

On the genre list page, should the last column and field values be "Mass / Office" or "Mass / Service"?

**Comment by annamorphism** [comment]
This should stay Mass/Office, I think.
