### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#160]
NewCantus needs to have users with different permissions. Copied from an email from Debra:

> Here, briefly is what I'm thinking right now:
> --Contributor
> --Co-contributor
> --Editor/Proofreader (just one level for this, with access only when provided by Project Manager or Admin)
> --Debra or "Project Manager" (no access to anything dangerous, i.e., no programming code sections)
> --System Administrator (full control, but make sure they don't change any content)

For the editor/proofreader level, my interpretation is that the Project Manager would assign specific sources to that user, for which they'd have access to either edit or proofread the source. If the user has editor access to a source, they'd be presented with all of the Fulltext, Volpiano, metadata fields but no "proofread" checkboxes when editing a chant, while if a user has proofreader access to a source, they would have all of those fields plus the checkboxes. 

Thus, for each editor/proofreader, there would be some sources for which they cannot edit anything, some sources for which they have limited editor permissions, and some sources for which they have extended proofreader permissions.

**Comment by jwang44** [comment]
The user group specification is updated here in the spreadsheet. https://docs.google.com/spreadsheets/d/1v-9IwsR6JBWFDaHaJlEzfDvZzK7W3fl13kLldOdmu0I/edit#gid=1535637058

**Comment by jacobdgm** [comment]
this has been implemented! closing.
