### ISSUE TITLE
TypeError on Source Create page

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1604]
Try and create a source with all of the fields empty. We get the following error:

`TypeError: sequence item 0: expected str instance, NoneType found`

This is currently on the develop and staging branches.

**Comment by lucasmarchd01** [comment]
It's because of the `shelfmark`. Should we make this a required field?

**Comment by annamorphism** [comment]
did we come up with a placeholder institution+shelfmark for sources that don't have a pre-existing RISM siglum or library shelfmark? Or does it not matter as long as the field is non-null?

**Comment by ahankinson** [comment]
The shelfmark no longer contains the RISM siglum. This is assigned to the institution and is pulled in from there.

Sources without a shelfmark typically get something like s.n. or s.s.
