### ISSUE TITLE
 Add a field to identify if a Source is a printed book or a manuscript 

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1628]
This should be a checkmark or dropdown for printed.

**Comment by ahankinson** [comment]
I would make it an IntegerField with two choices, 1 = Manuscript, 2 = Printed. 

(Don't do 0 because that's Falsey in Python, and liable to cause all sorts of problems.)

Here's how we define a similar field in DIAMM:

https://github.com/diamm/diamm/blob/main/diamm/models/data/source.py#L20-L37

And the actual field:

https://github.com/diamm/diamm/blob/main/diamm/models/data/source.py#L56

You can also have a `default=` argument, so you might do something like:

```
MANUSCRIPT = 1
PRINTED = 2

SOURCE_TYPE_CHOICES = (
  (MANUSCRIPT, "Manuscript"),
  (PRINTED, "Printed"),
)

source_type = models.IntegerField(default=MANUSCRIPT, choices=SOURCE_TYPE_CHOICES)
```

**Comment by dchiller** [comment]
@annamorphism What would you call this in the user display? The best I've come up with so far is "production method"

**Comment by fujinaga** [comment]
"Source type"? "Document type" ?

**Comment by annamorphism** [comment]
> @annamorphism What would you call this in the user display? The best I've come up with so far is "production method"

That's not a bad name, actually...

**Comment by annamorphism** [comment]
or maybe it could just be Manuscript/Print in the same way there is Full Source/Fragmented?

**Comment by dchiller** [comment]
> maybe it could just be Manuscript/Print

True...one implication of the way we've set up the field is that other options could be added in the future (if we wanted) ... but for now there are only the two so this is probably the clearest way to go.

**Comment by annamorphism** [comment]
> > maybe it could just be Manuscript/Print
> 
> True...one implication of the way we've set up the field is that other options could be added in the future (if we wanted) ... but for now there are only the two so this is probably the clearest way to go.

Ah--yes it could be interesting to be able to include things like stenciled sources or mixed-production sources...but mayeb that's a problem for the future.

**Comment by dchiller** [comment]
> Ah--yes it could be interesting to be able to include things like stenciled sources or mixed-production sources...but mayeb that's a problem for the future.

Yeah, I was picturing stenciling too as a future possibility. For now, I'll display it as `Manuscript/Printed` but we can go back in future and add more choices to the field *and* change the display name if/when that becomes useful.

**Comment by lucasmarchd01** [comment]
I think this was the last change we were planning to make before updating production. Is the change ready to go? I saw you were assigned to it @dchiller but I can work on it if you'd like.
