### ISSUE TITLE
trailing slash breaks URL

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1633]
On Cantus Index the links to concordances (both the chants and the sources) have a trailing slash:  cantusdatabase.org/source/somenumber/
<img width="605" alt="image" src="https://github.com/user-attachments/assets/149ae222-6d82-443c-9c13-a0c2b6aea46b">

This means clicking on them gives a 404, which is quite confusing!
Either CI needs to remove the slash, or the URLs with a slash in them should redirect to the slashless page.

**Comment by dchiller** [comment]
I'm having some trouble finding where this is true. Perhaps it has been fixed on their end? Or is inconsistently true depending on the source/concordance?

**Comment by annamorphism** [comment]
I was having some trouble finding it again yesterday as well. Maybe it got fixed (good!) or maybe it happens only sometimes (bad!). I'll poke around and then close this if I can't find it again.

**Comment by annamorphism** [comment]
Seems to have been fixed--I had a tab open where the links had the trailing slashes and didn't work, and when I refreshed the page, they now appear slashless. So this seems to be solved.
