### ISSUE TITLE
Fixes to source completeness and populating source completeness command

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1665]
After reviewing staging:

- sources where previous `full_source` field was `None` should be mapped to a full source (1) in the new `source_completeness` field
- browse sources filter should filter by this new field
- Make changes to user-facing text in the `source_completeness` and `complete_inventory` fields:
    - Source completeness options: "complete source"/"fragment"/"reconstruction"
    - Complete inventory options: "full inventory"/"partial inventory"

**Comment by ahankinson** [comment]
Does `collectstatic` need to be run somewhere on staging? I'm getting problems with the CSS...

**Comment by dchiller** [comment]
Hmm...it was, and I'm not having problems on any pages I'm visiting. What page?

**Comment by ahankinson** [comment]
The whole `/admin` site... :-D

Try shift-reloading the staging site `/admin` page and see if clearing your browser cache breaks it? I get a 400 Bad Request for `https://staging.cantusdatabase.org/static/admin/js/nav_sidebar.js`

**Comment by dchiller** [comment]
Weird. Shift-reloaded, disabled cache:

![image](https://github.com/user-attachments/assets/834b4e21-002a-451b-b6be-6a12e9dbeef4)

**Comment by dchiller** [comment]
Lemme try again... 

Shift-reloaded and disabled cache:

![image](https://github.com/user-attachments/assets/7e181df2-0f6e-47ce-9733-de55a601ca16)

I'll run `collectstatic` again just in case.

**Comment by dchiller** [comment]
Ok, just ran again... all files unmodified, but try again I guess?

Update: also works for me on multiple browsers...

**Comment by dchiller** [comment]
Interesting. I see all the 400's in the logs in the past 30m from the same IP which I presume is you.

**Comment by ahankinson** [comment]
Is there a VPN setting? Or some IP address restriction?

**Comment by dchiller** [comment]
Neither. There's the http authentication, which shouldn't return 400 and shouldn't affect only admin static files, but maybe try clearing the authentication cache for the site and try again?

**Comment by ahankinson** [comment]
Ok, it seems to work now? Not sure what happened.
