### ISSUE TITLE
500 error on Staging

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1672]
After I log in, I'm getting a 404. Trying to click on any other page results in a 500 error.

**Comment by dchiller** [comment]
Check again? I just was doing a database update/migration for some final tests so this may have been a timing thing.

**Comment by lucasmarchd01** [comment]
Okay, it works now. Sorry about that, I didn't know!

**Comment by dchiller** [comment]
np....should have told you!
