### ISSUE TITLE
Don't use "first name" and "family name" for users

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#168]
Further to Ich's comment on [pull request 111](https://github.com/DDMAL/CantusDB/pull/111), it's better to simply use a "name" field for users rather than having "first name" / "given name", "last name" / "family name" fields and then having to guess which order they go in.

**Comment by fujinaga** [comment]
Yes, I agree; having just a "name" field is best. There would be an extra work of providing a good searching capability when listing all users in certain orders.

**Comment by jacobdgm** [comment]
this is partially implemented: currently, we have a `full_name` field defined for the User model; users have a `first_name` and `last_name` that are inherited from the django's built-in AbstractUser, so there are First Name, Last Name and Full Name fields all present in the admin interface.

A direction we could go from here: I could write a script to populate all users' `full_name` fields, which Junhao can run once all the data has been pulled from OldCantus. once it's run, we can look into overwriting/deleting the first_ and last_name fields so they don't show up in the admin interface, and so no data is lost. Is there something else/different we should do with this?

**Comment by lucasmarchd01** [comment]
On our site, users are now represented by their full name. The first name and last name fields are maintained in the admin area to avoid loss of data from OldCantus.
