### ISSUE TITLE
chants out of order in sidebar

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1682]
I'm looking at this chant https://cantusdatabase.org/chant/698887 (source not yet proofread, so maybe there is something weird underlying it). The previous/following chants show up in the sidebar in kind of a weird order...actually now I'm looking at it it seems to be alphabetical by feast? Anyway we want them ordered by sequence...

![image](https://github.com/user-attachments/assets/0cb101b5-8f63-40bb-a728-3bc07cef61f0)

**Comment by dchiller** [comment]
@annamorphism Is this more what you are expecting (ie. still broken out by feast but with the feasts in order based on chant sequence?)

![image](https://github.com/user-attachments/assets/8701da3b-4b91-4987-a166-315d8c41f316)

**Comment by annamorphism** [comment]
yes! much better.
