### ISSUE TITLE
Chant edit page (when no chant pk is given) has weird feast filters

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1707]
This is what showed up when I selected `037r - Nativitas Domini`...

![image](https://github.com/user-attachments/assets/a502d5b8-59a9-4697-b80d-c8208322e899)

I think since we already have the folio filter, either the feast filter should not be folio specific (i.e. it should return all chants associated with a feast, separated by folio, but the option in the dropdown should not reference a specific folio) or we should get rid of the folio filter.

**Comment by annamorphism** [comment]
I think there is another issue somewhere similar to this one (maybe the same but on the Chant Detail page?)

I do think if it's possible it would be nice to display perhaps the folio a feast starts on.  I might know I want 37r but not remember what feast it was, for which I could see having "31r--Nativitas Domini" and (e.g.) "39v--Oct. Nat. Dom" as helpful.

**Comment by dchiller** [comment]
I don't quite understand what you are saying...

I think as a user, I would like two dropdowns, one with just folios and one with just feasts. I could then use them in any combination:
1. select a folio, all chants on that folio are shown in sequence order
2. select a feast, all chants in source with that feast are shown, grouped by folio in folio order
3. select both a feast and a folio, all chants with that feast on that folio are shown

Does that address your comment @annamorphism

**Comment by dchiller** [comment]
#754 is related, but closed to be similar to OldCantus

On further thought, I realize that the reason for the current behaviour is probably that for most feast - folio combinations, there will be no chants, so it makes sense to narrow down those combinations for users. So... scratch my idea above. 

Taking a step back, what annoys me about the current set-up is:
1. If you select something from the feast-folio dropdown, the selected feast-folio combination changes to something else when the filtered results load. This is very bug-looking and confusing: why would you change what I selected? Was that supposed to happen or did my selection not register correctly?
2. As mentioned above, if I select a certain feast folio combination, I may have to scroll down to see chants on the folio I selected because we just show all the chants with the feast. It seems like the dropdown is lying to me: "hey! select this option to see chants with this feast on this folio, but I'll show you a bunch of other stuff too!"

**Comment by annamorphism** [comment]
Mostly...I suppose I was fixated on having one menu do two things instead of just having two menus. 
That said, I do sometimes use this sidebar dropdown (or its equivalent on the chant detail page) as a kind of "Table of Contents" to see roughly where in the book some feast is and how much space it takes up--which in a list of all the feasts you wouldn't see in the same way. Admittedly, not the intended use for a navigation menu...

**Comment by annamorphism** [comment]
I think I'm thinking of this issue: https://github.com/DDMAL/CantusDB/issues/916

**Comment by dchiller** [comment]
Ok, what if we kept the current two dropdowns, but instead of having an option for every feast - folio combination, we had something like:

1. Dom 1. Adventus (001r - 007v)
2. Hebd. Adventus (002v, 007r - 007v)
3. etc.

That way, you would get the same results as you currently do, but the dropdown would be telling the truth ("you'll get all the chants with this feast") and that might still help you with your quick "how much space does each feast take up" overview.

**Comment by annamorphism** [comment]
yes! this would do very nicely.

**Comment by dchiller** [comment]
Speaking of weird things about this page, the instructions in the center don't really map to what is happening. When you click the edit button for one of the chants on the right-hand side, you just get the usual chant edit form. So I'm going to modify those instructions as well.
