### ISSUE TITLE
limit access to Sources based on visible, public status

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#172]
CURRENT STATUS: This has been implemented in a basic form: if a source's `published` is False, the source and any chants/sequences contained within it can only be viewed by logged-in users, and only show up in search results for logged-in users.

Several suggestions have not yet been implemented. These suggestions include: 
- that users should be able to decide whether to include unpublished items in search results, as suggested by Ich
- that individual chants have the option of being set to `published`, and if so, being visible to anonymous users and appear in search results even if their source is not published, as requested by Debra in the wishlist

/CURRENT STATUS

Certain sources (for example, sources whose chants have not been proofread, or made-up sources created for testing purposes) should have limited access for non-logged in users.

Sources already have `.public` and `.visible` attributes.

- If a source's `public` is `True`, anonymous users should be able to view the source's detail page, as well as all the chants associated with that source. If it's false, anonymous users should get a 404 error (or perhaps a 401 Unauthorized error) if they try to access a url for a page associated with that source. Logged-in users should be able to access these pages
- If a source's `visible` is `True`, the source, as well as all chants and sequences contained within it, should appear in search results.

**Comment by jacobdgm** [comment]
Question: logged-in users may need to search for chants in order to compare with other versions of a chant while transcribing. Since they will have access to view all chants (even those that have not yet been proofread, and fictitious chants created for testing purposes), would it be a good idea to indicate whether a field has been proofread with a visual icon (maybe a green checkmark next to the field)? Or is it enough that such sources should be set to `visible=False`, so they're unlikely to just stumble upon the record?

**Comment by jwang44** [comment]
For simplicity, I prefer having only one field indicating whether a source is `published` or not. If it is published, everyone can see it (in the search, in the list, and through the url). If it is not published, only logged-in users (any level) can see it. That's the ideal solution.

However, this ideal design poses a challenge when we try to migrate data from the old Cantus to the new Cantus. In the old Cantus, the status of a source is more complicated, there are various codes for various status (more than two). In my previous work, I managed to boil it down to two attributes and named them `public` and `visible`. Having `public=True` and `visible=True` at the same time roughly translates to having `published=True` in the ideal solution.

**Comment by jwang44** [comment]
> would it be a good idea to indicate whether a field has been proofread with a visual icon (maybe a green checkmark next to the field)? Or is it enough that such sources should be set to visible=False, so they're unlikely to just stumble upon the record?

It is a good idea to add a visual icon to indicate the proofread status. However, it is not of high-priority because I think an indexer wouldn't carelessly copy the full text from a chant whose source is called "TEST2020", even if those fictitious chants and sources appear in the search results.

**Comment by jwang44** [comment]
We should do another round of data migration from old Cantus to new Cantus sometime next week. During that process, we can try to figure out how to best address this `published` tag.

**Comment by fujinaga** [comment]
@jwang44 can you explain why you need two attributes: `public` and  `visible`, as opposed to one attribute: `published`?

**Comment by jwang44** [comment]
The old Cantus uses two attributes that jointly control the visibility of a source: `status` and `source_status`. It was unclear why they needed two attributes for that, so I decided to replicate them and see if they were necessary. I named the two fields `public` and `visible` on the new Cantus. 
So far we haven't really found a good reason to keep the two-attribute design. We will merge them into one `published` attribute in our next data migration.

**Comment by annamorphism** [comment]
@jwang44 personally I find OldCantus's two-attribute design quite annoying, since it often means I can find sources through their chants but not get at the sources directly! just my two cents.
as for proofreading status: yes, a visual icon might be useful--keep in mind a lot of yet-to-be-proofread sources are *not* called useful things like "TEST" so it's not always easy (for a logged-in editor) to see if something is reliable or not. But if they can see it hasn't been published that's probably fine.

**Comment by jwang44** [comment]
It is strange that the source list doesn't show all sources, even after logging in. 

In the database, there is a total of 819 sources. However, only 533 are available in the source list on old Cantus https://cantus.uwaterloo.ca/sources?segment=All&search=&field_indexing_notes_value=&tid=All&century=All&tid_1=All. After logging in, there are 570 (533 published + 37 unpublished). 

What is up with the rest (819 - 570 = 249)? After examining the old database, I didn't find any field directly related to why those 249 sources are hidden from the list.

**Comment by jwang44** [comment]
In the old Cantus, there seems to be two systems working to together to determine whether a source should appear in the list. 

There is a boolean field `status`, which equals `False` for those 37 unpublished sources (those that become available in the list upon logging in). The `status` field equals `True` for all the other (819 - 37 = 782) sources. 

There is another field called `source_status`, which could take on one of the following values:

1. "Unpublished / No indexing activity"
2. "Unpublished / Indexing process"
3. "Unpublished / Editing process"
4. "Unpublished / Proofread pending"
5. "Unpublished / Proofreading process"
6. "Editing process (not all the fields have been proofread)"
7. "Published / Proofread pending"
8. "Published / Complete"

The old Cantus source list displays the (533) sources that meets BOTH of the following two conditions: 

- Its `source_status` is category 1, 7, or 8.
- Its `status` equals `True`.

Upon logging in, the old Cantus source list displays the (533+37) sources that meets ONE of the following two conditions:

- Its `source_status` is category 1, 7, or 8.
- Its `status` equals `False`.

**Comment by jwang44** [comment]
OK. After d54757a1c3de3065726fd6bf46c1c69cb4f567dc, there are no more `public` and `visible`, just one field `published`. With this one field (`published`), all sources can be separated into two categories: published and unpublished.

For the public (not logged-in):
Unpublished sources (and the chants in them) shouldn’t appear anywhere in the entire website. Even if they type in the correct URL, they should get an “access denied”.

For logged-in users:
Unpublished sources (and the chants in them) should be listed and appear in search results just like they are published. However, if the user is not assigned to the unpublished source, they should get an "access denied" when trying to access the detail page for that source or chants within that source.

**Comment by jacobdgm** [comment]
Progress update: work on restricting access to sources etc. based on published status is continuing apace. The current implementation restricts/filters based on whether a user is logged in - if they're logged in, they see results from unpublished sources; if they're not, they don't.

Eventually, we are going to nuance this approach, as discussed in Junhao's most recent comment. It should not be too hard to make the switch: in all situations, I'm using a `display_unpublished` boolean variable/parameter, so one will be able to search for all instances of `display_unpublished` and update the logic to determine what to display.

Top of mind lately is that in situations where filtering of results is occurring (e.g. `next_chants` function), the update will  be more complicated than simply changing the logic to determine whether `display_unpublished` is True or False.

**Comment by jacobdgm** [comment]
> Unpublished sources (and the chants in them) should be listed and appear in search results just like they are published. However, if the user is not assigned to the unpublished source, they should get an "access denied" when trying to access the detail page for that source or chants within that source.

i.e. we don't filter the results based on whether or not the user has access to them? It might be somewhat jarring for a user to click on a link among a bunch of search results and to be presented with an Access Denied page without further explanation. Do we want to implement a way for users to easily see whether or not the source is unpublished (e.g. add "(UNPUBLISHED)" at the end of the title), or whether or not the user has access to view the source/chant (possibly don't include anchor tags around sources/chants for which a user does not have access)?

**Comment by annamorphism** [comment]
I agree with @jacobdgm that it would be weird to click through to Access Denied. 
Something that seems to happen (somewhat imperfectly?) on OldCantus is that the information shows up as text, rather than a clickable link: ![image](https://user-images.githubusercontent.com/67451875/185465621-9b56899a-a273-4c4c-b838-52628a1670a3.png)
(For me this is true of concordance searches but not direct searches, but I also currently don't have a way of access as a mid-tier editor.) This seems to me this is a bit better than taking people to an Access Denied page (and is I think the second of your proposed alternatives.)

**Comment by jacobdgm** [comment]
with https://github.com/DDMAL/CantusDB/pull/301, this should be complete, at least in an initial implementation. Currently, if a user is logged in, they can access unpublished sources, and they will appear among search results, in list views, etc.

In most, if not all, of the places where we filter a query or limit access to a page based on the published status of a source, I've used the variable/parameter `display_unpublished`, so when we eventually implement a more nuanced approach, it should not be too difficult to find all the relevant places in the code where we're checking for published status. Searching for `PermissionDenied` might also catch other instances (that were implemented before i went through the codebase, for example), as well as `.published` and `__published`.

**Comment by fujinaga** [comment]
For logged-in users, all sources that are inaccessible should be greyed out and unclickable. These users should have the option of showing only the sources they have access as well.

**Comment by annamorphism** [comment]
There's still something a little wonky about published/unpublished.  McGill Ms18 claims to be published in the Django interface, as do all the other McGill manuscripts:

![image](https://user-images.githubusercontent.com/67451875/200413689-65ef88e7-86bb-48dc-89c8-9502a4570554.png)

But it doesn't show up in the list of sources (maybe because its status is "Indexing Process"). In OldCantus I can still search for chants in the source and so find the source page (https://cantus.uwaterloo.ca/source/675683), even when logged out, but in NewCantus it's behaving like an unpublished source, which I find strange...

**Comment by annamorphism** [comment]
but wait! there's more! McGill MS 111 *is* unpublished (and like MS 18, is in "indexing status") . Yet earlier today, chants from were still showing up on NewCantus--without being greyed out, but with the link to the source replaced with a chant page instead:

![image](https://user-images.githubusercontent.com/67451875/200421936-9a6cbc4f-750c-496c-bb3d-3d58087d5760.png)

Of course, now I can't replicate this state of affairs again (maybe it's already been fixed as I was investigating!) Or maybe there's something else to dig up...

**Comment by jacobdgm** [comment]
My understanding is that we're happy with the current, simple, binary published-unpublished system. Closing this for now; if someone complains, we can re-open it.
