### ISSUE TITLE
Promote people to superuser in Django admin

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#215]
Replace the current `is_staff` checkbox with a `is_superuser` checkbox. This way, the project manager can give superuser access (access to Django admin interface) to people without touching the command line. 

Project managers can access the Cantus editing functionalities (within the Cantus DB website, not the Admin interface). 
Superusers can access the Django admin interface. 
If we want someone to have access to both, they need to be in the `project manager` group and have `is_superuser` as `True`.

**Comment by jiwoojeongjj** [comment]
Also, there needs to be both boolean fields (`is_staff` and `is_superuser`) present as checkboxes in the admin interface.

`is_staff` determines whether a user is able to access the admin interface at all in the first place, and `is_superuser` determines if a user is given the permission to do anything in the admin interface.
This means that if a user is superuser but not staff, they won't be able to access the admin interface.
