### ISSUE TITLE
Facebook widget at the footer not working

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#219]
The Facebook widget that links to the Cantus DB Facebook page suddenly stopped working. Probably needs update.

**Comment by annamorphism** [comment]
seems to work ok for me (coming from the test site)...

**Comment by jwang44** [comment]
Hmmm. Interesting, it seems to be working on Chrome and Firefox, but not Safari. @annamorphism what browser are you using?

**Comment by annamorphism** [comment]
@jwang44 I'm in Opera, so it makes sense that it works if it works in Chrome.

**Comment by jiwoojeongjj** [comment]
@jwang44 I just checked on my end with Safari and it seems to work.

**Comment by jiwoojeongjj** [comment]
@jwang44 I just checked on Safari and it seems to show up (if I remember correctly, when we pair programmed, this widget didn't show up at all?). However, the "hyperlink" functionality is not there.

**Comment by jwang44** [comment]
Yes. It did not show up at all. I just checked with Safari on both my computers and it is still not showing up.

**Comment by jwang44** [comment]
Fun fact, the McGill legal clinic website, which uses the same type of widget, seems to be having the same issue https://licm.ca/legal-information/

**Comment by annamorphism** [comment]
Bizarre, it works on my Safari, and usually nothing works on my Safari because I'm using an older version. Something to do with the last  Safari update? @jiwoojeongjj @jwang44 are you both using the same version?

**Comment by jiwoojeongjj** [comment]
Now the widget doesn't even show up at all on my Safari... @annamorphism @jwang44 I am currently on the latest version of MacOS and Safari so this is very odd -- perhaps it does have something to do with the latest updates.
