### ISSUE TITLE
edit-volpiano page lacks proofreading checkboxes

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#248]
On the edit-volpiano page, OldCantus has checkboxes above the Standardized Spelling, MS Spelling and volpiano fields. NewCantus does not have these checkboxes.

**Comment by jacobdgm** [comment]
Some discussion surrounding proofreading checkboxes has already occurred in #170.

**Comment by jiwoojeongjj** [comment]
Correct me if I'm wrong @jwang44, but this is remedied by the separate proofread-chant view, right?

**Comment by jwang44** [comment]
Yes. There is a designated "proofread-chant" view for proofreaders to do their work. Checkboxes are available there, and that view is only accessible to users at `editor` level who have been assigned to the source.

**Comment by jwang44** [comment]
As we have a designated proofread view now, it is no longer necessary to put "proofread" checkboxes on the chant-edit page. To proofread chant, the proofreader can go to the chant-proofread page. The chant-edit page is only for editing chant fields.
