### ISSUE TITLE
Admin Navigation vs. Contributor Navigation

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#250]
in the footer of every page on OldCantus, I see "Admin Navigation" rather than "Contributor Navigation", which is what I see on NewCantus (On OldCantus, I'm accessing the website using an account with Contributor, Proofreader and Editor permissions; I haven't been able to access the website with an account with different permissions to see whether this changes). Under "Admin Navigation" are listed the following links:

- [My sources](https://cantus.uwaterloo.ca/my-sources)
- [Add Source](https://cantus.uwaterloo.ca/node/add/source)
- [List of indexers](https://cantus.uwaterloo.ca/indexers)
- [Import feasts from Cantus Index](https://cantus.uwaterloo.ca/feasts-import)
- [Update feasts from Cantus Index](https://cantus.uwaterloo.ca/feasts-update)
- [Publish unpublished chants](https://cantus.uwaterloo.ca/publish-chants)
- [Generate CSV - all published sources](https://cantus.uwaterloo.ca/one-csv)
- [Image links](https://cantus.uwaterloo.ca/image-links-csv)
- [Source index](https://cantus.uwaterloo.ca/index)
- [Update differentiae](https://cantus.uwaterloo.ca/diff_update)

**Comment by jacobdgm** [comment]
It would be worth someone with access to an account with different permissions trying to verify this; I've not been able to access the accounts that were created for me that should have fewer permissions.

**Comment by jiwoojeongjj** [comment]
The contents of the navigation have been decided by issues #225 and #226. As for the name: @jwang44 what would you like to call it?

**Comment by jwang44** [comment]
I checked with my account, and it says "admin navigation" for me. Can one of you check with your proofreader or contributor account?

**Comment by jwang44** [comment]
Looks like @jacobdgm has tested with his contributor and proofreader accounts, and it always says "admin navigation". Let's call it "admin navigation" then.

**Comment by jacobdgm** [comment]
I tested with a single account with all three of Contributor, Proofreader and Editor permissions, not with separate accounts.

**Comment by annamorphism** [comment]
isn't an admin a specific category of user (like a Debra) who presumably has different things they should see than a proofreader or an editor? unfortunately I don't remember what this was called when I was a mere Contributor.
