### ISSUE TITLE
Edit-volpiano page: "More information about text formats"

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#251]
below the Image Link field on the edit-volpiano page, NewCantus lacks a "More information about text formats" link. But I don't know why it's there in the first place - can someone else close this issue upon confirming that this doesn't need to be included in NewCantus?

**Comment by annamorphism** [comment]
it's a confusing link, too,  insofar as it tells you about html vs plain text but doesn't use the term rich-text. (Not clear to me anyway why the image link field is the only one with rich text--wouldn't it make more sense with "indexing notes" if anywhere?)

**Comment by jwang44** [comment]
For whatever reason, I don't see "More information about text formats" link... I see "enable rich text" instead.
![Screen Shot 2022-08-08 at 14 14 46](https://user-images.githubusercontent.com/54256124/183485611-eb4b3977-9876-497a-b04e-d38d50e90002.png)

**Comment by annamorphism** [comment]
@jwang44 you know, at first I thought I didn't have it either, then I saw it over to the side and figured I just missed it the first time around. But now it's gone again...?? Investigating.

**Comment by annamorphism** [comment]
Proving this to myself: "Edit" on the first chant of a source:

![image](https://user-images.githubusercontent.com/67451875/183489612-eaf624f8-35ef-4de3-bc6f-4a8a473617d7.png)
Navaigate to some other chant and edit, there it is!
![image](https://user-images.githubusercontent.com/67451875/183489759-d026ff26-1388-4cad-af7c-95129c02a824.png)
Back to the first chant, now the link is there!!
![image](https://user-images.githubusercontent.com/67451875/183489807-4dbaf6c3-63bf-4248-a8ac-acc64fe26d8d.png)

**Comment by jwang44** [comment]
Interesting... I don't understand why this rich-text is applied only to image link. Doesn't make much sense. I don't think we need to include this in the new Cantus. Currently the rich-text is only applied to news articles.
