### ISSUE TITLE
"My sources" panel should appear on homepage

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#256]
In OldCantus on the homepage when a user is logged in, a list of sources appears in a "My sources" box in the left sidebar. This box replaces the "jump to source" and "what's new" boxes that are visible when a user is not logged in.

In NewCantus, the "jump to source" and "what's new" boxes appear whether or not a user is logged in. Behavior on NewCantus should be changed to match that of OldCantus

**Comment by jiwoojeongjj** [comment]
When I log into old Cantus, I am able to see both "jump to source" and "sources created by user" in addition to "my sources".

Perhaps this is another instance of seeing different things based on the given privilege?

**Comment by jwang44** [comment]
I see "jump to source", "my sources", "sources created by user". 

Looks like "my sources" and "sources created by user" replace "what's new" upon logging in.
