### ISSUE TITLE
csv view: AttributeError sometimes appears

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#257]
(draft - more details coming soon)

the csv view (e.g. http://206.12.93.196/csv/704571 - arrived at via the CSV export link on http://206.12.93.196/source/704571) sometimes raises an attribute error, evidently when a source does not have a `segment`.

**Comment by jwang44** [comment]
A source should always have a `segment`. It is either "Cantus Database" or "Sequence Database". It's a foreign key field. In cases where a source doesn't have a `segment`, it is probably a test source that we created. 
Desired behaviour: when creating a source, assign it to "Cantus Database" by default.
