### ISSUE TITLE
Migrate news articles

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#278]
We need to find a way to migrate news articles from old to new Cantus. We can follow the same workflow used for migrating indexer/chant/source/sequence, as stated here https://github.com/DDMAL/CantusDB/wiki/Data-migration-from-the-old-cantus-to-the-new-cantus#indexer

The idea is to use the json export of the old Cantus. A list of news article IDs has been created in `article_list.txt`. Using the IDs in the list, we can scrape the json export for the article's fields.

**Comment by jacobdgm** [comment]
this is done. I chose to import them manually, which was a good thing because there were some links that needed to be updated etc.
