### ISSUE TITLE
Missing URL for "manage source editors" on source-detail page

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#285]
It should link to the corresponding page in Django admin.

**Comment by jacobdgm** [comment]
I can add this link, but presumably, we don't want _all_ logged-in users to see this link, correct? It would lead to a 403 error to everyone but managers, wouldn't it? Currently, all the "source edit options" are visible to all logged-in users - should we not be checking for each link to see whether it should actually be displayed?

**Comment by jwang44** [comment]
Then can you make it so that the links are visible only to those who are actually allowed to edit the sources?
