### ISSUE TITLE
Duplicate primary key issue

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#287]
For newly created objects (across all models) in the database, we are using auto-incrementing primary keys, which means we don't specify a primary key and let Django figure out the next available primary key and use that instead. For objects that already exists in the Old Cantus DB. we migrate the same primary key over, so that their IDs don't change.

After loading the fixtures (or data migration between old and new Cantus), a duplicate primary key issue may occur when we try to create new objects in the database. This happens because Django is confused about what primary key to use. 

Solution: run `manage.py sqlsequencereset` to generate the necessary SQL statements for resetting the sequence. Then go inside the Postgres container and run those SQL statements in `psql`. https://docs.djangoproject.com/en/4.0/ref/django-admin/#sqlsequencereset

**Comment by jacobdgm** [comment]
Is this an issue that we may need to deal with again in the future, or are you confident we'll not need to do this again?

I copied and pasted the content of the comment above into the [Data migration from the old cantus to the new cantus](https://github.com/DDMAL/CantusDB/wiki/Data-migration-from-the-old-cantus-to-the-new-cantus) wiki article - is this an appropriate place for it to be? (I'm not exactly sure when/where this issue occurs - do associated errors occur during migration / the loading fixtures, or as new objects get added to the database?) In any case, if this is an issue that may eventually resurface, information related to it should be in the wiki I think, not buried among issues that have been closed/completed.
