### ISSUE TITLE
Error when searching with empty incipit but with feast and mode

### ISSUE THREAD

**Issue by blueNoteb5** [DDMAL/CantusDB#29]
The error seems to be that a specific query that should return only one item is returning more than one.

![Screen Shot 2021-02-12 at 1 50 12 PM](https://user-images.githubusercontent.com/22383576/109167650-fc0e9a00-774b-11eb-80ab-b9a2ff473f85.png)
<img width="596" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/22383576/109167629-f749e600-774b-11eb-8978-21ee294c3518.png">

**Comment by annamorphism** [comment]
Note, too,  that in the earlier version of Cantus, the feast is chosen from a (long) dropdown menu, rather than typed in by the user.

**Comment by blueNoteb5** [comment]
@fujinaga Took me a while but I figured it out!

**Comment by fujinaga** [comment]
Great!

On Mar 12, 2021, at 17:59, Gustavo ***@***.***> wrote:

﻿

@fujinaga<https://github.com/fujinaga> Took me a while but I figured it out!
