### ISSUE TITLE
some links to edit-volpiano page not working

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#297]
This issue does not seem to be present in staging, so it probably occurred since staging was last updated.

Links from Chant Detail pages to the edit-volpiano page are broken. For example, clicking the "Edit" toggle at the top of /chant/170582 brings you to /edit-volpiano/123670?pk=170582, which raises a DoesNotExist error. In staging, the links work: http://206.12.93.196/chant/170582 brings you to http://206.12.93.196/edit-volpiano/123670?pk=170582, which works just fine.

Following links from an edit-volpiano page (one without a pk specified in the query, such as /edit-volpiano/123670) seem to work fine. However, in these cases, the URL seems to include both `pk` and `folio` parameters: on the page mentioned earlier in the paragraph, clicking on the first "Edit" link in the sidebar takes you to /edit-volpiano/123670?pk=170273&folio=001r . This may be the root of the issue.

**Comment by jacobdgm** [comment]
Investigating this further, I'm confused by several things. I brought the code up-to-date on staging, so the code is the same on both staging and my local machine. But I'm still getting different results.

On staging, clicking "Edit" at the top of http://206.12.93.196/chant/170582 brings me to http://206.12.93.196/edit-volpiano/123670?pk=170582, which gives me a NoReverseMatch error.

On my local machine, clicking on the same button at the top of http://127.0.0.1:8080/chant/170582 brings me to /edit-volpiano/123670?pk=170582, as expected. But I get a DoesNotExistError instead of a NoReverseMatch error. Maybe it's because the state of the database on staging is different from that on my local machine?

**Comment by jwang44** [comment]
Did you restart the django container after pulling? This kind of issue are usually solved by restarting.
________________________________

**Comment by jacobdgm** [comment]
Currently on staging, I'm getting `DoesNotExistError`s rather than NoReverseMatch errors. The django container has been restarted over the past few days, so now we have just one error instead of two!
