### ISSUE TITLE
Add list of concordances and related melodies to chant view

### ISSUE THREAD

**Issue by blueNoteb5** [DDMAL/CantusDB#31]

**Comment by jwang44** [comment]
List of Concordances and list of melodies on chant detail page

**Comment by jwang44** [comment]
This feature might be redundant because of the same lists are present in Cantus Index. Decision pending. Needs further discussion.

**Comment by jwang44** [comment]
implemented in 1d368a853ea8501480b5c568569184bbd22e0443
