### ISSUE TITLE
Required fields in admin source-change page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#326]
I recently tried locally to assign myself as a proofreader for a source, and after adding myself as a proofreader and pressing save, I was shown an error message saying "Please correct the errors below." Several of the fields, ostensibly, are required if a Source is to be edited/saved: **Notation**, **Current editors**, **Inventoried by**, **Full Text entered by**, **Melodies entered by**, **Proofreaders**, and **Other editors**. How many of these should actually be required?
- **Inventoried by** (points to Indexer object): by my understanding, any source in the database will have been inventoried by someone. This one seems good as a required field.
- **Notation**: this one is its own whole issue (see [Issue 327](https://github.com/DDMAL/CantusDB/issues/327)), but it seems plausible that every source will have an associated Notation.
- **Current editors** (points to User object): What of sources that have been fully proofread (for example, those in the Bower Database?) - it should be fine for sources to not have any current editors, I think.
- **Full Text entered by** (points to Indexer): What of sources that have been indexed, but no full texts have been entered. It should be fine for sources to not have an associated Full Text Entered By.
- **Melodies entered by** (points to Indexer): We have plenty of sources for which melodies have not been added. Why should this be a required field?
- **Proofreaders** (points to Indexer): will there not be some sources for which the proofreading process has not yet begun? It should probably not be a required field. (also, shouldn't this point to User rather than Indexer? I thought this was the part of the form where users were given proofreader access to a source (though I guess this will be resolved when we merge users and indexers)....)
- **Other editors** (points to Indexer): this seems like it should be a fully optional field. Why is it not?

I haven't started looking in detail into these - things may become clearer as I begin looking into how these are actually implemented.

It's important that we address this, because currently, sources cannot be added/edited unless at least one user/indexer has been specified for each of these fields.

Please, whoever comes across this, do comment on whether any of these fields should/shouldn't be required - these are my initial thoughts, but I've quite likely overlooked certain situations.

**Comment by jwang44** [comment]
To determine whether these fields should be required, just check with the Django shell. For example, we think `inventoried_by` should be required, but in practice, there might be 100 source objects leaving that field empty. In situations like this, we have to make the field optional to accommodate the data that we have.

**Comment by jacobdgm** [comment]
right - so i agree (EDIT: oops, I thought we were agreeing...) that `inventoried_by` should be required, though i understand that some of the data pulled from OldCantus might not have an `inventoried_by` (or its OldCantus equivalent) specified. My question is why so many of these fields are currently required, when it appears to me that they should be optional.

**Comment by jacobdgm** [comment]
And say someone needs to make a quick edit to the description of a source without an `inventoried_by`, and doesn't know who the person was who originally inventoried it. Should Django prevent them from saving their quick edit because they don't know who the MS was inventoried by?

**Comment by jwang44** [comment]
Looking at the source model, these are all many to many fields. So I think this has to do with our many to many field implementation. `century` is also a many to many field, does `century` have the same issue?

**Comment by jwang44** [comment]
I don't think Django should prevent them from saving the edit. If the source had `inventoried_by` empty before the edit. People should be allowed to keep it that way.

**Comment by annamorphism** [comment]
some addenda: 
-This is not where proofreaders are added, merely where they are credited, I think (now I forget how you *do* add them...)
-One potential workaround for things that don't have data that they should (for legacy reasons) would be to assign them to a "Cantus Database" user. So if one wanted to know who is "currently editing" the Bower sequences, they would show up as being edited by the database/admin.
