### ISSUE TITLE
Representation of Notation objects

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#327]
When I recently tried to edit a source, I was presented with an error message, and found that I was missing several required fields, including this one: ![Screen Shot 2022-09-06 at 08 59 56](https://user-images.githubusercontent.com/58090591/188641630-13f87954-0f92-405f-a561-effe3075a3db.png)
Notation objects are currently pretty inscrutable. They should be represented such that at least their `name` property is visible.

Larger question: why do we have notation objects at all? Currently, the notation model has only one property: `name`. Could this information in Source objects not be more simply represented by a CharField? Is using Notation objects simply the way things were done in OldCantus? Are we using them to ensure standardization among multiple Sources?

**Comment by jwang44** [comment]
Displaying the `name` property can be done by adding a `__str__()` to the model. I'm not sure why notation is a separate model either... It only has one property, true, but it was acting as a foreign key on the old Cantus I think. 

Another possible reason for keeping it a separate model is that we want a "controlled-vocabulary" in defining the notations. Currently, source creators who want to specify a notation must choose from a given list (of notation objects pre-defined by experts). If notation becomes a CharField, the source creator will manually type in the notation name, which may introduce typos or inconsistency with other sources of the same notation – the same notation may be called different things by different people.

**Comment by jacobdgm** [comment]
okay, so the current implementation is probably a combination of that's-how-it-was-done-in-OldCantus and standardization/controlled-vocabulary. Fair enough.

I'll push a change with an updated `__str__` presently.
