### ISSUE TITLE
Century, RISM Siglum not in admin interface

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#329]
Currently, one cannot add or edit Century or RISM Siglum objects via the django admin panel:
![Screen Shot 2022-09-06 at 10 32 50](https://user-images.githubusercontent.com/58090591/188662431-4639a746-f9c0-48c6-a4d7-fcebc4d53c2f.png)

Before I make changes to make them display: Is this by design, or is this an oversight? Are we confident that Centuries and RISM Sigla are all correct as they are currently, and that the project manager will never need to add new ones?

**Comment by jwang44** [comment]
I'm not sure why they are not added to the admin interface. They are present in the old Cantus "taxonomy manager", so I think they should be added to the admin interface.
