### ISSUE TITLE
Chant-create page - chant suggestion buttons - genre selector not filled

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#344]
On the chant create page (see for example http://127.0.0.1:8080/chant-create/699578), there are buttons along the right side of the page that are supposed to autofill many of the fields. There is code to autofill the Genre selector, but the code doesn't work - clicking on any of the buttons has no effect on the value of the Genre selector.

The issue seems to be with the line
```javascript
const genreId = Array.prototype.find.call(document.getElementById('id_genre').children, ({ textContent }) => textContent === "{{ chant.genre }}");
```

I'm having difficulty parsing it (I gather it's supposed to search through the `id_genre`, pulling out the proper genre id if the genre's ID matches the current genre name (i.e. "A", "V", "R", etc.)). It would be possible to store the proper genre ID associated with each Cantus ID in `next_chants` and not worry about calculating `genreId` on the fly, but I'm worried this approach could get a bit messy.

**Comment by jwang44** [comment]
I am so confused by this line of javascript... some refactoring is definitely in order. There should be a more intuitive way to populate the genre selector, just like how we populate the feast selector, which I believe has already been implemented somewhere.
