### ISSUE TITLE
Top menu in Safari

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/CantusDB#352]
To top menu in Safari, the menu goes beyond  the white background:

<img width="994" alt="Screen Shot 2022-09-26 at 3 56 51 PM" src="https://user-images.githubusercontent.com/1031785/192373720-180fcb76-24fd-4d60-97d5-0307c6a9fa80.png">

**Comment by jacobdgm** [comment]
So I thought this would be an easy fix, but I've tried loading the page in four different browsers on five different devices running three operating systems, and I can't replicate this bug. @jwang44, are you able to observe something similar on your machine(s)?

@fujinaga, what version of Safari do you have? Is this occurring on production (http://206.12.93.196) or on staging (http://206.12.88.113), or both? What type of device and OS were you using when you saw this?

**Comment by jwang44** [comment]
I was able to reproduce this by zooming out (`command` + `-`) to the maximum that safari allows me to. I was using safari 16.0 on Mac (but I don't think this matters much).

**Comment by jacobdgm** [comment]
ah! that's it! I can reproduce it. okay, I'll try to figure out how to fix it.

**Comment by fujinaga** [comment]
This issue seems not to be resolved. It's a low priority, though.
![image](https://user-images.githubusercontent.com/1031785/194765976-d97bf3d7-081d-4cde-a615-2a06db382716.png)
