### ISSUE TITLE
Search Chants in MS page - table spills beyond div when window is narrow

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#367]
On the chant-search-ms page (e.g. http://206.12.93.196/chant-search-ms/123610), the table of search results spills beyond the right side of the white div:
![Screen Shot 2022-09-30 at 10 32 09](https://user-images.githubusercontent.com/58090591/193293574-91620af2-1bd6-4d2b-8992-8dae8f145ec3.png)
OldCantus (e.g. https://cantus.uwaterloo.ca/searchms/123610) seems to handle this by limiting the minimum width of the page, and adding a horizontal scrollbar (they seem to do this for all pages, which is not ideal for viewing the site on mobile devices. Also, their search-ms page has some formatting issues of its own, even when the window is nice and wide)

It's not immediately apparent to me what's the best approach is to fixing this - the columns in the table can only get so narrow. We could apply `overflow: scroll;` to the parent div, which should make it easy to interact with on mobile devices and computers with trackpads. But that would make it difficult to interact with on computers with mouses. Maybe setting the pagination to 50 or 25 (as opposed to the current 100) would help with this, to make the bottom scrollbar more easily accessible? Thought about how best to approach this?

**Comment by annamorphism** [comment]
OldCantus does also make the columns a little narrower in similar by omitting some of the headers (office/Genre/position, which are all only 1-2 characters long). 
Having the pagination set a little lower seems like good idea too--there is no reason it needs to be up at 100. (People who love at-a-glance views will be over at "view full index" anyway...)

**Comment by annamorphism** [comment]
...although actually the table in this case doesn't have any headers at all, making it rather different from most other tables on the site... (it also seems to be missing a separate column for differentia, so they are superimposed on "position"...)
![image](https://user-images.githubusercontent.com/67451875/193350318-02f82c4b-0c8a-47f5-8bf4-f30b992ec12b.png)

**Comment by jacobdgm** [comment]
With [commit f70a135...](https://github.com/DDMAL/CantusDB/commit/f70a135f3139b6c2497e9a6a0ae07b1f5aa14e06), the headers for several of the columns have been removed, which doesn't fully solve the issue but at least ensures that it only shows up on _very_ narrow screens. We're displaying enough columns that I don't think we're going to arrive at a better solution than this. Closing.

**Comment by jacobdgm** [comment]
re-opening, since we re-added the column headers when we implemented ordering of search results...

**Comment by jacobdgm** [comment]
this also occurs on the chant-by-cantus-id page on devices with narrow screens.

**Comment by jacobdgm** [comment]
Curiously, on the Chant List page (e.g. http://206.12.88.113/chants/?source=123665), we get a side-to-side scrollbar in the table of chants when the window gets narrow. I think this is the ideal solution for tables with many columns in narrow windows. Looking at how this is set up on the Chant List page could be a good starting point for implementing this in other places around the site.

**Comment by lucasmarchd01** [comment]
Closed with #720
