### ISSUE TITLE
Proofread Chant page - clicking on folio link in sidebar takes you to edit-chants page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#380]
On http://206.12.93.196/proofread-chant/699578, Clicking on the >004r link in the top of the sidebar takes you to the corresponding edit-chants page, whereas it should take you to the corresponding proofread-chant page.

**Comment by jacobdgm** [comment]
also, the formatting on the Proofread page is not great - it begins with a bunch of fields on single lines: 
![Screen Shot 2022-10-13 at 15 53 05](https://user-images.githubusercontent.com/58090591/195696405-8ada8f6e-9aaf-4b23-848a-c3cf67bdb68c.png)

**Comment by jwang44** [comment]
I don’t think this is how it used to be. Looks like some front-end stuff changed. This could be an artifact introduced by the change in Bootstrap version. I noticed some other front-end change as well. We should discuss this on Monday.
________________________________

**Comment by jwang44** [comment]
Something is wrong with the front-end UI. The proofread form should look like this (screenshot from staging)
![Screen Shot 2022-10-13 at 19 41 15](https://user-images.githubusercontent.com/54256124/195731075-94271f74-6591-4c1c-888c-bf7a09a70111.png)

Notice the form and the gap between the main section and right side bar. The production, however, doesn't look right.

**Comment by jacobdgm** [comment]
hm... and my develop branch looks like production (i.e. fields stacked on top of each other, and no spacing between main panel and sidebar). Yes, probably something to do with the bootstrap version.
