### ISSUE TITLE
Connect to a real email backend for sending messages via the contact form

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#397]
Currently the contact form uses a default email backend that logs the message to the server. We should replace it with a real email backend that can send the message to an admin email address. A real email backend can also be used for sending password-reset links.

**Comment by jacobdgm** [comment]
Especially since we currently give a "success!" message once they press send, this should definitely be updated!

**Comment by jacobdgm** [comment]
Current status: currently, instead of having a contact form, we have a contact page with a link to email Debra.

**Comment by jacobdgm** [comment]
For the contact form, it would not be difficult to use a service like https://un-static.com to send messages to a specified email address. It's maybe not super professional, and wouldn't help with sending password-reset emails, but we should be able to trust it to do its job, and it would be less hassle than most of the other possibilities for implementing a contact form.

**Comment by ahankinson** [comment]
For DIAMM we use Amazon Simple E-mail Service. It's very low cost (~$0.03/mo) for the volumes we're sending.

**Comment by fujinaga** [comment]
I can pay for that.

**Comment by jacobdgm** [comment]
I noticed on the SIMSSA wiki that SIMSSA has an AWS email server that could be suitable for this purpose. I can't easily access the wiki now, but here's the URL I took down a couple of weeks ago: https://wiki.simssa.ca/wiki/Resources#AWS_Email

**Comment by fujinaga** [comment]
Yes, this is something we should implement soon (i.e., this summer).

**Comment by jacobdgm** [comment]
So, we have password reset emails/links set up (a feature which should be up on staging within the next day or two) - we have all the infrastructure we need to implement this.

I'd like to (re-)put forward the **suggestion that we simply keep the link to email Debra**. The main reason is that contact forms are more complicated than showing people email addresses. Also, since they are more complicated than email links, it's more likely that something will go wrong at some point, and **if something breaks with our contact form, there will be no way for anyone to inform us** of this.

In addition, as a user, I really prefer being able to send my own emails - I'm able to control formatting myself, can include attachments if I need to, and so on.

Including an email link is a simpler, neater, and more robust solution than setting up a contact form.

**Comment by fujinaga** [comment]
> So, we have password reset emails/links set up (a feature which should be up on staging within the next day or two) - we have all the infrastructure we need to implement this.
> 
> I'd like to (re-)put forward the **suggestion that we simply keep the link to email Debra**. The main reason is that contact forms are more complicated than showing people email addresses. Also, since they are more complicated than email links, it's more likely that something will go wrong at some point, and **if something breaks with our contact form, there will be no way for anyone to inform us** of this.
> 
> In addition, as a user, I really prefer being able to send my own emails - I'm able to control formatting myself, can include attachments if I need to, and so on.
> 
> Including an email link is a simpler, neater, and more robust solution than setting up a contact form.

But wouldn't that mean we will expose Debra's email address? 
Did you try Google Forms?

**Comment by jacobdgm** [comment]
> But wouldn't that mean we will expose Debra's email address?

Yes, and Debra's fine with this. This copied from an email from her back in November:

> Just an email address is great!
...
No need for a whole form. Thanks!

> Did you try Google Forms?

This would be even more complicated than using the email backend we're using for password resets. Let's please not do this.

**Comment by fujinaga** [comment]
> > But wouldn't that mean we will expose Debra's email address?
> 
> Yes, and Debra's fine with this. This copied from an email from her back in November:
> 
> > Just an email address is great!
> > ...
> > No need for a whole form. Thanks!
> 
> > Did you try Google Forms?
> 
> This would be even more complicated than using the email backend we're using for password resets. Let's please not do this.

Ok.
