### ISSUE TITLE
Add xml data from cantus website to database

### ISSUE THREAD

**Issue by blueNoteb5** [DDMAL/CantusDB#4]
I have all of the data in xml form other than the chants, but I have a few tens of thousands of chants.

Need to write a ``manage.py`` command to each type of data (notation, feast, office, genre, source, etc) into the Postgres database.

- [x] Chant
- [x] Feast
- [x] Genre
- [x] Indexer
- [x] Notation
- [x] Office
- [x] Provenance
- [x] Segment
- [x] Sequence
- [x] Siglum
- [x] Source

**Comment by napulen** [comment]
Are those XML files somewhere? Noticed that all the management scripts receive these xmls and I am curious to take a look at them. Thanks!

**Comment by blueNoteb5** [comment]
I'll push them to the repo
