### ISSUE TITLE
login page--request password

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#413]
On OldCantus you can initiate a request for a new password--on NewCantus it's just an eternal log-in loop.

Might also be nice to have a way of initiating the request to become a new contributor,  but maybe we want to keep new accounts separate from fixing old ones (so that new users can be vetted first, but old users can get automatic password resets).

**Comment by jacobdgm** [comment]
you're talking about [this page](https://cantus.uwaterloo.ca/user/password) on OldCantus that NewCantus lacks, yes?

We can add this to our list of things we'd be able to fix if/when we set up an email server, I suppose. Without such a connected email server/service, there's not much we can do about this. Currently, only people who are logged in can change their passwords. If someone loses their password, an administrator (i.e. someone with access to the [admin interface](http://206.12.93.196/admin/)) will be able to assign them a new password, which that user can then use to log in and set their own password - it's not ideal, but at least no one will be permanently and irreversibly locked out of her account.
