### ISSUE TITLE
sort columns of search results

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#414]
In OldCantus the column headers of chant searches are clickable to order the search results within that column, like a spreadsheet:
![image](https://user-images.githubusercontent.com/67451875/200433412-ac07b01f-6d51-40e5-a5d3-70ee14f257b7.png)

NewCantus doesn't do this. It's a feature I use a lot, so it would be nice if it were there! (Actually I would love if the headers in the concordances tables worked the same way, but that may not be possible...)

**Comment by jacobdgm** [comment]
some working out on my own:
in OldCantus, this column sorting is present in the following views:
- [Chant Search view](https://cantus.uwaterloo.ca/search?t=ponam%20in%20sion&op=starts&genre=All&field_position_value=&cid=&mode=&feast=&volpiano=All&field_differentia_new_value_op=contains&field_differentia_new_value=&order=field_full_text_ms&sort=desc)

It's not present in the following views:
- [Chant List view](https://cantus.uwaterloo.ca/chants?source=123610) (all chants in a given source)

**Comment by jacobdgm** [comment]
This has been updated on the staging server - come all ye and click on the pretty column headers to ensure there are no bugs! See http://206.12.88.113/chant-search/?op=contains&keyword=ponam%20in%20sion&order=has_melody&sort=asc

**Comment by annamorphism** [comment]
...Is it sorting the Office part by the time the office happens and not just alphabetically? very cool!
OldCantus groups together blank Mode and * Mode, which I think makes some sense, but also puts them at the front (which I think makes less sense). Maybe putting them at the back of the sort would be nicer. 
No bugs detected so far.
