### ISSUE TITLE
unexpected chant search results

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#419]
"Paris" in the "search chants" box gives a great many results, none of which actually contain "paris." They seem to be identical with the results searching for "paries": 
![image](https://user-images.githubusercontent.com/67451875/201496676-4cbb1aa7-145c-4a02-a18a-3650a8b40903.png)
![image](https://user-images.githubusercontent.com/67451875/201496673-640d188c-1090-4b0a-ae9d-77145ded7352.png)

Meanwhile searching "nostru" [not a latin word] does not give you the same results as "nostrum"; searching "nostr" (also not a Latin word) DOES gives you results, which include "nostrae", but seemingly not "nostrum".  So it's not really clear what's going on here...
![image](https://user-images.githubusercontent.com/67451875/201496608-c0096ff1-e37e-4667-bb46-2c3544977814.png)
![image](https://user-images.githubusercontent.com/67451875/201496618-97b8626b-d9a2-48a1-92e6-de24ab644ee4.png)
![image](https://user-images.githubusercontent.com/67451875/201496633-cf73bee6-cf5b-4e7d-91e8-9aa621b46d32.png)

(In OldCantus "nostru" does give you results, and you also get a little arrow pointer for the relevant word which is sort of neat.)
![image](https://user-images.githubusercontent.com/67451875/201496739-35cc4775-f09e-492a-8e63-e20862ec66b2.png)

**Comment by jacobdgm** [comment]
this is very interesting! it's not simply a question of fuzzy matching, as leaving out/adding single letters achieves inconsistent results (all the below from NewCantus):
`paries`: 37750
`aries`: 5
`pries`: 0
`pares`: 23
`paris`: 37750
`parie`: 37750
`zparies`: 0
`pzaries`: 0
`pazries`: 0

**Comment by annamorphism** [comment]
Since I was testing some searches for #516 I may as well add the results here; chant-search gives different numbers than keyword-search, but the effect is similar:

urbs :   256 (search bar) , 318 (keyword)
urbis :  70 / 89
urbi :    70 / 89
urbem: 60 / 73
urbe:    256/318
urbes:   256/318
urbibus:0/0 
urbium: 4/5 (I swear I managed to get a 3-result search on this one, but I didn't screenshot it and I haven't replicated it, so maybe I imagined it.)

So in both flavours of search we get urbs=urbe=urbes, and urbis=urbi, but urbem, urbibus, and urbium are their own words (and as far as I can tell a separate set of search results, not a subset.)

(As for non-words, "urb" gives the same number of results as "urbs", but "urbiu" and "urbim" don't give any results at all.)

**Comment by jacobdgm** [comment]
this is mostly me thinking aloud while trying to figure things out, but it's likely this has to do with our using Postgres's search vector tool for keyword searches - it's supposed to support fuzzy matching, as well as ranking results based on its best guess of how relevant the result is. We might want to rework this, as I think we don't need ranking of search results - with the links in the column headers, we want to let users order search results themselves.

**Comment by fujinaga** [comment]
Can we implement a straight search without any fuzzy matching first?

**Comment by jacobdgm** [comment]
> Can we implement a straight search without any fuzzy matching first?

I like this idea, and yes, I should be able to do this.

**Comment by jacobdgm** [comment]
This seems to be fixed (i.e. no fuzzy search) currently on Staging, but not on Production: http://206.12.88.113/chant-search/?op=contains&keyword=paris finds 60 matching chants, mostly having to do with "Pariseus" and/or variant spellings of "pharisei" etc. Let's wait until this is confirmed on Production before closing, but it seems likely that no further action will be required towards fixing this.

**Comment by jacobdgm** [comment]
@annamorphism, can you confirm this is fixed, and close this issue if warranted?

**Comment by annamorphism** [comment]
I think this now works as expected! Closing.
