### ISSUE TITLE
OldCantus has several flavours of chant-search page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#421]
On OldCantus, the default behavior upon visiting the chant-search page is evidently to search for the specified keyword in only the incipit field, not in the full-text field.

[https://cantus.uwaterloo.ca/search](https://cantus.uwaterloo.ca/search):
![Screen Shot 2022-11-14 at 14 45 23](https://user-images.githubusercontent.com/58090591/201751505-87af4f1a-53fd-4c44-91c3-9d4115f232cc.png)
[https://cantus.uwaterloo.ca/search?op=starts&t=apud&genre=All&field_position_value=&cid=&mode=&feast=&volpiano=All&field_differentia_new_value_op=contains&field_differentia_new_value=](https://cantus.uwaterloo.ca/search?op=starts&t=apud&genre=All&field_position_value=&cid=&mode=&feast=&volpiano=All&field_differentia_new_value_op=contains&field_differentia_new_value=):
![Screen Shot 2022-11-14 at 14 46 36](https://user-images.githubusercontent.com/58090591/201751714-b0d26b7b-c121-4b99-a853-a9d06d720647.png)

Clicking on "Search "apud" in full texts" takes you to a page with a different number of search results
[https://cantus.uwaterloo.ca/search-all?op=contains&t=apud&genre=All&field_position_value=&cid=&mode=&feast=&volpiano=All&field_differentia_new_value_op=contains&field_differentia_new_value=](https://cantus.uwaterloo.ca/search-all?op=contains&t=apud&genre=All&field_position_value=&cid=&mode=&feast=&volpiano=All&field_differentia_new_value_op=contains&field_differentia_new_value=):
![Screen Shot 2022-11-14 at 14 48 17](https://user-images.githubusercontent.com/58090591/201752037-16b387d9-1da6-45b3-bb1f-51b3f47a17b3.png)
(notice how the url has changed from cantus.uwaterloo.ca/search to cantus.uwaterloo.ca/search-all)

If the link at the top is to be believed, searching by incipit is faster than searching by full text. Go figure.

On the main search page (but not on the search-all page), there's a link to a "printer-friendly version", which seems to be be plain html with minimal CSS styling
[https://cantus.uwaterloo.ca/search-print?op=contains&t=apud&genre=All&field_position_value=&cid=&mode=&feast=&volpiano=All&field_differentia_new_value_op=contains&field_differentia_new_value=](https://cantus.uwaterloo.ca/search-print?op=contains&t=apud&genre=All&field_position_value=&cid=&mode=&feast=&volpiano=All&field_differentia_new_value_op=contains&field_differentia_new_value=):
![Screen Shot 2022-11-14 at 14 50 36](https://user-images.githubusercontent.com/58090591/201752476-26cb9214-9d1f-493e-890a-ed807bcb4cf6.png)
(notice that the url has changed from cantus.uwaterloo.ca/search to cantus.uwaterloo.ca/search-print)

As noted by @annamorphism in #419, there's also a link to search for the keyword(s) on CantusIndex. This link is visible on both the main search page and the search-all page, but not the search-print page.

**Comment by jacobdgm** [comment]
On the search-all page, the default "starts with // contains" option is "contains" (though "starts with" can be selected), whereas the default option on the normal search page is "starts with" (though "contains" can be selected).

There are a bunch of other options in the above-mentioned drop-down selector which NewCantus doesn't have ("Is equal to", "Contains any word", "Contains all words", ...). Some of them don't appear very useful ("Is empty (NULL)", "Not regular expression"). OldCantus may be doing database queries directly so these options may have been simple to implement - some of these may be easy to implement in django, but implementing all of them should probably be a low priority.

**Comment by jacobdgm** [comment]
Also, the normal search page has a different set of order-by links on the column headers than the search-all page has.

**Comment by jwang44** [comment]
About the search options, "starts with" and "contains" are sufficient. No need to worry about the other options. They are used very rarely. This was confirmed by Debra some time ago.

**Comment by jwang44** [comment]
As for the existing search interface in New Cantus, we are harmonizing the interface on purpose. I'm not sure whether having incipit search and full text search separately is helpful, but we should try to keep the fields consistent (i.e., the same fields in the same positions in the same order across all "chant-search" pages). On the New Cantus we currently have two chant-search pages: search chants (accessible from the top navbar) and search chants in source (accessible from the source detail page). They search in different scopes, but the interfaces are the same. If we are to implement any new chant-search pages, I would suggest keeping the same interface.

**Comment by jacobdgm** [comment]
okay, formatting pages nicely for printing is implemented, and it sounds like incipit vs. fulltext search will be unnecessary (and perhaps counterproductive, if we decide to implement #361). I'm closing this; we can reopen it if we later decide that fulltext search vs. incipit search is the way to go.
