### ISSUE TITLE
CSV updates

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#428]
When working with McGill MS73 @dchiller and I found it takes quite a while for changes made in CantusDB to propagate to the CSV file, and thus to show up in Cantus Ultimus. There is an "update CSV" button, but it takes a long time (is it doing anything, or is there a regular nightly update and the button is irrelevant, or does an update get scheduled later iff the button is pressed, or...?)

@jacobdgm can you look into how and when the source CSVs get updated when you get a chance?

**Comment by jacobdgm** [comment]
I'm in the middle of getting set up on a new computer, so I don't currently have the most powerful "Update CSV"-button-finding tool available to me, but taking a quick look at both Production and OldCantus, I can't find this button. Can you share a URL and a location on the page?

(looking at [http://206.12.93.196/source/680970](http://206.12.93.196/source/680970) and searching "update" is not turning anything up. Doing this on the [corresponding OldCantus page](https://cantus.uwaterloo.ca/source/680970) achieves similar non-results. I know OldCantus keeps a number of files usually available via its APIs precalculated and cached, but I'm pretty sure we don't do this for any of NewCantus's APIs.)

**Comment by annamorphism** [comment]
It's probably limited to admin view, and it's under "manage sources" on the lower right of the source page. Not a button really, just a clickable link. 

![image](https://user-images.githubusercontent.com/67451875/203634165-2b871e98-8d5a-4ef6-b0d3-700f5c2d34dd.png)

**Comment by jacobdgm** [comment]
I can find what you're describing on OldCantus while logged in - https://cantus.uwaterloo.ca/source/680970 - but not on NewCantus Production - http://206.12.93.196/source/680970, and searches for "Authoring" and "Update CSV" in all files in NewCantus come up with nothing.

My guess is that this is an OldCantus thing that doesn't affect NewCantus. @annamorphism, can you take a look again and confirm this can only be found on OldCantus - if so, can you close this issue, and if not, can you provide a link to a page on NewCantus Production (or Staging) where I can find this so we can get to the bottom of it?

(Having looked at this in more detail, the "Update in the Cantus Analysis Tool" link suggests there may be functionality in OldCantus that no-one has made an effort to implement in NewCantus. Like there's [this whole page](https://cantus.uwaterloo.ca/json-analysis-export?src=680970) on OldCantus, for which I'm not aware of a similar page on NewCantus...)

**Comment by dchiller** [comment]
If it is not in new Cantus, then what is the mechanism by which these csv exports are updated in new cantus? Or do we not have the csv's at all in new cantus -- this would be a big issue for Cantus Ultimus as it currently stands -- all CantusDB information is imported to Cantus Ultimus through these csv's.

**Comment by annamorphism** [comment]
@dchiller There is still the option to download the CSV in NewCantus, and it does seem to work. Not sure how/when/whether these CSVs update to reflect changes to chants in the DB though. I can't seem to log into NewCantus (?) or I would try editing a few chants and seeing what it does... 
Looking at the URLs, it looks like OldCantus stores a .csv file in "files" (which presumably needed to be updated from time to time) while NewCantus has it under csv/source-id--so I'm guessing Django just generates the CSV upon request instead of Cantus storing it? That seems like it would keep CU more up-to-date *and* not break anything, but it would be good to confirm/test this...

**Comment by dchiller** [comment]
Ah, I see -- thanks @annamorphism 

If the csv is generated on the fly with the data in the Django backend, then agreed: it's even better than old Cantus!

**Comment by jacobdgm** [comment]
Can confirm - NewCantus's source CSVs are [generated on the fly](https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/main_app/views/views.py#L164).

**Comment by dchiller** [comment]
Sounds good!

**Comment by jacobdgm** [comment]
> it looks like OldCantus stores a .csv file in "files" ... but it would be good to confirm/test this...

In several places, OldCantus and other websites in the Cantus Network have been known to save the output of some expensive calculation, and only update it when a user requests that the calculation be run again. Your guess is very likely to be true, I think.

**Comment by annamorphism** [comment]
does having to calculate the CSV on the fly affect the functionality of Cantus Ultimus at all? or is it, in the scheme of things, not actually that expensive a calculation for CU's purposes? something to think about on a different thread, maybe. closing this issue.
