### ISSUE TITLE
On Chant Detail page, we should add links to corresponding Cantus Ultimus page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#429]
From an email from Debra:

> A really helpful item in the Cantus Database detail record (the view of a single chant in a source) would be the link to that chant/view in Cantus Ultimus.
> 
> Could we add this field right away... ?
> 
> Then, can the folio/page links for all the CU-processed sources be fed automatically into that new field?
> 
> I can imagine this link being directly under the Image Link field on both the data entry screen and the view for the user.

**Comment by jacobdgm** [comment]
In talking with @dchiller about how optimally to implement this, some relevant points emerged:

- sources/manuscripts have different identifiers in Cantus Database and Cantus Ultimus (for example, see Einsie in [Cantus Database](https://cantus.uwaterloo.ca/source/123606) vs [Cantus Ultimus](https://cantus.simssa.ca/manuscript/74/))
- it would be possible to set up a mapping between sources in CD and those in CU, it require an amount of data entry
- eventually, for a number of reasons, it would make sense to harmonize the source/manuscript identifiers in CU with the source identifiers in CD.
- Even though its URLs sometimes include an `&chant=N` query parameter, Cantus Ultimus is not currently set up to show a specific chant on a folio when that query parameter is specified.
  - so, for any given chant in Cantus Database for which we want to generate a link to the corresponding page in Cantus Ultimus, all we would need to provide is
    - the proper manuscript ID, and
    - the chant's `folio`

**Comment by jacobdgm** [comment]
@dchiller, you were working on renumbering sources a while ago, right? How is that going? This might be in a place where it will be trivial to implement - can you comment?

**Comment by dchiller** [comment]
When the source is on Cantus Ultimus, we should have the image link to there; if not, to the host institution. But we don't need both (and also not another field) because we can construct the CU links from the chant folio and sequence #.
