### ISSUE TITLE
Add Change History to all models

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#430]
At the LinkedMusic project meeting, it was suggested that we should begin keeping a history of all changes to all of our models (rather than the current approach of simply noting when the most recent edit occurred and the user who made the edit). @ahankinson noted that there are simple, off-the-shelf ways to implement this (and suggested [django-simple-history](https://django-simple-history.readthedocs.io/en/latest/), if I recall correctly).

**Comment by ahankinson** [comment]
Nope -- `django-reversion` https://django-reversion.readthedocs.io/en/stable/

**Comment by jacobdgm** [comment]
It sounds like this will be helpful for implementing #1158. Increasing the priority from low to medium.
