### ISSUE TITLE
OldCantus has an "Export data for analysis tools" page that hasn't been implemented in NewCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#432]
OldCantus has an "[Export data for analysis tools](https://cantus.uwaterloo.ca/json-analysis-export?src=680970)" page that hasn't been implemented in NewCantus. It can be reached by clicking "» Update in the Cantus Analysis Tool" in the "Manage Source" panel on a [source detail page](https://cantus.uwaterloo.ca/source/680970) (must be logged in).
![Screen Shot 2022-11-28 at 3 29 41 PM](https://user-images.githubusercontent.com/58090591/204374700-119527c8-b8fc-498f-aff9-8725a3dd0beb.png)

"REBUILD THE EXPORT" links to https://cantus.uwaterloo.ca/json-analysis-export?src=680970&rebuild=1; clicking it causes the page to spend a while loading, ultimately arriving at the same page.
"CLICK HERE" links to http://cantusindex.org/collect-src?db=CD&src=680970

I don't really know what the Cantus Analysis Tool does - at some point, I need to figure it out, and figure out whether there is anything we need to do (e.g. data we need to provide in a specific format) to make it work, or whether it's something for which we just need to link to the relevant page on CantusIndex.

**Comment by annamorphism** [comment]
I am fairly familiar what the Cantus Analysis Tool does on the user end of things--it takes the contents (that is, the feast, Cantus IDs, and relevant liturgical positions--not texts or melodies) of a whole bunch of sources across the network and compares them to one another for important similarities. Presumably it is getting this out of a json file on each source. 

Like the CSV-updater, I am not sure exactly what the corresponding user action on Cantus does. You would think that clicking on it means "yes, this source has been proofread and is now ready to be analyzed elsewhere", but the Tool has access to information about a bunch of sources that I never sent it directly (and at least one called "Test Source Do Not Publish".) So it seems like it also updates its internal source list automatically to some degree.  

This is probably not ideal, actually; I think the best behaviour would be for the json file to be sent automatically to the Analysis Tool (or, made fetchable by the Analysis Tool) iff the source has actually been published; that way the tool is as up-to-date as possible, without containing any weird un-proofread sources.  However this probably requires some communication with Cantus Index to make sure nobody is working at cross-purposes.

**Comment by jacobdgm** [comment]
giving this, somewhat-arbitrarily, a "necessary for full (but not for soft) launch" label. @annamorphism, can you comment on whether / to what degree this should be prioritized?

**Comment by annamorphism** [comment]
I can't give a clear answer on priorities, because I'm not 100% sure what this does--or rather, whether it is still a necessary part of the Cantus Analysis tool. We definitely want NewCantus to interact with the Cantus Analysis tool, but it seems like Cantus Index may pull this information itself without needing us to push it, as it were--in which case this page is a fossil of some former method.  But I don't think we can just assume that. 
So: if this is a fossil, hardly necessary. If this is critical to keeping Cantus Index's analysis tool up to date with whatever is in OldCantus, fairly important, but not urgent short-term.  It may be necessary to ask somebody at Cantus Index how this works.

**Comment by jacobdgm** [comment]
In a video call with Debra yesterday, she said this exists as a workaround for something in Cantus Index. As Cantus Index is being rebuilt in Backdrop in the next while, it may be that this tool becomes unnecessary once the rebuild is complete.

Since we don't know exactly what this does, and it may prove to be unnecessary, we decided to shelve this for the time being - if someone complains that this is missing and can explain to us what it's supposed to do, we'll revisit/implement it.

**Comment by jacobdgm** [comment]
It's been 6+ months and no one has complained. Closing - we can reopen if necessary.
