### ISSUE TITLE
volpiano special cases don't work

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#439]
Some of the more complicated volpiano cases don't seem to render right. E.g. for http://206.12.88.113/chant/675554 the {bracketed} text should align with the 6-----6 in the Volpiano, but it is offset.
![image](https://user-images.githubusercontent.com/67451875/204896700-6922f735-e2a4-4fc2-841b-24a12330c6b4.png)

**Comment by annamorphism** [comment]
actually in this case it seems to mostly be that the two places handle the absence of a clef differently (in NewCantus it throws everything off, which it doesn't in oldCantus. Since things really ought to have a clef, maybe this difference is actually desirable. 
However there are also cases where there is a bizarre gap in the staff for the "preview":
![image](https://user-images.githubusercontent.com/67451875/204900749-0139f161-6cd4-4775-a729-43bbdd2890ef.png)
On the actual chant page, it isn't there, but it doesn't align as a result: 
![image](https://user-images.githubusercontent.com/67451875/204900943-8a7966cc-498d-40bb-9789-8eb085623a9e.png)

**Comment by jacobdgm** [comment]
leaving a note for future work on this: when I visit /chant/675554 locally, the following output is printed to my terminal:

```
MELODY SHORTER THAN TEXT, DIDNT REACH TILDA
[06/Dec/2022 18:05:17] "GET /chant/675554 HTTP/1.1" 200 266216
```
So there's something going on with our matching-notes-to-syllables function. Hooray for debugging print statements that accidentally got committed at some point and are now doing useful things!

**Comment by jacobdgm** [comment]
I looked through the matching-text-with-volpiano scripts a few weeks ago, and I recall seeing that when we start syllabizing a text, we add an empty "word" at the beginning of our list of words, to match up with the clef. Since there's no clef in the screenshots you provided, this probably explains why the first element that should have a word/syllable has nothing beneath it.

I abandoned the refactoring-and-documenting-the-volpiano-scripts project because I wasn't aware of it being relevant to any issues that were live. Now that I see this, perhaps it's worth me picking it up again.

**Comment by jacobdgm** [comment]
Further to my previous comment: I just tried editing the chant, adding `1---` to the start of the volpiano, and I think this fixes it. So, this wouldn't happen in a perfect world where all our data has no errors, but as we don't live in that perfect world and there may be other chants without clefs, we should probably rework our scripts to account for this possibility (as OldCantus already does).

The chant in question, edited to include a clef:
![Screenshot 2023-03-31 at 2 44 51 PM](https://user-images.githubusercontent.com/58090591/229204109-c9a13bb7-3cb5-4d94-890a-935e3ab6f1ac.png)

A possible enhancement would be to prevent a user from saving a chant if its volpiano doesn't begin with a clef and three dashes.

**Comment by annamorphism** [comment]
A related error that misaligns text:
Here's 675565 in NewCantus
<img width="530" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/1015aa6f-89f5-44d7-8b44-01c1941bfd5d">
and in old:
<img width="441" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/104cacbc-be5f-47a0-9f71-b4a14a273bff">

Issue seems to be that there are extra hyphens in the Volpiano, which are ignored in Old but not New.

**Comment by jacobdgm** [comment]
Inasmuch as bugs can be aesthetically pleasing, this last bug is a good one. Nice catch!

**Comment by jacobdgm** [comment]
@dchiller - this is relevant to the harmonize-how-cantusdb-and-cantusultimus-treat-volpiano project.

**Comment by dchiller** [comment]
Thanks -- I'll refer to these cases as I continue developing/testing that.

**Comment by dchiller** [comment]
@dchiller will look at this chant again.

**Comment by dchiller** [comment]
Both of the above-mentioned chants look good on production now. I suspect that these (and related cases) were resolved with the integration of the volpiano-display-utilities module, so closing this...future alignment issues can be opened separately.
