### ISSUE TITLE
"Sequence" disappears for value 0

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#440]
For fragments, we sometimes have the "Sequence" value as 0, meaning it is an incomplete item that begins on the previous (missing) page. This doesn't show up in New Cantus though:
![image](https://user-images.githubusercontent.com/67451875/204898397-56c6be48-6512-43c0-8d7a-0a1c6275315c.png)
 cf oldCantus:
![image](https://user-images.githubusercontent.com/67451875/204898679-19ad2e72-fc67-4f22-92e1-d80798ecc37a.png)

I also think it would be better if the folio/sequence items displayed next to each other, as they do in OldCantus. Typically you need both bits of information at once.

**Comment by jacobdgm** [comment]
Nice catch!
