### ISSUE TITLE
Upon saving a chant in chant-edit page, user should be redirected to the chant-detail page

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#443]
On OldCantus, if you notice an error in a chant and edit it using the "edit" tab on each chant page, you get taken back to "view" once you are done, so you can see the results of your efforts. NewCantus seems to keep you in edit mode, which might not be desirable.

**Comment by jacobdgm** [comment]
(just a thought - maybe this is one of the key differences between the otherwise-similar chant-proofread and chant-edit pages)

**Comment by jacobdgm** [comment]
@lucasmarchd01 - did you recently do work on this? when you get a chance, can you confirm whether this has been fixed already and, if so, close it?

**Comment by lucasmarchd01** [comment]
Closed with #665
