### ISSUE TITLE
Articles have different IDs in OldCantus and NewCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#445]
In NewCantus, the articles were manually copied and pasted rather than imported via a script, and the IDs of corresponding news stories thus do not match (e.g. compare http://127.0.0.1:8888/article/32 to https://cantus.uwaterloo.ca/article/710905).

I don't know how much this is an issue (perhaps people have used links to articles in OldCantus in references, and if so, it's probably important that these links remain static). If we think it's important, the simplest solution would probably be to manually change the IDs to match those of their OldCantus counterparts.

(We can probably assume that no one has cited any of the articles on NewCantus yet, and that few if any people have bookmarked articles on NewCantus. Or do we think the articles have been up long enough that it is important that we set up some sort of redirection?)

The two options that I think worth considering, in order of preference, are:
- leave the numbers as they currently are
- renumber the articles to match OldCantus as soon as possible, and don't bother with redirection

Can anyone offer another opinion on what the best approach might be?

**Comment by annamorphism** [comment]
My gut feeling is that a lot of the articles are about ephemeral things like upcoming conferences or recent presentation, and that they are unlikely to need to have stable references years from now (at best they would be useful as evidence that Cantus presented at some conference in the past, but for that it wouldn't be necessary for article numbers to match their current ones.)  So I think it is probably fine to leave the numbers as they are.
