### ISSUE TITLE
adding editors

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#450]
1) All the editors to add are displaying in one long list, more-ore-less alphabetical (some weird Anonymour User accounts at the top, and lowercase/special letters after the Zs.) It might be nice if you could start typing your name instead of having to scroll past hundreds of others.

2) What does this actually do? I tried adding a few editors to a source, and it doesn't seem to display anywhere who has already been added as an editor.

**Comment by jacobdgm** [comment]
Where is this? I'm guessing that this is in the source edit page; In the Admin panel, there is such a searchable list:
![Screen Shot 2022-12-02 at 2 35 18 PM](https://user-images.githubusercontent.com/58090591/205373213-7e9a7fb9-b10c-4c43-9394-3ebd784816af.png)

If you add new "Current Editors" in the admin panel, I don't believe they visibly appear anywhere (if you add "Other editors", however, they should appear listed as indexers in the sidebar on the source detail page), but it should give that user access to modify the chants contained within the source (and perhaps the source description too, I can't remember off the top of my head). I think this difference is because any old user can be a "current editor", whereas "other editors" are meant to be indexers, with publicly visible user pages.

If you're indeed looking at the source edit page, I agree that it is weird that there are only two lists of users, "current editors" (which should contain all users) and "melodies entered by" (which should be indexer-specific). If this is in imitation of OldCantus, it's an odd design choice. I'm tempted to simply get rid of those fields, and perhaps provide a link to the admin panel....

**Comment by annamorphism** [comment]
Yes, I was looking at the source edit page (which doesn't seem to have "other editors" as an option.) In OldCantus there are lists of users and indexers for a great many possible roles, so it's strange that only two lists are available here; it's also strange that you have these two lists, but they don't seem to have any real function. Presumably the intent is to make it so a source creator can assign other people to work with them on something, but in that case they would probably want to know who is already assigned! Maybe the admin panel is a better solution...

Also, I thought indexers and users were being harmonized into the same role--am I missing something? Shouldn't both lists be the same?

**Comment by jacobdgm** [comment]
> Also, I thought indexers and users were being harmonized into the same role--am I missing something? Shouldn't both lists be the same?

So both Indexers and Users are now represented in the database as `User` objects, but that doesn't necessarily mean they have the same "role" (depending on what you mean by "role")...

As far as I recall, users can have edit access to a source, or proofread access to a source (or neither), and this is the key variable in dictating whether or not a user can access certain edit/proofread views for chants within that source.

Users also have lists of sources they have proofread/indexed/added melodies for/etc., which is only relevant if they are marked as an indexer. This affects which sources are displayed on a user's detail page (see, e.g. http://206.12.88.113/user/613#sources [This source list is only present on staging, and not currently on production]), but not who has access to which pages.

**Comment by annamorphism** [comment]
Ok, so when you say that the list for "Added melodies" should be indexer-specific, you mean it should only show the subset of users that have already been assigned edit access to that particular source?  Or should only list the 88 people currently under /indexers, as opposed to the 223 under /users?

**Comment by jacobdgm** [comment]
As far as I understand, any user can be added as an "added melodies"er for a source, whether or not they have edit/proofread access for it. We don't expect any non-indexer users to be added as "added melodies"ers for sources, but I think that if they were, it would show up on their user detail page as one of their "added melodies" sources. I think that in the side panel on Source Detail pages, only users who are indexers will be shown as having added melodies for the source.

That said, this is just my best guess as to what NewCantus currently does - all this goes to show that there's a fair bit of ambiguity between users-as-users and users-as-indexers. Maybe we should do some thinking as to how to clearly indicate these roles and what meanings these roles have (e.g. if a user is a "current editor" for a source, that means something meaningful for permissions, but if they're an "other editor" for a source, that's just an indicator that they did some indexerly work on a source but has no implications for permissions.) (Also, come to think of it, I have no idea what we currently do with granting-a-user-access-to-proofread-chants-in-a-source vs. this-is-an-indexer-who-did-proofreading-for-the-source...)

A good first step would be me going through the code, along with testing the site, to figure out exactly what's going on and to document it. This whole issue is a bit of a can of worms now that we're digging into it, and having things clearly described will be quite useful once people start interacting in earnest with user roles and indexer labels. I'll add this to my list of tasks for after the break.

**Comment by annamorphism** [comment]
This issue has also been mentioned by Debra, who writes: 
> "Not a huge issue at the moment, but is there an easy way for me to find my name in the list of "current editors"?
>
> I'm creating a new test source, and I'm assuming the list of "Current editors" is taken from anyone who has an account. Could it be alphabetical?
I suppose it's probably more work, but could it be one of those fields that completes as you type? (I start with "D", then "De" ... and it limits my choices as I go.)"

also:

> "Also in the "Create Source" (http://206.12.88.113/source-create/), we are missing some fields for authorship / editorship.
> 
> We need all of the "Inventoried by", "Full Texts Entered by", "Proofreaders", and "Other Editors" fields."

**Comment by annamorphism** [comment]
handling these cases via the admin panel rather than the source-create page is a possible solution to both the need to credit editors in certain roles and the need to search editors--though since I currently can't access this panel, I don't have a sense of how workable a solution it would be.
