### ISSUE TITLE
Chant create page - required fields should be clearly marked, and should match those of OldCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#453]
on #449:

> On the chant level, Folio and Sequence seem to be required fields (they are not on OldCantus!) but are not marked as such with asterisks, either.

So, Folio and Sequence should not be required fields. If it's intentional that these have been set as required fields, they should be marked with an asterisk on the chant create form, indicating this.

**Comment by jacobdgm** [comment]
@jwang44: was Folio and Sequence being set to required an instruction from Debra?

**Comment by jwang44** [comment]
Yes. We do need to make sure every chant (at least newly added ones) has a sequence number and folio. They are considered mandatory fields on the form.

We also have a mechanism in place:
Those two fields are automatically populated when you open a chant-create page. Their initial values are predicted based on the last chant in the source.
If, for whatever reason, those fields are empty when the form is submitted, they will be populated using the same initial values as mentioned above.
________________________________

**Comment by annamorphism** [comment]
-On the create form, these should have asterisks; currently they do not:
![image](https://user-images.githubusercontent.com/67451875/205401837-de4e0f43-55ca-4a2a-bd0f-649337d6e5c5.png)
-However, you cannot submit a form with these fields empty; if you delete the initial values, you get redirected to please fill these in (maybe there is a way to submit and have them auto-populate as in the second step of @jwang44 's mechanism, but I haven't found it). 
-On editing you can delete them, though! 
![image](https://user-images.githubusercontent.com/67451875/205402155-b6f74352-1bf4-468c-9241-86342d54f0fe.png)
http://206.12.88.113/chant/710913
-When I try to edit this chant and put a folio back in, it breaks things:
![image](https://user-images.githubusercontent.com/67451875/205402380-c5de70e3-338d-468b-83bc-9585fa9ce36a.png)

**Comment by jwang44** [comment]
OK. So it seems they are mandatory fields on the chant-create form, but not on the chant-edit form. This should be fixed. 

> -However, you cannot submit a form with these fields empty; if you delete the initial values, you get redirected to please fill these in (maybe there is a way to submit and have them auto-populate as in the second step of @jwang44 's mechanism, but I haven't found it).

Actually, I think this behaviour is better than populating the fields silently. I prefer blocking form submission if those fields are empty.

**Comment by jacobdgm** [comment]
> Those two fields are automatically populated when you open a chant-create page. Their initial values are predicted based on the last chant in the source.
> If, for whatever reason, those fields are empty when the form is submitted, they will be populated using the same initial values as mentioned above.

> Actually, I think this behaviour is better than populating the fields silently. I prefer blocking form submission if those fields are empty.

I agree - let's continue auto-populating the fields when the chant-create page loads, and prevent the user from submitting the form if the fields end up empty, rather than silently auto-populating them.

**Comment by annamorphism** [comment]
agreed all around!
