### ISSUE TITLE
sequence numbers not editable

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#455]
When investigating the folios and sequence fields for #453 , I found that sequence numbers populate automatically, which we want: 
![image](https://user-images.githubusercontent.com/67451875/205403386-f331ce32-c896-4737-8933-ac44236e9e45.png)

But if one tries to edit this to, say, sequence 102: 
![image](https://user-images.githubusercontent.com/67451875/205403443-b7dc1541-cede-432e-b331-160e6208a09e.png)

there is a success message, but the sequence number stays firmly at 100:
![image](https://user-images.githubusercontent.com/67451875/205403507-e8cdd413-f69b-4e0b-8677-c0084ed250db.png)

**Comment by jacobdgm** [comment]
As Anna already noted, this should automatically be resolved once #463 is fixed.

EDIT: actually, it will fix sequence numbers not being editable, but not sequence numbers being set automatically (a feature I think we should remove). We can be helpful and automatically provide an initial value on the form, but we shouldn't automatically set a sequence number if the user doesn't provide one.
