### ISSUE TITLE
Only sources from the Cantus Database segment should appear in the Browse Chants "Source" select element

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#458]
Jacob: EDITING this to put some conclusions, which otherwise would be buried in the discussion, near the top:

- Since sources from the Bower segment don't contain any chants, they _appear_ to be buggy when a user attempts to access them via the Browse Chants page (i.e. 0 chants are displayed)
- Thus, for the time being **we should not list sources from the Bower segment in the "Source" select element on the Browse Chants page.**
  - **Also, in the source navigation sidebar, for sources in the Bower segment, we should not display the "view all chants" link that currently links to the Browse Chants page** 
- At some point in the future, we may want to better harmonize how CantusDB handles/displays `Sequence`s (especially as compared to `Chant`s with a genre of "Sq" (i.e. "sequence"))

/jacob

When looking at chants in one source, you can also go to another via a drop down.  However, the dropdown displays all possible sources--including those in the Bower Sequence segment. If you choose one of those sequence sources, though, you end up seeing it has "0 chants", presumably because by default you are looking at "chants in this source in the Cantus DB segment". 
![image](https://user-images.githubusercontent.com/67451875/205420715-97f7805c-5932-4b1f-8ce3-59a986553b9c.png)
You can actually see this source just fine via  the Clavis Sequentiarum source list (http://206.12.88.113/source/124052) ; it's getting there from this dropdown that's a problem. http://206.12.88.113/chants/?source=124052&folio=&feast=&search_text=&genre=

This bug seems to also exist on OldCantus--it's just sufficiently weird that I never noticed it before. Still, either the Bower sources shouldn't be in the dropdown, or they need to correctly display their chants.

**Comment by jacobdgm** [comment]
One thought that comes to mind is that sources in the Bower segment don't have any chants, only a bunch of sequences.

**Comment by jacobdgm** [comment]
Which raises the question about which I've been wondering for a while - wouldn't it be more elegant to get rid of the Sequence model and turn all the sequences into chants? We could set them all to have a genre of "Sq", since we already have some bona fide Chants with that genre.

But I guess it's supposed to be a feature, rather than a bug, that the Clavis Sequentiarum is not particularly well-integrated with the rest of CantusDB.

**Comment by jacobdgm** [comment]
Right, so I guess we assume that only chants that are `Chant`s (and none that are `Sequence`s) are meant to show up on the `/chants/` page, and thus **the expected behavior is that only sources from the `CANTUS Database` segment should appear in the "Source" select element, correct?**

**Comment by annamorphism** [comment]
ah, you're right, a "chant" is not a "sequence", hence our problem.
I think you are right about the expected behaviour. If the /chants/ page only has Chants (which seems correct), then only sources from the Cantus Database segment should show up.

**Comment by annamorphism** [comment]
Also, it might indeed be nice to turn all the Sequences into Chants, true--except none of them have full texts...
It is a little odd, though, that they all already (in OldCantus) have a genre of "sequence", which you can click on to get a list of other sequences--but only those that are Chants, and not Sequences. I will consult about what we would actually like the behaviour to be.

**Comment by annamorphism** [comment]
just following up on this: yes, let's have only sources from the Cantus Database segment in the select element, so that users can't easily get to these apparently-blank source pages. 
Some day we will figure out how to integrate the Bower sources into this sort of browsing function, but that will take more forethought.

**Comment by jacobdgm** [comment]
Currently working on this. In the dropdown in question, I'm only listing sources in the Cantus segment. If someone tries to access the chant list page for a source not in the Cantus segment, I'm raising a 404 error.

As I was working on this, the thought occurred to me: @annamorphism, should we not be hiding the link to the search-within-a-manuscript page in addition to the link to the Browse Chants (i.e. Chant List) page? If someone tries to search for chants within a Bower source, should we raise a 404 error there, too?

**Comment by annamorphism** [comment]
Right now searching chants in a Bower source takes you to http://206.12.88.113/chant-search-ms/123930 which works just fine, no? Or did you mean another link from the one in the sidebar?

**Comment by jacobdgm** [comment]
ah, you're right - the /searchms/ page works just fine for manuscripts in both segments. Never mind (and thanks)!
