### ISSUE TITLE
search is broken on Clavis Sequentiarum/Bower segment?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#459]
A-Gu 17 (one of the Bower sources) claims to have no hits for "grates" even though the first things in it start with that word:
![image](https://user-images.githubusercontent.com/67451875/205421142-bf2672ec-eefb-46d5-a55e-2e6a15f00057.png)

![image](https://user-images.githubusercontent.com/67451875/205421128-7bfbaf81-fc13-42bc-84e1-9f9fe9d7a070.png)

In fact while "grates nunc" has quite a few hits in OldCantus (mostly from the Sequence DB)
![image](https://user-images.githubusercontent.com/67451875/205421160-f107bfc1-4d53-4f87-b2a7-4f73c2cddf37.png)

there are only 2 results in NewCantus
![image](https://user-images.githubusercontent.com/67451875/205421208-35b2d8eb-0f8b-471c-84be-277ddc3b5ce7.png)

I thought this had to do with the way search operates in the segment, but now am wondering if it is just a special case of #419 ...?

**Comment by jacobdgm** [comment]
Huh, I just came across this too while doing some testing. My guess is that it is only displaying Chant objects rather than Sequence objects. Must look into in further detail!

**Comment by jacobdgm** [comment]
I think this is fixed now? @annamorphism, do the links below demonstrate the issue has been fixed, or have I missed something?

general Chant Search page: http://206.12.88.113/chant-search/?op=starts_with&keyword=grates (223 results)

Chant Search MS page for A-Gu 17: http://206.12.88.113/chant-search-ms/124052?op=contains&keyword=grates (85 results)

**Comment by annamorphism** [comment]
whoa... now a search in the MS for "Grates" just returns everything in that source! (A-Gu 17 has 85 sequences...)
http://206.12.88.113/chant-search-ms/124052?op=contains&keyword=Grates&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/67451875/229918167-3ed032f2-6d3b-4e78-be97-3a5092e64ebb.png">

**Comment by annamorphism** [comment]
More experimentation with this sequence-heavy search:
New Cantus gives nothing at all for "grates nunc" through the search bar (using contains):
http://206.12.88.113/chant-search/?search_bar=grates+nunc
and everything in the DB for "starts with"!
http://206.12.88.113/chant-search/?op=starts_with&keyword=&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=

**Comment by jacobdgm** [comment]
> New Cantus gives nothing at all for "grates nunc" through the search bar (using contains):
http://206.12.88.113/chant-search/?search_bar=grates+nunc

This is bizarre. I tried http://206.12.88.113/chant-search/?search_bar=grates%20nunc as well (the `%20` encodes a space - I thought the `+` might be causing problems), and still no results.

> and everything in the DB for "starts with"!
http://206.12.88.113/chant-search/?op=starts_with&keyword=&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=

I think this is an artifact of the "keyword" field not being automatically filled in when a user does a `search_bar` search - note the `&keyword=<nothing>`. Guessing you selected "Starts With" in the StartsWith/Contains dropdown, and pressed "Apply" without copying the "grates nunc" into the "keyword" field.

**Comment by jacobdgm** [comment]
I'm not sure what changed in order to make this work properly, but I tried searching for "grates" and "grates nunc" on several pages on staging, and this seems to be fixed:
http://206.12.88.113/chant-search/?search_bar=grates
http://206.12.88.113/chant-search/?op=contains&keyword=grates&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=
http://206.12.88.113/chant-search-ms/124052?op=contains&keyword=grates&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=

http://206.12.88.113/chant-search-ms/124052?op=contains&keyword=grates+nunc&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=
http://206.12.88.113/chant-search/?op=contains&keyword=grates+nunc&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=

@annamorphism, can you do some poking around on staging and confirm we're good to close this?

**Comment by annamorphism** [comment]
Search_bar is not giving all the results it should be, since the Bower sources don't get returned. I think the issues with chant-search are resolved, though.

**Comment by jacobdgm** [comment]
This may be solved by #786 - assigning myself too, so I can check in on this early next week.

Edit: #786 does in fact seem to fix the problem. I'll ping annamorphism, once these changes are up on staging, for confirmation.

**Comment by jacobdgm** [comment]
Bower sources are returned via `search_bar=`, and also via `keyword=`. I think this is fixed. Closing, someone can re-open if not all is as it should be.
