### ISSUE TITLE
Chants should use `sequence_number`, but ChantEdit and ChantProofread views set chants' `sequence`

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#463]
Our `Chant` and `Sequence` models both inherit from `BaseChant`, so they both have a `sequence_number` field and a `sequence` field. `sequence_number` is supposed to be used only for `Chant`s, and `sequence` is supposed to be used only for `Sequence`s. The ChantCreate page properly sets chants' `sequence_number`, but the ChantEdit and ChantProofread pages set chants' `sequence` instead.

So, when a user loads a chant's Edit page, the `sequence` field is not populated, as the chant has a `sequence_number` but no `sequence`. When a user changes a `sequence` in the ChantEdit page and then visits the chant's Detail page, their edit will appear to have had no effect, since we don't ever try to display the chant's `sequence`.

**Comment by annamorphism** [comment]
whoa! this explains the issue I was having in #455 .
