### ISSUE TITLE
Turn off debug on production server

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#467]
Currently, if you navigate to an [erroneous page on production](http://206.12.88.113/source/12361012), you get a message saying "404" as well as a nice django debug page. We should ensure that this is turned off when we go to full production. This can probably happen as soon as we get logging set up (cf. #465).

Currently, we have the following code in `django/cantusdb_project/cantusdb/settings.py`:

```python
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.getenv("CANTUSDB_DEBUG", "False")))
```

I don't understand exactly what this is doing, but I gather there's an environment variable, `CANTUSDB_DEBUG`, whose value can be set in order to prevent the django debug page from being displayed.

**Comment by lucasmarchd01** [comment]
I suppose we could just manually set this to False by default on the production server and when we develop locally or on staging we can set this to True?

**Comment by jacobdgm** [comment]
While I don't know how to do this off the top of my head, I'm pretty sure it will not be difficult to do by changing the environment variable rather than by changing our code.

It's been helpful having error messages on "production" up until now, but now that we have the same version of Postgres running on both servers, now(-ish - it's not urgent) could be a good time to make this change.

**Comment by jacobdgm** [comment]
This is complete! I've also updated the relevant wiki pages with instructions for turning DEBUG on on staging and on a local setup.
