### ISSUE TITLE
On Chant Detail page, in the Source Navigation sidebar, indicate current chant

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#478]
Currently, on the chant detail page, there is a sidebar that lists the chants on the current folio as well as on nearby folios. In the sidebar, there is no indication of which chant is currently being displayed:
![Screen Shot 2022-12-15 at 1 19 53 PM](https://user-images.githubusercontent.com/58090591/207939496-fdcb9a9a-1fa2-4dc3-a447-7c0d89b771bf.png)

It might be helpful if we visually indicated somehow the chant that is currently being displayed.
Possible options:
1. Bold it
2. make it not be a link
3. add a little arrow pointing to the chant
4. a combination of 2. and 3., or maybe all three of the options above.

For example, here's a quick mockup of option 4:

![Screen Shot 2022-12-15 at 1 34 09 PM](https://user-images.githubusercontent.com/58090591/207940198-55b1d25e-f5f8-4bb7-af0a-9299d4d6c081.png)

**Comment by annamorphism** [comment]
I would like to enthusiastically endorse this enhancement!! Many are the times I have stared at the navigation menu, trying to work out WHICH chant is actually the immediately preceding one...
I think bolding it might look nicer than the little arrow (which suggests some sort of drop-down function to me) but I'm not sure.

**Comment by jacobdgm** [comment]
This is about to be fixed by #566!

Thinking about it a little more, the place where this would be particularly useful is not the Chant Detail page but the Chant Edit and Proofread pages. This will not be too difficult to set up, but it will not be trivial (as it was for the chant detail page).
