### ISSUE TITLE
Different results for the same query in Sources

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/CantusDB#48]
Results are different for the same query:

https://cantus.uwaterloo.ca/sources?segment=4063&search=US-CApc+&field_indexing_notes_value=&tid=All&century=All&tid_1=All

http://206.12.93.196/sources/?segment=4063&general=US-CApc+&indexing=&provenance=&century=&fullsource=

**Comment by jwang44** [comment]
Our implemented search rules are fine. This discrepancy in the search results is mainly caused by the difference in data. This should no longer happen after we update our data. That is, after we solve issue #49

**Comment by jwang44** [comment]
Fixed after data migration. The queries give the same results now.
