### ISSUE TITLE
On Search-By-Melody page, search results display "null" if chant is missing a field

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#482]
http://206.12.88.113/melody/:

![Screen Shot 2022-12-16 at 1 42 41 PM](https://user-images.githubusercontent.com/58090591/208167453-425ee7fd-bba3-408b-9ffc-80da28331fc0.png)

**Comment by annamorphism** [comment]
for completeness, the OldCantus alternative is to have a blank, which is indeed somewhat better:
![image](https://user-images.githubusercontent.com/67451875/208211077-71c22cc5-fdc5-4602-8c92-7cd8f0dc91a2.png)

In most cases proofread sources _should_ have something in both those fields--not sure why this one doesn't, but it should be a comparatively rare occurrence.
