### ISSUE TITLE
Source Edit Page: sidebar: dropdown elements don't work

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#483]
On the Edit Source page on OldCantus, you can see "» View all chants   » View full index   » CSV export" etc. You can't select a folio or a feast:

https://cantus.uwaterloo.ca/node/711311/edit:
![Screen Shot 2022-12-16 at 2 23 09 PM](https://user-images.githubusercontent.com/58090591/208173403-56dcb32a-ec87-4639-88cf-d9bbc74dc192.png)

On the Edit Source page on NewCantus, you can't see the useful links - only the folio and feast selectors (which are just as useless as in OldCantus)

http://206.12.88.113/edit-source/123653:
![Screen Shot 2022-12-16 at 2 23 47 PM](https://user-images.githubusercontent.com/58090591/208173695-676814b9-4306-4ffc-b187-ab8f9f624914.png)

**Comment by annamorphism** [comment]
I'm confused--I don't think the selectors are useless on OldCantus:

![image](https://user-images.githubusercontent.com/67451875/208210249-a467cb09-ce2b-42f3-a75a-4b248dafd152.png)
![image](https://user-images.githubusercontent.com/67451875/208210314-89f5d6b2-956c-44bb-81a2-d7608738f465.png)

Agreed that the NewCantus version isn't right, though!

**Comment by jacobdgm** [comment]
Ah. Maybe the perceived uselessness of the selector in OldCantus is an artifact of chants being added at random to the particular test source I was looking at.

So the sidebar should work just as it does on chant-detail pages. I'll look into this in a bit more detail and try to get this set up properly once I finish my Christmas/etc. break.

**Comment by jacobdgm** [comment]
Further detail: On OldCantus, when you select the element from the dropdown, it brings you the relevant Browse Chants page.

I split #781 off from this issue, as they're really two separate things. Renaming this one to focus on the dropdown.

We just need to copy this from the Source Detail view. This has already been done in the template, but the necessary code has not been added in the view. This should not be a particularly difficult fix.

Not important for the soft launch, but we need to fix it by the time people are expecting to edit things in NewCantus.
