### ISSUE TITLE
We need to create Delete Views for Source, Sequence and Chant

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#486]
Conclusions from the comments below:
> we should add source-delete, chant-delete and sequence-delete views. People should not see links to these views, and be blocked from accessing these views, unless they are a `project manager`, or if the source/chant/sequence in question was `created_by` the current user.

Original post:
While investigating #481 I checked out how deleting items works in OldCantus for mere "contributors". It seems they can currently delete any chants OR sources that they created themselves, which corresponds to those items that they have edit access for. Basically if  https://cantusdatabase.org/node/711349/edit is available to them (not 403), then https://cantusdatabase.org/node/711349/delete gives the option of deleting it, and if not then not. (Haven't checked yet if this also holds for "editors", "proofreaders" etc but I don't know why it wouldn't.)
<img width="792" alt="image" src="https://user-images.githubusercontent.com/67451875/208976160-6558fffd-96d7-49ce-ae31-747e4a516938.png">

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/67451875/208976107-bb3ab673-1686-4270-821f-f94ba9be93e3.png">

It seems like in NewCantus the equivalent option to delete chants is done through chant-delete, but there is no equivalent for deleting sources. Wondering if that is intentional. 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/67451875/208976738-71ffd22e-efff-4171-bdaa-557a4cd441d1.png">

**Comment by jacobdgm** [comment]
Whoa - I've never seen the "Delete" button on OldCantus. Jiwoo set up a chant delete page last summer, which was just for ease of testing as far as I know (It's set to be removed by #481), but evidently it may be worth keeping it around after all. We'd also need a source-delete and a sequence-delete page, yes?

**Comment by annamorphism** [comment]
I didn't check sequences (since the Bower database is basically fixed and not added to), but yes, both sources and chants are delete-able.

**Comment by jacobdgm** [comment]
Right re: sequences - we do have an Sequence Edit page, presumably for making quick corrections in case of discovered typos etc., but if we need to make drastic changes like deleting a sequence, we can do it in the admin panel.

**Comment by jacobdgm** [comment]
#481 has been booting around for long enough - we should figure out what we want to do with this, one way or another.

First option: we add a delete button to all Model Edit pages. This way, if you have access to edit a thing, you have access to delete it. We would also add simple pages for the user to confirm they actually want to delete the thing.

Second option: we get rid of the delete button on the Chant Edit page, and get rid of the Chant Delete page (i.e. the "are you sure you want to delete this chant?" page). If/when a thing needs to be deleted, an administrator can do it via the admin panel.

Additional options: (are there more options?)

The second option is probably safer - there are fewer possibilities of us accidentally giving delete access to users that shouldn't have it. But this could also make more work for the Debras in the world.

@annamorphism, do you have a sense of what path we should take? Worth checking in with Debra?

**Comment by annamorphism** [comment]
I would check in--my gut is to do the first option, because it is closer to what OldCantus does, and because I think it would be frustrating for contributors never to be able to delete things like accidentally duplicated entries or whatever. I think anybody who can be trusted with creating chants in a source can be trusted with deleting them.

Source-delete is maybe trickier, since it has the potential to delete many things at once. I think it should still follow the same protocol as chant-delete, for the same reasons, but Debra might disagree...

**Comment by annamorphism** [comment]
From Debra: 

> Delete buttons
> 
> No to sources for anyone except Admin (i.e. Proofreaders as well as people like me, Anna, or Alessandra).
> 
> Yes to chants for the person who is creating the index. I don't want to have to go into their inventories and delete their mistakes for them. (I did that for a while at the start of OldCantus and it was quite confusing for me - and the creators.)
> 
> QUESTION - Do I still get to limit the sources that each "editor" can see/edit? In OldCantus, someone with editor permission still had to have the sources opened up for them. Otherwise, they couldn't get at the records.  If this is still the case, then I think it's safe enough to have a delete button at the chant level. They can fix wrong entries. ALSO - can it have an "ARE YOU SURE?" safety response?

**Comment by jacobdgm** [comment]
I should be able to add a delete button for the Source Edit page, visible only to people in the "editor" and "project manager" groups, but not to people just in the "contributor" group.

We can reinstate the delete button for the Chant Edit page, but have it visible only to "project manager"s, "editor"s, and to the person who created the source.

(@annamorphism, do my permissions specifications in the previous two paragraphs sound correct?) 

We already had an "are you sure?" page for chants, so I'll ensure that's there for both Chants and Sources.

**Comment by annamorphism** [comment]
I think if what Debra is calling Proofreaders (these are Editors, yes?) can delete whole sources, they should also be able to delete chants. Other than that I think this matches the specifications.

**Comment by jacobdgm** [comment]
> I think if what Debra is calling Proofreaders (these are Editors, yes?) can delete whole sources, they should also be able to delete chants. Other than that I think this matches the specifications.

Good - i updated my comment. Thanks!

**Comment by dchiller** [comment]
FYI: in #804 I noted that in OldCantus I can delete sources I myself created. If that is no longer going to be possible per the instructions noted about by Debra, that should be added to the list of known and intentional differences between Old and New Cantus.

**Comment by annamorphism** [comment]
I have emailed to confirm whether this is an intentional change to be recorded or not. Will update on response.

**Comment by annamorphism** [comment]
Update: yes, people should be allowed to delete their own created sources.

From Debra:
" Ok then, let's let Contributors delete their own things. 🙂

Only upper admin can delete other people's things though. This should be what it was on OldCantus. I'm not sure I had ever thought of people deleting entire sources, but for testing this makes sense."

**Comment by jacobdgm** [comment]
Just to confirm: we should add source-delete, chant-delete and sequence-delete views. People should not see links to these views, and be blocked from accessing these views, unless they are a `project manager`, or if the source/chant/sequence in question was `created_by` the current user.

@annamorphism is this correct? There are no other objects (feasts, indexers, etc.) which should have delete pages, yes? If the description above is accurate, I'll rename this issue and update the initial comment to reflect this.

**Comment by annamorphism** [comment]
I think this is basically correct. On inspection it turns out that admins can also edit (and hence delete) certain flatpages (e.g. https://cantus.uwaterloo.ca/node/664923/edit)  but if we are moving to access these via the admin panel I assume it doesn't need to be replicated. 
![image](https://github.com/DDMAL/CantusDB/assets/67451875/36fbaf62-7f7d-423d-9e36-5dd8fc46ac76)

So yes, we want this view to only be accessible to project managers or the creator of the node in question, and we want them for chants, sequences, and sources.

**Comment by jacobdgm** [comment]
We now have chant delete and source delete pages, via #951

Since contributors have no way of creating new sequences, I think it makes most sense to handle the deletion of sequences in the Admin area.

So, I think we have all the delete pages we need. Going to close this issue; if we really do need a sequence-delete page, someone please reopen this.
