### ISSUE TITLE
"View full index" is out of order

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#488]
When you look at the full index (e.g. http://206.12.88.113/index/?source=123611 ) the chants should be in the order they are in the manuscript, but they are not (as can be seen by their sequence numbers):

<img width="581" alt="image" src="https://user-images.githubusercontent.com/67451875/209037324-f464e429-ed25-4a82-ad10-a1c2cdb003b0.png">

**Comment by jacobdgm** [comment]
This was fixed by #411, and the staging server is now running the updated code! Good catch; I'll try to update the staging server more often in the future ^^
