### ISSUE TITLE
broken edit forms for empty sources

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#489]
If one tries to access either the volpiano or the proofreading form for an empty source e.g. http://206.12.88.113/proofread-chant/710076, one is met with a grey screen of sadness. On OldCantus  https://cantus.uwaterloo.ca/edit-volpiano/710076 gives the explanation page about editing instead.

**Comment by jacobdgm** [comment]
We should avoid showing users django debug screens, yes! This is not urgent, since http://206.12.88.113/chant-create/710076 still works.
