### ISSUE TITLE
"contributor" in source sidebar is empty

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#490]
On OldCantus the sidebar for a source tells you the various credited indexers, but also the person who created the source (as "contributor".)  On NewCantus this "contributor:" slot just seems to be empty:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/67451875/209039245-2f066ceb-0193-4bf7-80d1-cce6d6315cc8.png">

Seems to me it would be useful to keep the author information for the source, and if anything add the other current editors as well (which don't show up here in OldCantus). Or one could get rid of "contributor:" if it's just going to be empty anyway.

**Comment by jacobdgm** [comment]
Probably, the way to approach this is to automatically assign a user as a Contributor indexer for a source when they create it, similar to what we'll probably do with proofreader status (see #491).

**Comment by jacobdgm** [comment]
This is the same issue as #737. Closing.
