### ISSUE TITLE
Chant Index page: folios without leading zeroes sorted out of order

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#496]
http://206.12.88.113/index/?source=123931

![Screen Shot 2023-01-09 at 3 50 29 PM](https://user-images.githubusercontent.com/58090591/211405778-25a10024-bd1c-4ae9-bcdd-e63e21b7b98b.png)

**Comment by jacobdgm** [comment]
I tried fixing this simply (but would have caused querying to be slow) by adding a `padded_folio` property to the base_chant model, but it didn't interact nicely with whatever Django does behind the scenes with Postgres. I could add a `padded_folio` field that's kept up-to-date in `signals.py`, but I wonder whether there's a simpler way.

**Comment by annamorphism** [comment]
Can you sort them by the Bower-specific "sequence number"? I am pretty sure it would bring them in order, and while it's inelegant that it doesn't work the way it does in the rest of the DB, it's inelegant anyway that these sources don't follow Cantus protocol.

**Comment by annamorphism** [comment]
not sure why they DO order correctly on the source page. maybe worth looking into. 
![image](https://user-images.githubusercontent.com/67451875/211435826-0fb9bc0c-809c-46b5-8475-f8f25a16284e.png)

**Comment by jacobdgm** [comment]
Hm... on the source detail page of sources in the Bower segment, sequences are ordered by `s_sequence` (i.e. Calvin Bower's "sequence number).

I think this would be worth implementing if/when we implement #495. I'll leave a note there mentioning this.

**Comment by jacobdgm** [comment]
As noted by @ahankinson on [#583](https://github.com/DDMAL/CantusDB/issues/583#issuecomment-1469866981), Postgres has a feature that allows "natural sorting" - we could perhaps use this

**Comment by jacobdgm** [comment]
Looking at the source linked here, and a handful of other sources, this appears to be fixed. It's not a problem for pages in the CantusDB segment, and pages in the Bower segment are now properly ordered by `s_sequence` (ignoring `folio`)

@annamorphism, would you be able to sample some index/inventory pages and close this if you agree it's been resolved?

**Comment by annamorphism** [comment]
This looks solved, and even takes care of some oddities OldCantus didn't handle well, like roman numerals (!) in the folio field https://cantus.uwaterloo.ca/index?source=123997
<img width="781" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/fe7539a9-7556-4d05-977a-cee343eee6c5">. Closing.
