### ISSUE TITLE
Chant Proofread page, in sidebar: replace "EDIT" with "PFRD" or something

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#501]
It is currently not very obvious when one is editing a chant versus when one is proofreading the chant. On the Proofread Chant page, other than the URL, there's only a line of normally-sized text stating that one is proofreading that specific chant.

On the Chant Proofread page, in the sidebar, we currently display the same table as on the Chant Edit page, including an "EDIT" link. While one can technically edit the chant on the proofread page, the main point of the page is that one can check the "proofread" checkboxes. We should replace "EDIT" with something indicating that the user would not just be editing the chant.  This would also help differentiate the Edit and Proofread pages.

The challenge - finding something that fits in the tiny column! "PRF"? "PROOF"? "PRFRD"? "PFRD"?

Or maybe "EDIT" is close enough, and it's not worth trying to change it?

**Comment by annamorphism** [comment]
maybe there could be a non-text solution, like the background is pale blue instead of white...

**Comment by jacobdgm** [comment]
With #1047, we no longer have a Chant Proofread page. Closing.
