### ISSUE TITLE
OldCantus displays preview of melody with text on Chant Editing pages

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#507]
visible on https://cantus.uwaterloo.ca/edit-volpiano/699578 (our Source Edit Chants page) https://cantus.uwaterloo.ca/node/702097/edit (our Edit Chant page), beneath Indexing Notes.

For some reason we don't have this implemented yet.

**Comment by annamorphism** [comment]
Should be on proofread forms as well as edit ones. 
![image](https://user-images.githubusercontent.com/67451875/211885342-c0e51480-c245-4c83-975e-b3dc11e41714.png)
![image](https://user-images.githubusercontent.com/67451875/211885452-270f42f4-5dc0-4c88-bf65-b0a5fad542f7.png)
