### ISSUE TITLE
Internal string representations of objects shown in Office, Genre dropdowns on chant-edit, source-edit-chants pages

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#512]
found on http://206.12.88.113/edit-chants/123610?pk=243158&folio=001v

![Screen Shot 2023-01-11 at 13 18 15](https://user-images.githubusercontent.com/58090591/211886262-5dd19131-d819-4be1-b5cb-47825fed2228.png)

**Comment by annamorphism** [comment]
not clear to me what the problem is--are you saying these should be V and A and not "[V] First Vespers"?

**Comment by jacobdgm** [comment]
Basically, yes.

The issue is that every model in our app has a defined string representation, which is mostly used to unambiguously identify objects for the admin panel, development/debugging, etc. If ever in the future we decide to rework some feature having to do with offices or genres, it might be useful to have offices' IDs, say, displayed while interacting with them in the django shell. These are only really meant to be used internally, but tweaking the string representation would have the unintended side effect of changing what's displayed in the dropdown on this page.

The dropdowns can include the full-spelled out versions "first vespers" and "antiphon", sure. The point is that we should decide what we want to be be displayed in the dropdowns, and explicitly set it, to prevent unintended side effects.

**Comment by jacobdgm** [comment]
cf. #699, on Chant Create page
