### ISSUE TITLE
search seems...slow

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#513]
On OldCantus, a simple one-word search in the home-page search box for e.g. "Jerusalem" gives results in probably about a second (haven't taken out the stopwatch). On NewCantus I can count to 15 or 20 while doing so. 

Some of this is probably that NewCantus gives more results (4026 chants containing "Jerusalem" and not just the 629 starting with it), but I don't think it's worth it if it's going to take an order of magnitude longer....

**Comment by jacobdgm** [comment]
Okay - so the difference here is between incipit search and full text search. OldCantus has an incipit search and a fulltext search, whereas NewCantus only has fulltext search.

![Screen Shot 2023-01-12 at 11 03 04 AM](https://user-images.githubusercontent.com/58090591/212117890-8fac2744-c4fb-4039-ae7c-33ec7b57a4c4.png)
![Screen Shot 2023-01-12 at 11 02 51 AM](https://user-images.githubusercontent.com/58090591/212117795-498f4dbb-0ee2-4605-9f9b-a1cb383e6e12.png)

When you use the search bar, or when you initially navigate to the Chant Search page on OldCantus, it defaults to the incipit search, which is a lot faster.

If you use the fulltext search, OldCantus is about half as fast as NewCantus: searching for "Jerusalem" and counting in my head, I found that OldCantus takes about 13 seconds to return results, whereas NewCantus takes 6 or 7 seconds.

Though we didn't definitively decide to not implement incipit search, my understanding is that we're trying to not have as wide a variety of different search pages as OldCantus does. But maybe it's time to revisit #421, and add a "search incipits only" option to the search page that's selected by default.

**Comment by annamorphism** [comment]
I collected a little data for this with a stopwatch:

On OldCantus, incipit search:
"Jerusalem": less than a second (essentially, my own reaction time)
"Jerusalem respice": maybe more like a second; took a little longer the second time
"Dum": similar to above
"Dum transisset": under half a second


Equivalent searches on full-texts (which is also "contains" and not "begins with") are a lot slower--basically a consistent twelve seconds:
"Jerusalem": 12.44 seconds
"Jerusalem respice": 12.56 seconds
"Dum": 12.88
"Dum transisset": 12.28
"Dum transisset sabbatum maria magdalena": 11.97

So, on OldCantus, fulltext is a LOT slower than incipit search, and the length of the search term doesn't affect it much. (I didn't do repeat trials in this case, because the search clearly gets cached and reappears instantly the second time round.)

Note that these times are also from when I hit "Enter"--I think the incipit search starts searching when you type, while the full text waits for a command, so that affects perceived time a lot too.

For comparison:
On http://206.12.88.113:
"Jerusalem": 5.82 seconds
"Jerusalem respice": 13.25
"Jerusalem respice ad" 9.85
"Dum": 5.6
"Dum transisset": 6.4
"Dum transisset sabbatum" 7.8

So this is noticeably faster than OldCantus's full text search (except in one case) but quite a lot slower than the incipit search. 

I also, for fun, tried the same terms on Cantus Index--which also does a full text search by default (though it has fewer texts to search). There, results come in in about a second. 
Cantus Ultimus searches as you type, and had the complete list of results within a fraction of a second of finishing typing the term. 
So that gives a benchmark for what users are going to expect/notice. It does seem like there is something flat out buggy about the search (possibly carried over from OldCantus's full-text search) that makes things perform below expectations.

**Comment by annamorphism** [comment]
also it's possible it's just chance, but I do seem to consistently get fractionally better results on http://206.12.93.196 than http://206.12.88.113. But it's the difference from 8 seconds to 6, and not 8 to .8.

**Comment by annamorphism** [comment]
also, something a little weird that might be related:
On OldCantus, you start getting a dropdown of results before hitting enter, like so:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/67451875/213817356-fae22d9c-259e-4ca8-b987-00f649297f92.png">
On NewCantus, this seems to only happen some of the time--in fact I thought it simply didn't have this feature, but then I managed to get it to appear on one search. 
Subsequently I changed what I was actually writing in the search bar, but the old results stayed:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/67451875/213817237-cf9fc9ef-397c-4bc3-b428-244ed711d64b.png">

It may be that this is a separate issue about search bar behaviour, but I mention it here in case this apparently difficulty starting up new searches/switching from a previous search to a new one is part of the issue.

**Comment by annamorphism** [comment]
Hmm..when I tried to replicate the above a second time I got a 504 error.
Then searching "mysterium"again on my newly refreshed tab gave the expected dropdown (as I typed):

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/67451875/213818565-01062bfb-c13e-489c-83c3-ba077a542d66.png">

but after I deleted it and wrote a new word it ceased to exist. A second typing of "Mysterium" gives nothing, but the spinny wheel spins, and then...another 504.  Another attempt at "mysterium"--no dropdown, no spinny wheel until I press enter, and then--504. 
A mysterium to be looked into.

**Comment by fujinaga** [comment]
> also it's possible it's just chance, but I do seem to consistently get fractionally better results on http://206.12.93.196 than http://206.12.88.113. But it's the difference from 8 seconds to 6, and not 8 to .8.

This make sense because .196 is a production server and it is likely that it has a larger (faster) machine (instance) assigned to it than the staging server (.113).

**Comment by jacobdgm** [comment]
> Hmm..when I tried to replicate the above a second time I got a 504 error.

i.e. when you typed your search term in the search bar and pressed enter, it showed you a 504 error when it tried to load the Chant Search page?

**Comment by annamorphism** [comment]
> > Hmm..when I tried to replicate the above a second time I got a 504 error.
> 
> i.e. when you typed your search term in the search bar and pressed enter, it showed you a 504 error when it tried to load the Chant Search page?

Yes--for whatever reason I can get a 504 error fairly often if I first set up the type-delete-type conditions that cause the dynamic search to go buggy as in #527 , and then press enter. (not every time--maybe every third or fourth attempt?)

**Comment by annamorphism** [comment]
one can also get an error pretty consistently by leaving the search blank and hitting enter. Usually 504, sometimes 502 for variety...

**Comment by jacobdgm** [comment]
Okay, either I'm going crazy, or there's something going wrong with the Compute Canada servers (or possibly both?). When I `git checkout` the `staging` branch locally and search for "jerusalem" on the chant search page, I get results in <2 seconds. When I try it on [staging](http://206.12.88.113/), it takes 5-6 seconds. I checked `git log` in both places, and I have the same latest commit locally as on the staging server. The same number of chants are returned. I tried rebuilding my docker container locally, and I'm still seeing the same results. I'm baffled.

**Comment by jacobdgm** [comment]
Trying this now, search-bar searches for "jerusalem", "mysterium", and "" are all returning results in <2s currently, on Production. I think this is basically fixed. Closing.

(Curiously, "willibaldus" takes quite a long time to return no results)
