### ISSUE TITLE
search chant results should order by RISM siglum

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#514]
Currently search results are in a strange order loosely associated with the city the source is in, as in Aberystwyth-Arras-Aosta (why is this after Arras?)-Assisi, and a strange interloping London source that also goes by "Augsburg"

![image](https://user-images.githubusercontent.com/67451875/211892851-82f7ed3d-28e4-49e9-9804-e3d1c216b865.png)

This is different from OldCantus, which (as far as I know) alphabetizes by RISM siglum, which means one gets all the A-for-Austria sources together and all the B-for-Belgium sources etc. 
![image](https://user-images.githubusercontent.com/67451875/211893543-575a7741-f3a4-434f-a813-c8cb1979fbd1.png)

**Comment by annamorphism** [comment]
Should have been more specific--this is true for search_bar searches (http://206.12.88.113/chant-search/?search_bar=urbis), not for keyword searches. And if I try to order the columns of search_bar searches (perhaps to compare the results to keyword ones...) I get a 502 error.

**Comment by jacobdgm** [comment]
With the ordering of columns generating a 502 error, I think this amounts to a bug. Assigning a priority of medium

**Comment by annamorphism** [comment]
On production this doesn't seem to order at all. http://206.12.93.196/chant-search/?search_bar=deo&page=1
<img width="1086" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/fa6bf1f6-e79d-4fa0-9ed1-493520475c22">
When one tries to order by column header, the search term is lost, and you get an ordered list of all chants (http://206.12.93.196/chant-search/?&order=siglum&sort=asc)
<img width="1129" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/4eac2c38-9b4d-4a96-8947-7d3da529beed">

**Comment by jacobdgm** [comment]
> When one tries to order by column header, the search term is lost, and you get an ordered list of all chants (http://206.12.93.196/chant-search/?&order=siglum&sort=asc)

Ah! The links in the column headers account for all the fields on the main form, but they don't make any effort to preserve the text in the global search bar.
