### ISSUE TITLE
Cantus discrepancies

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#52]
The word "Israel" is divided into two syllables on the Cantus DB, so "Is-rael." However, when it shows up in the Salzinnes manuscript, it always clearly has three neumes associated to it, as in the examples below (from folios 028r, 028v, and 030r):
<img width="162" alt="Israel 028r" src="https://user-images.githubusercontent.com/83373378/118818972-e6100180-b882-11eb-85cd-86b5072b74aa.png">
<img width="163" alt="Israel 028v" src="https://user-images.githubusercontent.com/83373378/118818992-ea3c1f00-b882-11eb-98e3-b9e55865e039.png">
<img width="263" alt="Israel 030r" src="https://user-images.githubusercontent.com/83373378/118819015-ef00d300-b882-11eb-83d2-e85b8dab9ef2.png">
I can't confirm for the Latin, but I know that in French the word is divided into three syllables "Is-ra-el."

**Comment by napulen** [comment]
Same for Spanish: `Is-ra-el`.

**Comment by jwang44** [comment]
Could you post a link to where this syllabification issue is happening? I guess it's somewhere on the old Cantus, i.e., [cantus.uwaterloo.ca](http://cantus.uwaterloo.ca/)?

**Comment by fujinaga** [comment]
Don’t worry about this. I’ve asked Alessandra.

On May 19, 2021, at 10:08, Junhao Wang ***@***.***> wrote:

﻿

Could you post a link to where this syllabification issue is happening? I guess it's somewhere on the old Cantus, i.e., cantus.uwaterloo.ca<http://cantus.uwaterloo.ca/>?

**Comment by JoyfulGen** [comment]
Cantus links (sorry for the delay):
028r: https://cantus.uwaterloo.ca/chant/270414
028v: https://cantus.uwaterloo.ca/chant/270421
030r: https://cantus.uwaterloo.ca/chant/270432

**Comment by carrieeex** [comment]
In the word "iherosoliman", "ihe" is divided into two syllables on the Cantus DB as "i-he"; however, when it shows up in the Salzinnes manuscript, it only has one neume associated with it, which results in one syllable missing in Cantus DB in the "Meloday with text section", as in the examples below (from folios 048v):
image of 048v line 1:
<img width="463" alt="048v ihe in manuscript line 1" src="https://user-images.githubusercontent.com/59303880/119466363-1e2dad80-bd77-11eb-9da6-3661429c7ed0.png">
[Cantus DB 048r](https://cantus.uwaterloo.ca/chant/270696):
<img width="804" alt="048v ihe in CantusDB 048r" src="https://user-images.githubusercontent.com/59303880/119466365-1f5eda80-bd77-11eb-863b-67c7a6459dd5.png">

image of 048v line 7:
<img width="449" alt="048v ihe in manuscript line 7" src="https://user-images.githubusercontent.com/59303880/119467684-541f6180-bd78-11eb-8933-6c76c9bb9641.png">
[Cantus DB 048v](https://cantus.uwaterloo.ca/chant/270697):
<img width="809" alt="048v ihe in CantusDB line 7" src="https://user-images.githubusercontent.com/59303880/119468089-b710f880-bd78-11eb-8352-3b75d0525fcc.png">

**Comment by carrieeex** [comment]
In the word "dixerit", "xerit" is missing a letter "i" in [Cantus DB](https://cantus.uwaterloo.ca/chant/271108) for Salzinnes folio 076r:
The manuscript of 076r:
<img width="1050" alt="076r manuscript dixerit" src="https://user-images.githubusercontent.com/59303880/119651159-48569c80-be57-11eb-846f-e09c371c5684.png">
and in Cantus DB:
> Manuscript Reading Full Text (standardized spelling): 
>Igitur puella cui dixero da mihi aquam de hydria tua ut bibam et illa **dixerit** bibe domine et camelis tuis potum tribuam ipsa est quam praeparasti domine filio domini mei
>Manuscript Reading Full Text (MS spelling): 
>Igitur puella cui dixero da michi aquam de ydria tua ut bibam et illa **_dixert_** bibe domine et camelis tuis potum tribuam ipsa est quam preparasti domine filio domini mei | Tu
<img width="547" alt="076r CantusDB missing a letter in dixerit" src="https://user-images.githubusercontent.com/59303880/119651431-966ba000-be57-11eb-9fa5-0170a2441c8a.png">

**Comment by fujinaga** [comment]
For any discrepancies between the Rodan workflow output and the Volpiano in Cantus DB, please note the manuscript name, the folio number, the chant name (incipit), and the text, where there's the discrepancy. I suggest that you create a Google Sheet so that all the testers can share and enter this data.   Keep the MEI as you think is the correct interpretation. (The syllabification in the Volpiano in Cantus DB is performed with an algorithm, which can result in errors.) You do not need to create an issue for every discrepancy, unless the discrepancy is unusual.

**Comment by JoyfulGen** [comment]
Here's the link for the Google sheet, where testers can add further discrepancies if and when they show up:
https://docs.google.com/spreadsheets/d/133lVOVM15l7a6bQKIQije4op363ragG4OXewYop_cbQ/edit?usp=sharing
