### ISSUE TITLE
chants on chant search page out of order

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#524]
yes, it's a source to which chants have been added haphazardly, however it's not clear as to why 004r should be before 001r on http://206.12.88.113/chants/?source=699578 ...

![Screen Shot 2023-01-13 at 10 51 43 AM](https://user-images.githubusercontent.com/58090591/212361890-7459dc3e-adfc-4b41-8764-18b5efe2dd44.png)

**Comment by jacobdgm** [comment]
on the same page, it would also be worth looking into where the siglum is coming from, as the chant I just created doesn't have one...
![Screen Shot 2023-01-13 at 10 53 42 AM](https://user-images.githubusercontent.com/58090591/212362290-71e38b7a-4732-43b9-a9b5-258843615143.png)

**Comment by annamorphism** [comment]
interesting. It's doing the same for me, but this seems to be a new development. Must be something caused by a recent change.
![image](https://user-images.githubusercontent.com/67451875/212366517-1eb38e11-ba70-483e-b880-63db212c5e05.png)

**Comment by annamorphism** [comment]
and, as pointed out up top, the chants seems to show up in the order added, not by folio 
![image](https://user-images.githubusercontent.com/67451875/212367256-c09ec327-75e9-49ed-90f7-44100631dcc6.png)
The "Full index" has them correctly ordered--not a case of an invisible leading zero or something.
![image](https://user-images.githubusercontent.com/67451875/212367403-79d418aa-90af-4da1-9350-69b617a73eb1.png)
