### ISSUE TITLE
Search bar is buggy

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#527]
as noted by Anna on #513, the search bar sometimes behaves erratically. In exploring this, I've noticed that it tends to happen when a user types one search term, deletes it, and then begins to type another search term. Sometimes, the results preview fails to update when the search term is changed, continuing to display results for the previous search term. Sometimes, results will continue to be displayed even when the search bar is empty.

This is slightly related to #516, where we'd expect the Keyword Search or Cantus ID field to be automatically populated when a user arrives at the chant search page via a search in the search bar, and the ordering of search results doesn't work when there's a `&search_bar=` in the url rather than a `&keyword=`.

**Comment by jacobdgm** [comment]
further to this: typing part of a Cantus ID causes results to display below the search bar, but the Chant Search page only turns up results if an entire Cantus ID was entered.

**Comment by annamorphism** [comment]
There's also this, where the dynamic search seems to be giving either fuzzy results, or ones based on only the first few characters (the actual search for this non-word gives no results):

![image](https://user-images.githubusercontent.com/67451875/214399660-a6b8d658-3ad6-488c-bf1c-1998d35012d2.png)

**Comment by annamorphism** [comment]
Possible further clue:
Some words seem to be more problematic than others. For example, no chant begins with "Willibaldus" (though a few contain this word/name) and generally speaking it will have no displayed results as you type, and often lead to a gateway error after hitting enter.  
More typical words (like "mysterium") don't do this unless they have been "primed" by previously searching, or failing to search, a term like "willibaldus".

**Comment by annamorphism** [comment]
It also takes a notably long time to get the results to change from one very common term (like "et") to another ("etiam")--it happens, but it takes a while. Getting back to "et" from "etiam" is much faster. 

Rarer search terms behave even more poorly in terms of displaying this list of results (before hitting enter).
Typing (comparatively uncommon) "W" takes seven seconds before anything displays. It then takes another 11 seconds to refine this list after typing an "i". Another fifteen to add on an "l". Trying to weed "Willibald" out by typing "willibr"(adding four letters on one occasion took 53 (!) more seconds.

**Comment by annamorphism** [comment]
you can also make good searches turn worse! "Mysterium" starts off a nice happy word in the search bar,  where the results (the displayed results that drop down, not those of the search) take maybe a second or two. Then searching "wil" takes thirty seconds...and now "mysterium" takes more like 10 seconds. Then "Wil" still takes thirty seconds, but now "mysterium" takes almost twenty seconds, and that seems to be the plateau for both words.
(Searched directly on the chant-search page they don't seem to do this--sort of a consistent 5-6 seconds.)
So things that worked before can get gunked up by previous searches (and this, in turn, seems to affect later error rates--stuff for which the dropdown lists aren't retrieved before the user starts doing other things seem to lead to errors after pressing enter, or to make future searches not display after deleting the offending word.)

**Comment by jacobdgm** [comment]
In #946, we made changes to the search bar to make it return more logical results.

The fact that the search bar is sluggish has been noted in #979, which remains open.

So, I think this issue is more-or-less dealt with. Going to close it; if problems still remain, someone can reopen this issue or create a new one for the specific problem.
