### ISSUE TITLE
Meta-issue: Make Chant Search better

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#540]
I'm creating this meta-issue as I'm losing track of all our numerous search-related issues.

Some of the things that have been noted:
- OldCantus defaults to searching only chants' incipits, whereas NewCantus defaults to searching both full-text fields. It's been decided that we won't try to emulate this behavior, and instead focus on making full-text search quick. Relevant discussion occurred in #519 and #513.
- Somewhat related, different results appear when one searches via the search bar at the top of each page compared to the "Keyword search" field on the Chant Search page. This is likely because a `?search_bar=` parameter in the URL leads to an incipit-only search, whereas `?keyword=` leads to a full-text search. See #516.
- Related to the immediately preceding bullet point, a search via the search bar sometimes searches for Cantus IDs and sometimes for incipit substrings. When this occurs, the search term should appear in the appropriate field (i.e. Cantus ID, or Keyword Search) on the Chant Search page, but instead it reappears in the search bar. See #515.
- Default ordering of search results differs depending on whether one is searching by `?keyword=` or by `?search_bar=`.  See #514.
- If the user tries to reorder the search results by clicking on column headers after doing a `?search_bar=` search, the page hangs, usually leading to a 502 error. See #514.
- Some unexpected chants appear among search results, which may be a result of Postgres using fuzzy matching. See #419.
- applying `db_index=True` to some of our fields may help a bit (but if we're using search vectors, it is not likely to be a silver bullet). See #530.

Also, below I'm including some ideas and figurings-out as I learn/think about how to improve the Chant Search page.

**Comment by jacobdgm** [comment]
Regarding the question of why we have a search vector field: My understanding is that a SearchVectorField allows multiple fields to be concatenated, which allows the database to match a keyword against a single field. For our Chant model, we have an [`.index_components` method](https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/main_app/models/chant.py#L13), which combines the chant's `incipit`, `manuscript_full_text`, `manuscript_full_text_std_spelling` and `source.title`, along with its `genre.name`, `feast.name`, and `office.name` into a weighted list of search terms. There's a hook [in signals.py](https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/main_app/signals.py#L42) that uses this method to populate chants' `search_vector` fields. `incipit`, `manuscript_full_text`, `manuscript_full_text_std_spelling` and `source.title` are weighted relatively heavily, while `genre.name`, `feast.name`, and `office.name` are weighted relatively lightly.

The approach of searching against a search vector should be fairly efficient, as far as I can tell - my understanding is that all the fields above are concatenated into a single field which is added to the database, so in any particular query, the database only needs to look at one column from each row.

With that said, I don't think that the current selection of information to add to the search vector makes a lot of sense (@annamorphism - thoughts on this?):
- `incipit` should be a substring of `manuscript_full_text_std_spelling` (see #361), so why bother including it?
- a whole bunch of results appear when one searches for "Klosterneuburg", presumably because their source's name includes "Klosterneuburg" and not because the chant's text contains it. My understanding was that the Chant Search Page would mostly be used for searching through a chant's text - is there any situation where we'd want to return all the chants from a particular source in the chant search page?
- `feast.name` will be similarly un-useful - will a bunch of search results for "pentecostes" ever be useful for anyone?
- `genre.name` and `office.name` will hardly ever be useful, as their names are mostly one- or two-character strings ("A", "V2", "C", etc.).

A related issue is that the `search_vector` field is only populated for Chant objects, and not for Sequence objects, while the chant search page searches for both chants and sequences. I don't know what effect this has on search performance or search results.

Another issue is that concatenating the three versions of the full-text may interact with "Starts with" vs "Contains" in unexpected ways.

**Comment by jacobdgm** [comment]
~~[SearchQuery](https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/search/#searchquery) seems to be the main alternative to [SearchVector](https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/search/#searchvector).~~ A search query check against a search vector, so by saving a search vector in a field in our database, we can improve the performance of Search Queries.

A useful feature of SearchQuery would be allowing users to use `websearch`, which would allow queries like `"ecce terraemotus factus" descendit` or `terraemotus and willibaldus and not alleluia`, which I can imagine being helpful in <span title="such as when one needs to sing a Willibaldus earthquake chant, of course. Why do you ask?">certain use cases</span>.

Another thing we'd need to consider if we switch to SearchQuery is whether to search through the MS Spelling field or the Standardized Spelling field. We should probably just default to both? Another approach, though this would go beyond OldCantus's current interface, would be to give users two checkboxes, to indicate which of the fields they wish to search through.

**Comment by jacobdgm** [comment]
Another thing to consider and/or figure out if we're using SearchQuery or SearchVector is whether our database is configured with a dictionary (it seems that with certain configurations, Postgres will try to separate word stems from affixes. If it tries to apply an algorithm designed for English to our data's latin, it could lead to unexpected results), and whether it is ignoring stop words (and, in, of, by, to, etc.).

Both of these considerations are good arguments for using simple querying techniques (`contains` and `icontains`, etc) rather than using fancy database optimizations, which may optimize in ways we don't actually want.

The documentation on [SearchQueries](https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/search/#searchquery) contains the troubling indication "by default, all the words the user provides are passed through the stemming algorithms", without an indication of how to change this default. :/

**Comment by jacobdgm** [comment]
Working in my search sandbox, I am coming to the conclusion that combining the Chant and Sequence querysets into one set of results is the source of slowness for Chant search.

To return __all__ the __chants__ in my test database (about 500,000 of them in total), the page loads __instantaneously__.

To return __all__ of the __combined__ chants/sequences in the test database (about 600,000 of them in total), the page takes about __3 seconds__ to load.

__Searching__ for a short string among only the __chants__, the page takes __<1 second__ to display results.

__Searching__ for a short string among the __combined__ chants/ sequences, the page takes about __2 seconds__ to display results.

---

I have my test search pages set to paginate by 100, so the first 100 records are being returned in all situations above.

These timings do not change significantly when results are sorted by id, genre, etc. I'm not doing anything fancy to merge the results on the combined search page - I'm just unioning the two querysets.

---

I would still like to experiment with a few more things, but these initial results suggest that being able to work with a single queryset of Chants, rather than combining two querysets, may significantly improve our chant search page's responsiveness.

**Comment by annamorphism** [comment]
Is searching the same string among just the sequences just as fast as just among the chants? (so are the sequences themselves the problem, or is it having to string the two searches together in sequence?)

**Comment by jacobdgm** [comment]
the results above are with my test database - there's no functional difference between "sequences" and "chants", other than them being stored in separate tables in the database.

**Comment by jacobdgm** [comment]
That said, I just experimented with tweaking some things in the actual CantusDB code along these lines; here's what I found:

**chant_set**: I only fetch chants from the database, and return them
**combined**: I fetch chants and sequences from the database, and return the union of the two querysets (we're currently doing this)
**icontains**: I search the MS std spelling field, filtering using the bog standard case-insensitive `contains`
**keyword_search**: I use the `keyword_search` function someone wrote, which sorts multiple fields and ranks them by their relevance (as defined by Postgres) (we're currently doing this)

all timings in seconds

searching for "alleluia":
**chant_set, keyword_search: 2**
**chant_set, icontains: 1.5**
**combined, keyword_search: 2.5**
**combined, icontains: 1.5**

^ here, when we have only about 30,000 chants, switching to the bog-standard `icontains` seems to make the difference.

searching for "":
**chant_set, keyword_search: 1.2**
**chant_set, icontains: 1.2**
**combined, keyword_search** or **icontains** (doesn't matter which, as we're not filtering anyways): **9**

^ when we have all ~500,000 chants (this count is approximately accurate, whether or not you're including the sequences), returning only the chants makes a big difference

searching for "est":

**chant_set, keyword_search: 2**
**chant_set, icontains: 1.5**
**combined, keyword_search: 5**
**combined, icontains: 2**

^ approximately 50,000 results. using just the chant-set and just icontains achieves the best results. Switching either to the one we currently use makes things worse, and switching both makes things worse again.

**Comment by jacobdgm** [comment]
Another reason not to use postgres's fancy search features: no results are returned when one searches for "an", "am" or "at" (evidently, they're being ignored since they're common English words). "et" and "est" work, though. This is hardly ideal...

(context: was trying to find a search term with about 100,000 results...)

**Comment by ahankinson** [comment]
Are you using [Django Debug Toolbar](https://django-debug-toolbar.readthedocs.io/en/latest/)? Does it tell you how many actual SQL queries you're running when you do a search?

I once had a relatively simple page load that was very slow. Turns out that, through some pretty naive code, that I was running over 1,000 SQL queries on page load. Using the Debug Toolbar let me see how many queries the ORM was running, and let me optimize the queries with `select_related`. 

> Another reason not to use postgres's fancy search features: no results are returned when one searches for "an", "am" or "at" (evidently, they're being ignored since they're common English words). "et" and "est" work, though. This is hardly ideal...

These are called "stopwords". It looks like you can configure something other than the defaults with a well-placed file.

https://stackoverflow.com/questions/1497895/can-i-configure-postgresql-programmatically-to-not-eliminate-stop-words-in-full

I think this is probably the default list: 

https://github.com/postgres/postgres/blob/master/src/backend/snowball/stopwords/english.stop

**Comment by jacobdgm** [comment]
I spent some time last week trying to set up DDT, ran into difficulties, and set it aside in an attempt not to get bogged down; I'll give it another go today, as I agree, it will be a useful tool.

On one hand, I'm fairly confident that the two changes I noted above are responsible for the difference I observed - we're displaying the same information in the template for every record, whether it's a Chant or a Sequence. On the other hand, I do know that the branch I was experimenting on is not applying certain `select_related` optimizations that I'm confident will work. That is, once I get DDT running, I expect it to tell me that the ORM is running 7 queries for every record we display. Fixing this should make any differences in performance even clearer, so I'll try to get this set up soon.

**Comment by ahankinson** [comment]
Let me know if you need any help getting it set up.

**Comment by jacobdgm** [comment]
I think I should be good at this point! I had followed the installation instructions on Read The Docs last week, to no avail; however, I had copied some code from when Junhao had set up DDT a few months ago, and now that I've figured out where to put it, and have sorted out the additional layer of problems #557 created, DDT seems to be running properly. Thanks, though!

**Comment by jacobdgm** [comment]
another possible thing that could be contributing to the slowdown - in several views, like the chant-search view, we have code that looks something like

```{% comment %} this is used for distinguishing chants from sequences,
                    if the object is chant, use chant-detail view,
                    otherwise, use sequence-detail view.
                    the combined queryset turned all objects into chants
                    so this is the only way to make the distinction {% endcomment %}
                    {% if chant.search_vector %}
                        <td class="text-wrap"><a href="{% url 'chant-detail' chant.id %}">{{ chant.incipit }}</a></td>
                    {% else %}
                        <td class="text-wrap"><a href="{% url 'sequence-detail' chant.id %}">{{ chant.incipit }}</a></td>
                    {% endif %}
```
That is, we're searching for chants using Postgres search vectors, involving features like stopwords and search result ranking, searching for sequences using simpler `icontains`-style queries, and then combining the querysets. I don't have a sense of the specific details, but maybe if/when we start searching for chants in a simple way like we do for sequences, the querysets will play more nicely together and combining them will no longer cause the slowdown we're seeing.

(Also, of course, this feels like a terrible criterion to disambiguate between sequence objects from the Bower Database and chant objects in Cantus Database proper. A much better approach, which we could maybe implement eventually, would be to add an `is_sequence` boolean field or something to these models)

**Comment by ahankinson** [comment]
You might be able to use `annotate()`: https://github.com/DDMAL/CantusDB/blob/497986de3123edd49b0038abfc78f22dcdef5bbd/django/cantusdb_project/main_app/views/chant.py#L623-L624

I've never used it, and this hasn't be tested, but it might be worth trying:

```py
chant_set = Chant.objects.filter(cantus_id=self.cantus_id).annotate(chant_type="chant")
sequence_set = Sequence.objects.filter(cantus_id=self.cantus_id).annotate(chant_type="sequence")
```

Then `chant.chant_type` should be available in your template to differentiate. I'm not sure if the annotate will survive the queryset merges, but it might be worth a test.

**Comment by jacobdgm** [comment]
> Is searching the same string among just the sequences just as fast as just among the chants? (so are the sequences themselves the problem, or is it having to string the two searches together in sequence?)

Yes. They're the same - the only difference between the two models and their corresponding views is the substitution of the string "sequence" for the string "chant" in the relevant places in the code (and, I suppose, the randomly generated data in the database)

With 300,000 chants and 300,000 sequences in the database:

chant-only search: ~0.3 seconds (returns nearly 300,000 results, but displaying only the first 100)
sequence-only search: ~0.3 seconds (returns nearly 300,000 results, but displaying only the first 100)
chant+sequence search: ~5 seconds (returns nearly 600,000 results, but displaying only the first 100)

---

While I was setting up the database, I tried running a search before any sequences had been added to the database. Here are timings with 300,000 chants in the database, and 0 sequences:

chant-only search: <1 second
chant+sequence search: 3 seconds (!! - to be clear, the sequence queryset contains 0 sequences)

later, I tried deleting all the chants. I got analogous results with 300,000 sequences and 0 chants:

sequence-only search: <1 second
chant+sequence search: 3 seconds

**Comment by jacobdgm** [comment]
Aha! It appears that when you use `queryset.union(another_queryset)`, SQL defaults ensuring all rows in the new queryset are DISTINCT/unique. Switching to `queryset.union(another_queryset, all=True)` turns this off, and in my sandbox, it decreases the query time in the combined view from about 5s to about 0.8s. I think this is what we've been looking for!

**Comment by jacobdgm** [comment]
I tried quickly applying this change to CantusDB, and while query times (as measured by Django Debug Toolbar) drop, other processes seem to take correspondingly longer, leading to not much reduction in page load time. Not sure why this should be the case, but I'll try some more things in the sandbox to see whether I can figure out what's happening.

UPDATE: the toolbar itself adds quite a bit of overhead, which is enough to explain the difference. When I load a page in my sandbox, it will say that it took 300ms, say, on SQL queries, and a total CPU time of 500ms. If I turn off SQL profiling, the total CPU time drops to 100ms.

**Comment by jacobdgm** [comment]
Just taking notes - in sandbox, I'm getting near-identical queries running multiple times because of pagination. One query will be along the lines of `SELECT {a bunch of columns} FROM {complicated query, unioning chant and sequence queries} LIMIT 100` (i.e. the one actually fetching the results that will be displayed), and two will be `SELECT COUNT(*) FROM {the same complicated query}` (it appears one of these validates that the number of the requested page is not too high, and the other calculates the _`n`_ in "displaying chants `x` to `x+100` of _`n`_") - these last two are each triggered by a step in the pagination process. Eliminating these could potentially lead to a 2x-3x speedup.

These three queries take up almost the entirety of the query time; I've not tried to apply any `.values` / `.select_related` optimizations, but the several hundred queries that would be eliminated by this optimization would trim <10% of the total time running queries.

It seems to be more of a problem on higher page numbers, and less of a problem on the first/second page (but only by a factor of about 2).

**Comment by jacobdgm** [comment]
Okay, either I'm going crazy, or there's something going wrong with the Compute Canada servers (or possibly both?). When I `git checkout` the `staging` branch locally and search for "jerusalem" on the chant search page, I get results in <2 seconds. When I try it on [staging](http://206.12.88.113/), it takes 5-6 seconds. I checked `git log` in both places, and I have the same latest commit locally as on the staging server. The same number of chants are returned. I tried rebuilding my docker container locally, and I'm still seeing the same results. I'm baffled.

**Comment by ahankinson** [comment]
There is a significant difference in HD throughput on CC servers, which may explain it. 

Try running this command on the server:

`dd if=/dev/zero of=/tmp/test1.img bs=1G count=1 oflag=dsync`

And then compare it to running locally. If your local machine is a Mac, the command is:

`dd if=/dev/zero of=/tmp/test1.img bs=1G count=1 && sync`

On the server I get:

`1073741824 bytes (1.1 GB) copied, 13.0557 s, 82.2 MB/s`

While on my Mac I get:

`1073741824 bytes transferred in 0.290601 secs (3694900651 bytes/sec)`  (about 3.7GB/s!)

This could explain the difference you're seeing.

(remember to `rm /tmp/test1.img` after you're done!)

**Comment by jacobdgm** [comment]
Well! Running this on my local machine takes ~0.5s, whereas running it on both staging and production takes 11-12s. Thanks for this suggestion - this quite possibly accounts for the difference in performance!

**Comment by jacobdgm** [comment]
Another thing that could account for the differences: It seems that I've been running Postgres 15 on my local machine for the past several months, whereas we've been running Postgres 14 on the staging server.

**Comment by jacobdgm** [comment]
Looking at the bullet points in the first comment, basically all of them have been addressed! The chant search page is in good shape these days. Going to close; further issues related to the Chant Search page can be given their own issues, and we can create a new meta-issue if we end up with a bunch of related issues.
