### ISSUE TITLE
Turn Sequence objects into Chant objects?

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#561]
Why don't we turn all Sequence objects into Chant objects? We did something similar when we merged indexers and users, but this would be much less involved than actually merging two models.

Main benefits:
- wherever we search for chants and sequences, it would simplify the process immensely - currently, we create a Chant queryset and a Sequence queryset and then union them - if we were working with just Chant objects, we could use just a single queryset, thus reducing the chance of bugs, improving readability, etc., etc.
- we could combine several templates/views that currently have lots of repeated code, simplifying the codebase

Possible difficulties:
- In case people have cited/bookmarked a url with /sequence/ in it, we would need to set up redirects to the new Chant detail pages. This will be much simpler to do now rather than later (see below)

Why we might want to do it now, rather than later:
- if we make the merge before the last sync between OldCantus and New, all chants and sequences will have unique IDs, because of how Drupal manages its database. Django handles this differently (i.e. each model has its own database table, rather than all of them being stored in a single table as in Drupal), so once people start creating chants in NewCantus, we're likely to get pk collisions, which will make the merging of the two models (and the creating of any necessary redirects) more complicated.

Reasons why it would not be difficult:
- The Chant and Sequence models currently have all the same fields, it's just that certain fields are currently left blank for Chant objects and other left blank for Sequence objects. A database row for a sequence-turned-chant would thus look just like the database row for the current sequence.
- The process would be a lot simpler than the Indexer-User merger that occurred a few months ago: whereas we had duplicate Indexers and Users that needed to be paired up with each other (e.g. Debra as user and Debra as indexer), this is not the case with Chants and Sequences - all we would need to do is create a new Chant object for each Sequence currently in the database. We could even retain the current Sequence objects in the database, and include a reference in each new Chant object to its original Sequence object.

The workarounds we currently employ are fine, but considering Sequence objects are likely going to be converted into Chant objects eventually, considering that the conversion process will become more complicated once NewCantus replaces OldCantus, and considering there would be immediate benefits to making the switch, I think it's worth thinking about doing this sooner rather than later.

**Comment by annamorphism** [comment]
I think the reason this wasn't done in the first place has something to do with wanting to keep the Sequences in a sort of semi-published status---that is, they are viewable to most users, like published sources, but they're also sequestered, so it's obvious that they came from some other database and the data may not be of the same things or to the same editorial standards as everything else currently on the database.  
If all sequences get turned into chant objects, it seems to me that this distinction will be lost, and the sequences will just look like poorly edited chants, which we want to avoid.  But maybe I'm wrong!

**Comment by jacobdgm** [comment]
This makes sense - I hadn't thought of why the current situation exists in those particular terms.

In principle, it would be possible to make everything appear the same as a currently does (using URLs with /sequence/ as opposed to /chant/, etc.), but to store current Sequence objects in the database as Chants.

But I guess if the process of turning them into full-fledged chants will involve a proofreading step, it could make more sense for proofreaders to manually create new chants as they proofread.

It makes more sense to me now why we're choosing not to standardize Chants and Sequences in the same way we did Users and Indexers. Thanks!
