### ISSUE TITLE
Source Detail page - sequence list missing columns

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#562]
On the source detail page, for sources in the Bower segment, we display a table of all the sequences in the source. OldCantus has "Notes:1", ":2" and ":3" columns that we do not display - compare https://cantus.uwaterloo.ca/source/123931 with http://206.12.93.196/source/123931.

Was it a conscious choice to not include these columns?

**Comment by annamorphism** [comment]
A very good question! I wonder if it was in part because it is mysterious to most people (including me) what these notes are supposed to mean...so the information is not really in a usable form at the moment.
