### ISSUE TITLE
Chant Edit/Proofread pages - UnboundLocalError

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#574]
discovered at http://206.12.88.113/edit-chants/123704?pk=316285&folio=003r. Doesn't seem to affect that chant's Detail page, but it is also present at http://206.12.88.113/proofread-chant/123704?pk=316285&folio=003r.

**Comment by jacobdgm** [comment]
It's because the chant has neither `manuscript_syllabized_full_text`, `manuscript_full_text`, nor `manuscript_full_text_std_spelling`. Both OldCantus and New validate to make sure every chant has at least a `manuscript_full_text_std_spelling`, but I guess this is a case we have to deal with. Currently working to fix the functions in `align_text_mel.py` to account for this edge case.

**Comment by jacobdgm** [comment]
Current plan of attack:

- [ ] Add type annotations and comments to the functions in `align_text_mel.py` (in progress - the functions in this file are already fairly well commented, but the values returned are quite complex in some cases, so this will help me figure out exactly where things are going wrong and how to fix it).
- [ ] Fix the relevant function(s) (question @annamorphism: if a chant has volpiano but no fulltext, in the text-with-melody preview, we want to display the volpiano without any text beneath it, yes?)
- [ ] Write more exhaustive tests for the functions in the file, and for the Chant Edit and Proofread views.

**Comment by annamorphism** [comment]
Hmm. In principle I would say that it's still possible to match the volpiano incipits to the text incipits, which seems to be what was attempted in these cases (the several volumes DK-Kk 3449 8o), but the Volpiano was entered wrong and it doesn't work.  So yes, I think Volpiano with no text is probably the way to go. 
Incidentally, is there any way of finding out how many sources have this problem of not having full texts?

**Comment by jacobdgm** [comment]
> In principle I would say that it's still possible to match the volpiano incipits to the text incipits, which seems to be what was attempted in these cases (the several volumes DK-Kk 3449 8o), but the Volpiano was entered wrong and it doesn't work. So yes, I think Volpiano with no text is probably the way to go.

Currently, we check syllabized fulltext, then MS spelling fulltext, then STD spelling fulltext. It's certainly possible to add the chant's incipit to this list (as this appears to be what OldCantus does), and then use an empty string as a last resort, but I can leave the incipit out of this list of things to check if you think it would be best.

**Comment by jacobdgm** [comment]
> Incidentally, is there any way of finding out how many sources have this problem of not having full texts?

I'm just looking into this, and it seems to be surprisingly (even frighteningly) common. I ran the following commands on the staging server, whose data should be basically the same as OldCantus's was a few months ago...

```python
>>> from main_app.models import Chant
>>> chants_w_empty_fulltext = Chant.objects.filter(manuscript_full_text_std_spelling__isnull=True)
>>> chants_w_empty_fulltext.count()
277655
```
Like, that's about half of the chants in the database (!!)

I tried to tally up the sources that contain these chants, and python died rather than completing the calculation:

```python
>>> empty_fulltext_sources = {c.source for c in chants_w_empty_fulltext if not c.manuscript_full_text_std_spelling}
Killed
```
I don't understand why so many chants have no fulltext - OldCantus doesn't let you save a chant if it doesn't have a fulltext, correct? I guess a bunch of these chant records could have originally been from indexes of sources where the researcher only copied down the chant's incipit.

One thing to take from this: this seems like a strong argument not to simply get rid of the `incipit` field and rely on the first few words of a chant's fulltexts, as was floated in #361...

**Comment by jacobdgm** [comment]
> I don't understand why so many chants have no fulltext - OldCantus doesn't let you save a chant if it doesn't have a fulltext, correct? I guess a bunch of these chant records could have originally been from indexes of sources where the researcher only copied down the chant's incipit.

Come to think of it, when I worked as a transcriber for OldCantus, I spent some time filling in texts for a manuscript that did not have fulltexts iirc. Whenever I would load up a chant edit page, the standardized fulltext field would be automatically populated (based on the chant's Cantus ID, I'm guessing), and it was my job to verify that the predicted full text actually matched what I saw in the manuscript. We don't have this functionality currently implemented afaik - is this another thing we need to implement before NewCantus is production-ready? (update: we _do_ have this functionality implemented - phew!)

**Comment by annamorphism** [comment]
> 277655
> ```
> 
> Like, that's about half of the chants in the database (!!)

Huh, that's really quite a lot more than I would have expected! I'm trying to figure out how many sources this is...

> I don't understand why so many chants have no fulltext - OldCantus doesn't let you save a chant if it doesn't have a fulltext, correct? I guess a bunch of these chant records could have originally been from indexes of sources where the researcher only copied down the chant's incipit.

Correct. OldestCantus (in the 00's and before) often just gave incipits, with the aim of quickly getting a table-of-contents level analysis.  This is not possible to do anymore (but also not necessary, since it's possible to autofill the text field.) However some of the old records are still with us.  Some of these have since been converted to longer texts (hence "full-text-entered-by" as an indexer role) but apparently many (!!) still remain. 


> 
> One thing to take from this: this seems like a strong argument not to simply get rid of the `incipit` field and rely on the first few words of a chant's fulltexts, as was floated in #361...

Agreed.
