### ISSUE TITLE
Rework footer to match layout on OldCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#578]
Debra has requested that the MARGOT logo be adjusted - the version recently added to OldCantus has been cropped so that the text takes up more of the frame:

> Jacob - take a look at what Jan did with the MARGOT logo re: size and placement on the page. I think trimming off some of the red improves its look. Could you use this same version for the new Cantus DB?

for easy reference: https://cantus.uwaterloo.ca

**Comment by jacobdgm** [comment]
PR #579 adds the cropped logo.

Focussing on other things right now, but at some point, it would be worth reworking the footer to match the formatting seen on OldCantus more closely.

OldCantus:
![Screenshot 2023-03-13 at 9 20 17 AM](https://user-images.githubusercontent.com/58090591/224713806-cadb8c61-f909-49ac-a044-d3437890371c.png)

NewCantus, as of PR #579 (it's worth noting that this is the logged-in view):
![Screenshot 2023-03-13 at 9 20 53 AM](https://user-images.githubusercontent.com/58090591/224713923-9ddd106c-a227-4570-86c6-08b13c1b1c00.png)

Note how in NewCantus, the logos are in different places and of different sizes, and red bar at the bottom of the page is not as thick as in OldCantus. The date range for the copyright should also be updated.

**Comment by annamorphism** [comment]
I have this strange feeling that the regrouping of the footer was in fact done by request, but maybe I am just remembering being pleased with the re-arrangement (which looks much better in my opinion).

**Comment by jwang44** [comment]
I don't recall the regrouping being done by request. I re-arranged it because I wanted the footer to be more compact. But I do agree that the re-arrangement looks better :)

**Comment by jacobdgm** [comment]
I think this is fine the way it is. Closing. We can re-open this issue if anyone complains.
