### ISSUE TITLE
pages in the admin area very slow to load

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#587]
related to #208, I tried to upgrade @annamorphism's permissions through the admin page on staging, and got a variety of 50x errors (severe enough that it prevented me from updating the permissions) when I tried to visit the admin user detail page. Similar results occurred when I tried to do the same thing on production. Debra/others are going to need to change objects via the admin panel, so this needs to be sorted out sooner rather than later.

**Comment by ahankinson** [comment]
Usually this is caused by lots of SQL queries for complex data models.

Admin models have a `get_queryset` method you can override and add in `select_related` which can help massively.

See, for example: https://github.com/diamm/diamm/blob/master/diamm/admin/data/item.py#L139-L142

**Comment by jacobdgm** [comment]
Thanks for these pointers, @ahankinson!

Some general comments, for helping me/a future developer unpick this: Testing locally, I'm able to load Anna's page, but it takes ~1min (as compared to the page for my own account, which takes a second or two). The main difference between our accounts is that Anna has dozens of sources for which she is listed as a current editor.

We already have some customization of the User Change page, to allow listing of sources, so I'll do some reading of docs and some experimenting to try to sort this out.

**Comment by jacobdgm** [comment]
> Usually this is caused by lots of SQL queries for complex data models.

You don't say...
![Screenshot 2023-03-15 at 2 41 44 PM](https://user-images.githubusercontent.com/58090591/225412096-dad59da1-4695-4971-9272-c9a84fe98ebe.png)

Glancing through the queries, it seems that in generating the list of User-Source relations, we're getting lots of similar/duplicate queries to the RismSiglum table, since sources' `rism_siglum` is being used to generate their `__str__`.

**Comment by ahankinson** [comment]
Yeah, you should be able to clear that up with a `select_related`. You can do through relationships there as well with the double-underscores -- `select_related("source__rism_siglum")` might help?

**Comment by jacobdgm** [comment]
running some experiments locally in the Admin Area using DjDT to establish a baseline and identify the areas that are particularly problematic:
- Articles
  - Articles
    - "Select article to change" page: 5 queries, 12.63ms
    - "Change article" page: 5 queries, 6.65ms
- Authentication and Authorization
  - Groups
    - "Select group to change": 5, 13.28
    - "Change group": 6, 10.30
- Flat Pages
  - Flat Pages
    - "Select flat page to change": 6, 9.10
    - "Change flat page": 6, 8.99
- Main App
  - Centuries
    - "Select century to change": 5, 6.77
    - "Change century": 4, 12.17
  - Chants
    - "Select chant to change": 5, 68.06
    - "Change chant": **_page took more than 60s to load. Subsequent attempt timed out._**
  - Feasts
    - "Select feast to change": 5, 12.7
    - "Change feast": 4, 10.90
  - Genres
    - "Select genre to change": 5, 17.05
    - "Change genre": 4, 4.86
  - Notations
    - "Select notation to change": 5, 13.65
    - "Change notation": 3, 28.55
  - Offices
    - "Select office to change": 5, 13.65
    - "Change office": 4, 11.48
  - Provenances
    - "Select provenance to change": 5, 9.93
    - "Change provenance": 4, 12.10
  - RISM Sigla
    - "Select RISM siglum to change": 5, 13.83
    - "Change RISM siglum": 4, 4.70
  - Segments
    - "Select segment to change": 5, 14.7
    - "Change segment": 4, 12.54
  - Sequences
    - "Select sequence to change": 5, 41.17
    - "Change sequence": 691, **_376.35_**
  - Sources
    - "Select source to change": 14, 18.97
    - "Change source": 23, 37.24
- Sites
  - Sites
    - "Select site to change": 5, 7.61
    - "Change site": 4, 10.79
- Users
  - Users
    - "Select user to change": 6, 9.07
    - "Change user": 2731, **_678.24_**

(all SQL execution times > 100ms **_bolded and italicised_**)

Some patterns/conclusions we can draw from this:
- The pages where individual objects are listed ("Select {} to change") are not a problem
- The pages that took a long time to load were all "Change {}" pages - Chant, Sequence and Source. One common feature of all of them is that the page features a list of sources.
  - The User page fires off many more queries than the Sequence page.
    - At first glance, this seems to make sense: sequences can either belong to a source or not - to display the page, we only need to generate one list of sources, whereas users can be assigned as "current editors", "inventoried by"s, etc., there being six possible relationships.
    - But 2731/691 ~= 4 != 6.
    - Also, on the user page, we only display a single section with a list of sources ("Source-User Relationships", and it doesn't specify how they're associated with the source (!) - this seems to be a bug/oversight).
    - Most of the queries shown in the toolbar while loading the user page are queries to the `main_app__rismsiglum` table in order to show the string representation of a source, so the it's-slow-because-we're-displaying-a-list-of-sources hypothesis seems to hold up. But something isn't adding up here.

**Comment by lucasmarchd01** [comment]
As I am working on a PR for a similar issue with slow loading pages I came across this issue. It seems to have the same problems and most likely the same solution with `select_related`. I investigated the pages that are noted as being slower than others but it seems like they are using a relatively low number of queries already. Has this issue been resolved as a result of #608?

**Comment by jacobdgm** [comment]
> Has this issue been resolved as a result of #608?

Not resolved, no. Even the factor-of-three speedup I observed means we're still waiting ~5s for certain pages to load iirc.

**Comment by lucasmarchd01** [comment]
Update for this issue: I have tried lots of different ways to optimize this page while maintaining the inline for sources users can edit. The closest I could get was by using `raw_id_fields` which already drastically improves queries compared to the default select-boxes. The overwritten `get_queryset` method aims to prefetch the sources user can edit.
```
class SourceInline(admin.TabularInline):
    model = Source.current_editors.through
    raw_id_fields = ("source",)

    def get_queryset(self, request):
        queryset = super().get_queryset(request).select_related("source")
        return queryset
```
This solution SHOULD work, but unfortunately there is still a known Django bug (https://code.djangoproject.com/ticket/29294#comment:2) that prevents the widget used by raw_id_fields in inlines from using the prefetched values. We can instead use `readonly_fields` which does work, however it will not allow you to add another source to a user from the user admin page, which is not what we want. 

There is another potential solution here (https://deepintodjango.com/reducing-queries-for-foreignkeys-in-django-admin-inlines) but looks a little bit hacky so I'm not sure about this one.

**Comment by jacobdgm** [comment]
(for reference, this was closed because we just tested on Production, and both the Change User and Change Chant pages load nice and quickly!)
