### ISSUE TITLE
In Concordances, link to MMMO leads to 404 Error

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#591]
On Chant Detail pages, in the Concordances section, links to the Medieval Music Manuscripts Online Database are broken.

To replicate:
- Visit a [chant detail page](http://206.12.93.196/chant/271704#concordances)
- In the "Concordances" section, in the summary table of the different databases. Click on "{N} chants", after MMMO (on this page, it says "1 chant")
- the new tab leads to a 404 page on musmed.eu (i.e. on the MMMO website)

This problem seems to occur on other sites (e.g. clicking on the corresponding link on [the CantusIndex.org page for the relevant Cantus ID](https://cantusindex.org/id/006698) leads to the same page), so I think this is a combination of MMMO's problem and Cantus Index's problem, rather than being our problem. Links to individual chants in MMMO, such as those in the full table that's beneath the summary table discussed above, seem to work fine.

**Comment by annamorphism** [comment]
Well observed! It's *sort of* our problem--it seems like MMMO at one point had /ID pages for all the chants in their database matching a certain ID (as Cantus DB does, and several of the other DBs), and now just refers people to the concordances across the network? Or, alternatively, it was supposed to implement such a page, but never did. If it's the latter, then perhaps Debra can bug them. If it's the former, maybe some other solution needs to be found (e.g. maybe it makes more sense to just give the tally and not construct a link).
Amusingly, the link to MMMO doesn't even work on MMMO itself --all the other concordances on http://musmed.eu/chant/24290 go somewhere, but not that one!

**Comment by jacobdgm** [comment]
This seems to be fixed on MMMO's end. Closing
