### ISSUE TITLE
Sequence Detail page: list of concordances should come from Cantus Index, not from our database

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#598]
Currently, on the Sequence Detail page, our list of concordances is all the chants/sequences in our own database with the matching Cantus ID (see http://206.12.93.196/sequence/635594). Curiously, OldCantus seems to do the same (see 
https://cantus.uwaterloo.ca/sequence/635594, noticing the lack of summary table with links to other databases above the list of concordances). CantusIndex does have a page for this Cantus ID (https://cantusindex.org/id/ah53010), and other databases seem to have no trouble displaying the table of concordances (e.g. http://musmed.eu/chant/166140), so we should probably change this to match the Chant Detail page.

**Comment by annamorphism** [comment]
Not sure about this. As it is, one can compare all the rubrics and notes in the Bower DB at a glance, which is not true if all the sequences are handled like chants. (This means you can see e.g. which saint and which melody name is used for some sequence elsewhere https://cantus.uwaterloo.ca/sequence/620709, which is not true in the equivalent CI concordance: https://cantusindex.org/id/ah53243).

**Comment by jacobdgm** [comment]
Okay - good to know that this is likely a feature rather than a bug. I'll close this.

In the sequence detail page you linked, where can you see the info about saint and melody name? This is mostly in the "Rubrics" column, yes?

**Comment by annamorphism** [comment]
The "rubrics" columns indicate which saint is indicated in the manuscript, exactly as given (the "Feast" in Cantus is similar, but uses a fixed vocabulary). The melody name, when there is one, is in Bower's "Notes:3", and has no equivalent among chants.
