### ISSUE TITLE
Source List page behaves differently than expected

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#603]
The Source List page behaves differently on NewCantus than it does on OldCantus.

If you visit http://206.12.88.113/sources/, the default Segment is "-Any-". But if you visit https://cantus.uwaterloo.ca/sources, the default Segment is "CANTUS Database".

Also, viewing the pages while I'm logged in, I see a different number of sources displayed:

- In the "CANTUS Database" segment, I get 502 sources on Staging and 245 sources on OldCantus.
- (I get the same number, 326, on both sites searching in the Bower segment)

This could be because OldCantus has a different system to handle published vs unpublished.

In any case, it might be worth someone taking a close look at this to ensure everything works as intended.

There are additional discrepancies noted in #412.

**Comment by annamorphism** [comment]
Yes, the discrepancy about published/unpublished sources is considerable!! 
And things that are published in one can be unpublished in the other, and vice versa if I remember right (mentioned in #172). I think I have a list somewhere of how many sources fall into which categories. 
At any rate, it means things that are only accessible to admins in OldCantus (because "unpublished" in a specific OldCantus sense) are visible to all logged-in users in NewCantus.  This might be desired behaviour, but it's a shift in how things work.

**Comment by jacobdgm** [comment]
> At any rate, it means things that are only accessible to admins in OldCantus (because "unpublished" in a specific OldCantus sense) are visible to all logged-in users in NewCantus. This might be desired behaviour, but it's a shift in how things work.

If I recall, this change (from using two fields, `unpublished` and `visible`, to using a single field, `published`) was made in discussion with Debra, so yes, "desired behavior" is true. I don't recall the exact policy, however, that was used to simplify the two old fields into the current one field...

**Comment by annamorphism** [comment]
Still trying to figure out which sources do what and where. 
All in all, OldCantus has (as of today) 521 sources in the CantusDB "segment"; NewCantus has 502. Some of the extra ones are probably something to do with the latest import  (seems not to include things that were added to OldCantus after last June or so, by the look of it; I can account for at least 15 of these, but it's possible there are 4 more I didn't find.) 
So, virtually all the sources in oldCantus (the 521 previously in sources-all) are now in the 502 sources for any logged in user to see in NewCantus under sources. That said, some things added directly to NewCantus (an assortment of test sources) seem to exist in a state where they are visible to the creator (me) under My Sources, but are not in the 502 sources in the list. Are these in some sort of invisible/unpublished state? I assume an admin has to publish them, if that were to be wanted? I don't seem to be able to publish them myself. 
It seems...strange to me that everything coming from OldCantus is apparently in the source list by default, but things made in NewCantus are not.

**Comment by jacobdgm** [comment]
> Are these in some sort of invisible/unpublished state? I assume an admin has to publish them, if that were to be wanted? I don't seem to be able to publish them myself.

Looking around in the Admin section on the Staging site, I can see a few recently created sources. There's a checkbox at the top of the page which allows me to toggle its published/unpublished status:

![Screen Shot 2023-04-17 at 09 29 45](https://user-images.githubusercontent.com/58090591/232498693-9b0b60a6-d4c4-4017-b59f-c77a246e7ba4.png)

The source does seem to appear among search results when I'm logged in (we'd expect such unpublished sources to appear when a user is logged, but not when they're not): http://206.12.88.113/sources/?segment=4063&general=Te-st+123&indexing=&provenance=&century=&fullSource=

**Comment by jacobdgm** [comment]
> It seems...strange to me that everything coming from OldCantus is apparently in the source list by default, but things made in NewCantus are not.

We'd expect all published/visible sources in OldCantus to be published (i.e. visible to non-logged-in users) in NewCantus, but newly created sources in NewCantus need to be "approved" by an administrator, it seems. Are you aware of any examples of sources that are unpublished in OldCantus that _do_ appear in the sources list on NewCantus?

Let me see again what I can do about giving you full permissions on staging/production, so you can test in a bit more depth.

**Comment by annamorphism** [comment]
> 
> The source does seem to appear among search results when I'm logged in (we'd expect such unpublished sources to appear when a user is logged, but not when they're not): http://206.12.88.113/sources/?segment=4063&general=Te-st+123&indexing=&provenance=&century=&fullSource=

Aha--the problem seems to be that I created a few test sources with no siglum. These are the ones that don't show up in the results, but I think the others all do. And since the loophole allowing siglum-less sources has been fixed, it shouldn't happen for anything else (we hope.)

**Comment by jacobdgm** [comment]
I think we're happy with the current state of the Source List page. Closing, feel free to reopen if necessary.
