### ISSUE TITLE
syllabifying tool should draw on standard text if there is no full text

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#606]
in OldCantus, editing the syllabification of a chant with no MS Full Text will give you a window where the syllabification is populated with the current syllabification based on the "Standardized" reading:

![image](https://user-images.githubusercontent.com/67451875/230173767-3ce052eb-536a-4a42-ab47-8d6322642571.png)

In NewCantus these cases will give you two blank fields, which means you can't see what text it was you were trying to edit!  
![image](https://user-images.githubusercontent.com/67451875/230176237-66df7b15-794f-4044-b0e2-8979e2677344.png)

**Comment by annamorphism** [comment]
(although I will add that OldCantus's method is not without flaws; in the example above, the text actually has a few more words, but because they didn't match the Volpiano, they've been removed from "syllabized full text" as well: 
![image](https://user-images.githubusercontent.com/67451875/230175001-a5bb2369-eff9-4461-9066-91148bb9bc4b.png)

**Comment by jacobdgm** [comment]
Would adding an extra field to the Edit Syllabification page, allowing the user to also view/edit the standard text, be a reasonable approach? This would be simpler than checking which of the two full text fields to display.

**Comment by jacobdgm** [comment]
Or is the main issue here the auto-populating of the syllabized text field? It should not be difficult to fill in that field using either of the MS/STD spelling fulltext fields, but that wouldn't solve the problem of the non-syllabized field being empty.

**Comment by annamorphism** [comment]
It's both. We definitely want the syllabized text field to be auto-populated. Ideally the field above it with the full text is filled too, though currently on OldCantus it isn't always, and that's workable. The auto-populated field should display with the syllabification currently being used--whatever it is--so that a minimum of hyphens need to be deleted. 

(for Full Fanciness you could conceivably adapt the syllabification algorithm to whichever spelling you are using--e.g. "ae" is likely one syllable in Standardized Spelling but two in MS spelling--but maybe that's a little crazy.)

**Comment by jacobdgm** [comment]
I've split this into two issues, one for displaying both fields (as an enhancement) and one for auto-populating the Syllabized full Text field (as a feature that needs to be implemented, since OldCantus does it). Closing.
