### ISSUE TITLE
Check for broken links using GitHub Actions

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#611]
We can use GitHub Actions to check whether any links have stopped working in CantusDB.

**Comment by jacobdgm** [comment]
We should also think about other places to use GitHub Actions in the CantusDB development process.

**Comment by zhannaklimanova** [comment]
Because this is not a static website, the simple link checker that's being used for something like the ddmal website will not work as easily. The recursive option that I tried, will likely work but may take hours to execute - this will have to be a background job running in Github actions.

**Comment by fujinaga** [comment]
@zhannaklimanova Please ask Andrew next week, for a good solution.

**Comment by jacobdgm** [comment]
It seems it won't work to run a link-checker script in GitHub actions, since NewCantus is not a static site, and has too many pages to check in a reasonable amount of time. But we learned some useful things when @zhannaklimanova ran a script as a one-off on the Production server. Closing - we can think of this one as a qualified success!
