### ISSUE TITLE
Change “rism_siglum” model to “archive”

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#621]
The RISM siglum model in this project currently takes an abbreviation that conforms to the RISM siglum, and a description that, presumably, is the actual name of a holding institution for a manuscript.

I have recently been updating the DIAMM site to accommodate links to RISM Online, and I think this would be a great place to do some further alignment between the three projects.

The DIAMM Archive model is here: https://github.com/diamm/diamm/blob/master/diamm/models/data/archive.py

There is also a one to many relationship with other identifiers for a given institution, which can be seen here:
https://github.com/diamm/diamm/blob/master/diamm/models/data/archive_identifier.py

This allows forms of identifier like `institution/123456`, which we can then add the base URL prefix of `https://rism.online` to, but can also use as a namespaced identifier, eg `rism:institution/123456`.

So I would propose making the change to Cantus by renaming the RISM siglum model to “Archive” (or something similar) and adding the ability to capture external identifiers for that institution that can be used to link the two.

(I wouldn’t necessarily expect the actual model to change too much, but it would probably be good to have a “name” field for the organization…)

**Comment by jacobdgm** [comment]
If only in order that we can have "siglum" meaning just one thing in the codebase, and even without considering the other, more substantial reasons you offer, I'm fully in support of this change!

@fujinaga, we should think about how exactly to implement this in order to most seamlessly integrate this into the larger Linked Music landscape.

**Comment by dchiller** [comment]
We've gotten rid of the rism_siglum model and everything discussed in this issues has been superceded by the introduction of the `Institution` and `InstitutionIdentifiers` models.
