### ISSUE TITLE
404 Error when trying to access Source Edit Chants view of a Source with no chants

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#631]
When a user (logged-in, with edit access for a source) clicks on the "Edit chants (fulltext & volpiano editor)" button on a Source Detail page, if that source has no chants, a 404 error results. See, for example, http://206.12.88.113/source/710897 -> http://206.12.88.113/edit-chants/710897 (404)

I'm pretty sure this is because our Source Edit Chants view only works if there is at least one folio specified among the chants in the source (and since folios are properties of chants, if there are no chants, there will be no folios). 

This occurs both on test sources that lack both chants and sequences, and on sources in the Bower segment that contain only sequences and no chants.

When you take a source with 0 chants and add a chant, the link/page work as expected.

We should be able to fix this by hiding this link in the template if the source has no chants.

**Comment by lucasmarchd01** [comment]
This Issue has been resolved in #635, closing
