### ISSUE TITLE
OldCantus Source Detail page has a Manage Source panel with links to pages not yet implemented in NewCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#633]
On OldCantus, on the Source Detail page, there a "Manage source" panel not present in NewCantus (see blue rectangle):

![Screenshot 2023-05-10 at 1 56 25 PM](https://github.com/DDMAL/CantusDB/assets/58090591/ece3f40c-7f26-4bb7-bf86-8bf7591a5ac3)

- Clicking on "Manage source editors" leads to a "Manage source editors" page (https://cantus.uwaterloo.ca/source-editors/680970)

![Screenshot 2023-05-10 at 2 03 45 PM](https://github.com/DDMAL/CantusDB/assets/58090591/2913c6e4-57f2-4599-a807-dfa1a5983e87)

- Clicking on "Update CSV file" leads to a "Save static CSV file with a source index" page (https://cantus.uwaterloo.ca/save-csv?src=680970). This page includes a link ("Download CSV") which leads to the same url as the "CSV export" link on the main Source Detail page.

![Screenshot 2023-05-10 at 2 07 46 PM](https://github.com/DDMAL/CantusDB/assets/58090591/a595f719-d063-49b7-b947-91bb1ee35ff2)

- Clicking on "Update in the Cantus Analysis Tool" leads to a "Export data for analysis tools" page (https://cantus.uwaterloo.ca/json-analysis-export?src=680970)

![Screenshot 2023-05-10 at 2 09 45 PM](https://github.com/DDMAL/CantusDB/assets/58090591/def9ea09-f88b-4bbb-b653-2b7dc9f74a3d)

- Clicking on "Update the concordances" leads to [a page on cantusindex.org](https://cantusindex.org/refresh-ci-json?url=https%3A//cantus.uwaterloo.ca/json-source-cids/680970)

This panel seems to be distinct from the "Source edit options" panel, present on other sources, which NewCantus has implemented.

**Comment by jacobdgm** [comment]
I've emailed Debra to ask about these - more details to follow!

**Comment by annamorphism** [comment]
Did we ever work out what this is supposed to do (and whether it is necessary)?

**Comment by jacobdgm** [comment]
> Did we ever work out what this is supposed to do (and whether it is necessary)?

Based on Debra's email,
- Manage Source Editors is probably not necessary:
> Not necessary for me because I go into the "Source Description" screen to manage source editors. (This duplicates that, I think.)

But maybe this implies that this page is accessible via a link somewhere else, and we still need to implement it because we don't have it yet? Or is Debra describing what I think of as our Source Edit page?
- Update CSV File - Debra never uses it, so probably not necessary
- Update in the Cantus Analysis Tool - Debra doesn't want this
- Update the concordances - Debra says this isn't useful, so we can not implement it.

**Comment by jacobdgm** [comment]
Going to close this for the time being. We have a link to a place to manage source editors on the Source Detail page. Maybe once Debra starts using NewCantus more regularly, she will let us know that she wants it set up differently, in which case, we can reopen this and/or open another issue. All the other things need not be implemented, it seems.
