### ISSUE TITLE
CI Input tool pop-up should go away

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#637]
Currently after you choose a chant using the "Input tool" the window stays there, making it hard to tell if you selected the chant or not. In OldCantus it goes away after the information is in the edit form.

**Comment by jacobdgm** [comment]
This is the CI Search View, correct, i.e. the one accessed via "Search ID" on the Chant Create page?

I don't immediately know how to do this, but it strikes me as something that should not be difficult to set up.
