### ISSUE TITLE
request: admin navigation should be for admins only

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#641]
On the bottom of my log-in page there is an "Admin navigation" panel:

<img width="305" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/c6591b53-7ccc-4ffd-b95f-60c69e9dfb97">
This strikes me as a bit silly for two reasons, since 1) I am not really an Admin in NewCantus, merely a peon who is not referred to as an admin anywhere else and 2) Both the functionalities are already present elsewhere and thus not very necessary(as noted obliquely in the discussion in  #632).  I am not sure if the silliness of (1) is also true in OldCantus or not, since I am, in fact, an admin there, but I will check on my alt account. If not maybe it should be renamed.  (2) definitely is true of OldCantus. Probably this panel could just be removed for non-admin users?

**Comment by jacobdgm** [comment]
Based on our recent discussion, we should simply hide the entire "admin navigation" panel for users who aren't admins. It would be helpful, though, to have a link to the `/my-sources` page, so we can add a hyperlink to the header of the "My Sources" panel that links to this page.

This should be an easy fix!

**Comment by lucasmarchd01** [comment]
Closed with #686
