### ISSUE TITLE
"sources created by user" is incomplete

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#642]
Under "my sources", the "sources created by user" only shows three test sources I made within NewCantus (where I have dozens on OldCantus--see below). This suggests to me that the OldCantus creator information is not being used in NewCantus, and users of the new site could lose their old "created by user" list.

<img width="1115" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/54b99ec1-eae9-4975-a6e7-04c0b1dde61a">

cf OldCantus:
<img width="949" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/3700a632-2804-4b81-9faa-f153410244de">

**Comment by annamorphism** [comment]
I guess this is really a consequence of #237 .

**Comment by jacobdgm** [comment]
Maybe it would be worth asking Jan about how to get at this information. Last summer, I recall @jiwoojeongjj, @jwang44 and I doing a fairly thorough search, and it was when we came up empty-handed that Junhao opened #237...

**Comment by annamorphism** [comment]
Interesting...today this is empty, and I can no longer find the test sources in question.  I don't remember deleting them...
<img width="1129" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/c251d1cc-2301-4ff4-b044-1bf39ead174e">

**Comment by jacobdgm** [comment]
@annamorphism is this on staging? @lucasmarchd01 deleted all the old sources and synced from OldCantus - now, the only sources on staging should be ones present on OldCantus as of a couple of days ago.

**Comment by annamorphism** [comment]
Ah that probably explains the disappearance.  My desire to see this populated with my old created sources still stands, though.

**Comment by jacobdgm** [comment]
Regarding getting creatorship information from OldCantus, I don't think there's any possibility of making progress on this issue unless someone is able to figure out #237.

Linking #737, because this seems directly to the discussion of "author" there.

**Comment by jacobdgm** [comment]
@lucasmarchd01, similar to my request on #644, when you get a chance, can you review the status of this one? Has this particular issue been addressed by the recent changes you've made to these pages?

**Comment by lucasmarchd01** [comment]
@jacobdgm although other particular issues related to the sidebar are now fixed, this one remains opened because of #237. Sources that are created on NewCantus will show up on this sidebar, but any sources created on OldCantus will not.

**Comment by lucasmarchd01** [comment]
Linking #825 here as it will most likely resolve this issue as well.

**Comment by lucasmarchd01** [comment]
Closing this issue as we have now synced the data from OldCantus with #825 in place
