### ISSUE TITLE
"My sources" sidebar and page should use siglum

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#643]
As noted in #438 the listed sources in the My Sources sidebar should use siglum and not rism_siglum.
On the /my-sources page, the table should also use siglum, and not the full shelfmark (to avoid the screenshot below):
<img width="716" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/151d7d4a-72f6-4dcc-a555-9214236e6169">

**Comment by jacobdgm** [comment]
mentioned in #438 - evidently the sidebar still doesn't use the siglum. Reopening.
