### ISSUE TITLE
"My sources" page and sidebar should match

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#644]
In principle, the  "My sources" page and the "My sources" sidebar should contain the same sources. But as noted in #438 the sidebar only contains six sources, and does not have an option to page through to any others. I am not sure why it is those six sources, either--perhaps they have me assigned in some particular role?--but this is not ideal behaviour. 

This is a bit broken on OldCantus too--it seems to show the first 50 sources alphabetically by siglum, also without a paging option. What we probably want is for it to show the first, say, ten sources, with the option to show the next ten. Probably most-recently-edited is a more useful ordering than alphabetical, too, though it *is* a change for anybody used to finding their particular source this way.

**Comment by jacobdgm** [comment]
@lucasmarchd01, when you get a chance, can you review the status of this one? Has this particular issue been addressed by the recent changes you've made to these pages?
