### ISSUE TITLE
"sources created by user" not present on homepage

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#645]
In investigating #644 I noticed that NewCantus does not have the additional list of "sources created by user" that OldCantus has below the "My sources" list on the landing page. This is probably only really relevant to people creating a lot of sources (me), but it is a change from OldCantus for people used to looking in a particular spot for their work.

[What would be nicer, really, would be to have "sources created by me" in one list, and "sources assigned to me" (as a proofreader, as a contributor, etc.) in another list. But replication before innovation!]

**Comment by jacobdgm** [comment]
I don't think we've made any effort to implement this (and it hasn't been on my radar at all, probably because I never created any sources back when I worked as an RA for CD!)

We may need to sort out #237 first...
