### ISSUE TITLE
Combine Chant and Sequence querysets in chant-search page. 

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#66]
Currently the chant search only has chant objects, but on old Cantus, the sequences are also searched in the same interface. 

See old Cantus https://cantus.uwaterloo.ca/search-all?op=contains&t=&genre=All&cid=&mode=&feast=&volpiano=All
and new Cantus http://206.12.93.196/chant-search/

It would be useful to combine the two querysets (i.e., chants and sequences) and start filtering from there. Note that `chant` and `sequence` models share some common fields but are not exactly the same.

**Comment by fujinaga** [comment]
Ask Debra, why they do not have exactly the same. fields. It may be a historical artifact. It may be better for the future to harmonize them to have the same fields, even if some of them are not always used.

**Comment by jwang44** [comment]
Sure. I will do that.

**Comment by jwang44** [comment]
harmonize the two models to have the same fields: b70f357dcc3754fdd22d7a23013d59c3643cef64
combine sequence and chant querysets: c7da5a24388e24d5378d09d9d49f18758bb374f9
