### ISSUE TITLE
Something has broken in displaying concordances on the Chant Detail Page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#662]
![Screenshot 2023-05-25 at 10 36 26 AM](https://github.com/DDMAL/CantusDB/assets/58090591/952960a3-73ee-40e8-93cd-a982b721e295)

This is on the `develop` branch

**Comment by annamorphism** [comment]
For what it's worth the concordances tool doesn't work on OldCantus right now either (it has an 
under maintenance" message and a somewhat frustrating link to the Index that doesn't really lead to that chant's ID page e.g. https://cantusindex.org/ci/006129?c=1) .

**Comment by jacobdgm** [comment]
This seems to be a problem just on our `develop` branch - it was only occurring locally, and when I switched to the `staging` branch, things started working fine again...
