### ISSUE TITLE
Is jQuery really necessary?

### ISSUE THREAD

**Issue by napulen** [DDMAL/CantusDB#68]
I am not super convinced that jQuery is the way to go

https://github.com/DDMAL/CantusDB/blob/e25b426bdf67110122f76a6adab54465eead240a/django/cantusdb_project/main_app/templates/chant_detail.html#L269

Just in case it wasn't clear, jQuery is not necessary for AJAX requests. Here is a standard snippet without jQuery:

```javascript
<script>
function loadDoc() {
  const xhttp = new XMLHttpRequest();
  xhttp.onload = function() {
    document.getElementById("demo").innerHTML =
    this.responseText;
  }
  xhttp.open("GET", "ajax_info.txt");
  xhttp.send();
}
```

**Comment by jwang44** [comment]
OK. If we really want to kick jQuery out, that's ok. It's not necessary. It's just that the tutorials I found online about implementing ajax tend to use jQuery, and we happen to already have a CDN for it in the code. The CDN has been there for a long time, and I'm not 100% sure whether we have anything else in the code base that relies on it. Could you please elaborate on why jQuery is not the way to go?

**Comment by fujinaga** [comment]
We try to minimize our reliance on third-party libraries in general, because we've had so much trouble maintaining codes for any extended period. You are perfectly welcomed to use any libraries for testing and prototyping but we prefer that we minimize their use in production.

**Comment by jwang44** [comment]
Sure. I see. I will remove jQuery and rewrite that part of the code.

**Comment by napulen** [comment]
I didn't know it was already being imported. Do you know what is being done with jQuery in other parts of the code? Just curious

**Comment by jwang44** [comment]
I don't think it has been used much in the code, but not entirely sure. I will check.

**Comment by jwang44** [comment]
It is also used in this and several other places. They are for the sole purpose of keeping the GET parameters on the form. https://github.com/DDMAL/CantusDB/blob/e25b426bdf67110122f76a6adab54465eead240a/django/cantusdb_project/main_app/templates/feast_list.html#L9

Example scripts: 
```javascript
<script>
    // Make sure the select components keep their values across multiple GET requests
    // so the user can "drill down" on what they want
    window.onload = function () {
        $("#month-filter").val("{{ request.GET.month }}")
        $("#order-by").val("{{ request.GET.ordering }}")
        $("#date-filter").val("{{ request.GET.date }}")
    }
</script>
```

and
```javascript
<script>
    // Make sure the select components keep their values across multiple GET requests
    // so the user can "drill down" on what they want
    window.onload = function () {
        choice = "{{ request.GET.mass_office }}"
        if (choice == "Mass") {
            $("#mass_choice").prop("checked", true);
        } else if (choice == "Office") {
            $("#office_choice").prop("checked", true);
        } else {
            $("#any_choice").prop("checked", true);
        }
    }
</script>
```

Similar code is used on every search/filter form, but I think we can come up with some pure javascript to replace them.

**Comment by fujinaga** [comment]
You don't need to replace them right away. Put an issue up to fix later whenever you see jQuery being used.
Make the whole thing work first.

**Comment by jwang44** [comment]
Sure. Got it.
