### ISSUE TITLE
Chant List table header appears and is smushed when no chants are returned

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#688]
If no chants pass the series of filters passed by the user on the chant list page, the header of the chant result table still shows up and is oddly proportioned on the page- 

On staging: 

<img width="1215" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/b3dea17b-ea5e-4912-8fe7-06a1aa5a2da8">

**Comment by jacobdgm** [comment]
This is the right page, correct? http://206.12.93.196/chants/?source=123713&genre=125
