### ISSUE TITLE
`IndexError` in syllabization and alignment

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#689]
I just found this poking around on staging...I don't know how many chants this might be true for: `/chant/396856`.

<img width="1414" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/a9c12f04-ae46-49ed-a4b1-30379b4c6258">

I navigated to this page by following a link on the chant search page, specifically: `/chant-search/?op=contains&order=has_melody&sort=asc`

**Comment by annamorphism** [comment]
Strange. That chant seems to break regardless of how you access it (e.g. directly from the inventory of the source); it works fine in OldCantus, for what it's worth. 
Same breakage happens to the  next item in your search results, http://206.12.88.113/chant/521098. Not sure what they have in common...

**Comment by jacobdgm** [comment]
for both of these chants, `chant.volpiano` is `\n` (i.e. just a line break character) lol

This should not be too hard to fix. Nice catch!
