### ISSUE TITLE
Chant Search table overflows on smaller windows/screens

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#690]
Found on staging on Desktop Chrome v114.

The chant table overflows on narrower windows. Perhaps this is a good case for a horizontal scroll on overflow?

<img width="686" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/5601c623-2713-4c82-bf58-ea877a2d5a88">

**Comment by jacobdgm** [comment]
if I recall, this is a deceptively tricky issue, but I've had success fixing things like this by using `style="display: table;"`. Maybe this will be helpful here.

**Comment by dchiller** [comment]
In developer tools, I just put the table in a `div` with `style="overflow-y:auto"` and it scrolled horizontally on small windows.

**Comment by jacobdgm** [comment]
see also #493, #367
