### ISSUE TITLE
Different `Diff` values in Manuscript Inventory for `NewCantus` and `OldCantus`

### ISSUE THREAD

**Issue by jackyyzhang03** [DDMAL/CantusDB#693]
Not sure if this is an issue, but I noticed that the `Diff` values are different in `NewCantus` vs `OldCantus` manuscript inventory/index.

NewCantus (http://206.12.88.113/index/?source=123611)
<img width="1440" alt="Screen Shot 2023-06-05 at 2 32 40 PM" src="https://github.com/DDMAL/CantusDB/assets/81784897/a2a1eec0-0ca4-41d2-85e7-a8ac06cfeef4">

OldCantus (https://cantus.uwaterloo.ca/index?source=123611)
<img width="1128" alt="Screen Shot 2023-06-05 at 2 34 40 PM" src="https://github.com/DDMAL/CantusDB/assets/81784897/36b595fd-b4b2-4b15-8cc8-5ceee7b9971c">

**Comment by annamorphism** [comment]
Interesting. The Second image (from OldCantus) is the "DifferentiaeDatabase" value, which is a comparatively recent addition to OldCantus. We probably want to show that in cases where it exists (not sure about cases where it doesn't).

**Comment by jacobdgm** [comment]
We should see whether this resolves itself once we've finished syncing data. @lucasmarchd01, can you check in on this once you've finished the data syncing process?

Edit: we've done the final data sync, and this is still not correct. I think OldCantus displays the value in our `differentia_database`, while we display the value in our `differentia`.

**Comment by jacobdgm** [comment]
Debra requested that both the current "Diff" column _and_ a "DD" (i.e. differentiae database) column be included on the inventory page.

She also requested that the value in the DD column be a link to the relevant page on https://differentiaedatabase.ca. (and in general, we can go ahead and add links to relevant pages - feast, genre, etc. - on this page and elsewhere - the more connectivity, the better)
