### ISSUE TITLE
Scroll to top button in `Browse Sources` present in `OldCantus` but not in `NewCantus`

### ISSUE THREAD

**Issue by jackyyzhang03** [DDMAL/CantusDB#695]
When browsing sources, there is a button to scroll to the top of the page in `OldCantus` that is not present in `NewCantus`. Not sure if this was intentionally left out.

OldCantus (https://cantus.uwaterloo.ca/sources)
<img width="1022" alt="Screen Shot 2023-06-05 at 3 20 07 PM" src="https://github.com/DDMAL/CantusDB/assets/81784897/55425361-96a5-4339-877b-2fed15320ffd">

NewCantus (http://206.12.88.113/sources/?segment=4063)

<img width="1168" alt="Screen Shot 2023-06-05 at 3 20 59 PM" src="https://github.com/DDMAL/CantusDB/assets/81784897/2c3f1b61-625e-4ae5-a424-0a15feaa9b52">

**Comment by jacobdgm** [comment]
Sites with pages with "scroll to top" buttons feel very quaint and old-timey to me. I'd advocate for leaving this out, as it's hardly a vital feature. I'll close this for now as and note the difference between OldCantus and New; @annamorphism or @fujinaga, feel free to re-open this issue if you think we should include this.

Thanks for pointing this out, @jackyyzhang03!

**Comment by fujinaga** [comment]
Please ask Debra if she wants this.
