### ISSUE TITLE
Genre dropdown list formatting is strange

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#699]
In the chant create page, the genre dropdown list has strange behaviour for some of the genres. We should reformat this dropdown menu to display the shorthand notation only without the entire string representation.

![image](https://github.com/DDMAL/CantusDB/assets/71031342/e6b70180-f8f2-4493-b140-9e0b2ef5647f)

**Comment by annamorphism** [comment]
Just noting that OldCantus has no brackets here except for those items given in double brackets in NewCantus (for categories that are discouraged for new entries.). Hopefully this is taken into account in the shorthand notation on NewCantus.

**Comment by jacobdgm** [comment]
@lucasmarchd01 was this fixed by #703?

edit: it seems like it should have been; not sure why GitHub didn't handle this on its own. Closing.
