### ISSUE TITLE
404 error when attpemtping to navigate to Cantus Planus page

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/CantusDB#70]
On the thrid section of the homepage, a user may be directed to Cantus Planus page.
In production the hyperlink leads to here: https://www.uni-regensburg.de/Fakultaeten/phil_Fak_I/Musikwissenschaft/cantus/
In staging the hyper link leads here: https://www-app.uni-regensburg.de/Fakultaeten/PKGG/Musikwissenschaft/Cantus/CANTUSPLANUS/

**Comment by jwang44** [comment]
They must have changed the url. I just updated the homepage. It should be correct now.
