### ISSUE TITLE
Logo image not loading in `NewCantus`

### ISSUE THREAD

**Issue by jackyyzhang03** [DDMAL/CantusDB#705]
I noticed that the MARGOT logo does not seem to load in `NewCantus` production.

<img width="1440" alt="Screen Shot 2023-06-06 at 4 30 27 PM" src="https://github.com/DDMAL/CantusDB/assets/81784897/ee0d4c62-80de-41ec-ad50-380da2146d6f">

**Comment by jacobdgm** [comment]
Nice catch. Fixed!
