### ISSUE TITLE
Feast information is different in `NewCantus` vs `OldCantus`

### ISSUE THREAD

**Issue by jackyyzhang03** [DDMAL/CantusDB#707]
It appears that the list of most frequent chants, as well as the list of sources containing the feast is different in `NewCantus` compared to `OldCantus`.

OldCantus (https://cantus.uwaterloo.ca/feast/2360)
<img width="958" alt="Screen Shot 2023-06-06 at 4 52 40 PM" src="https://github.com/DDMAL/CantusDB/assets/81784897/4a11395b-b629-4e56-b5f2-ca015a5143ad">

NewCantus (http://206.12.93.196/feast/2360)
<img width="1111" alt="Screen Shot 2023-06-06 at 4 52 33 PM" src="https://github.com/DDMAL/CantusDB/assets/81784897/618d4d75-f049-4c95-85bc-fa375e2557c2">

**Comment by jacobdgm** [comment]
This is probably a data issue - let's see whether this resolves itself once we finish syncing data.

@lucasmarchd01, can you check in on this once you've got the scripts working?

**Comment by annamorphism** [comment]
By the look of what's missing, it has to do with the published/unpublished status of the sources.  NewCantus is hiding Princeton MS 245 (unpublished) and several other unpublished sources--which I think is intended.

**Comment by jacobdgm** [comment]
This makes sense - thanks, @annamorphism! @jackyyzhang03, to explain, we have a simplified system of deciding which sources to display, which accounts for this discrepancy (thanks, though, for opening this!). Closing.
