### ISSUE TITLE
Case where ci-search works differently in Old and New Cantus

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#709]
I seemed to have happened upon an idiosyncratic difference between Old and New Cantus. For most search strings I have tried, this error does not seem to be reproducible, however: 

On NewCantus, `/ci-search/laud` returns two results:
<img width="1440" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/4cc05125-5daa-43cc-9b0d-d822dcc4abf0">

On OldCantus, `/search-cantus?value=laud` returns many results:
<img width="1440" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/2dba8858-07b2-4399-9f9f-42780583b942">

I wonder if this has something to do with the errors when requesting from Cantus Index? I don't have an account on NewCantus, so maybe this won't be the case there.

**Comment by annamorphism** [comment]
It seems to be looking for the exact string rather than a partial one, so we don't get all the "lauda" "laudate" etc chants that OldCantus does. Reproducible on all sorts of strings ("Luca" \neq "Lucas", for example--in NewCantus "Luca" has 4 results and "Lucas" 8, but in OldCantus you get 16 for "Luca" and 8 for "Lucas").

**Comment by annamorphism** [comment]
also note that OldCantus lets you search things like "ra men" (giving you chants with "...libera mentes..." and the like) which has no results in NewCantus.

**Comment by fujinaga** [comment]
You're making me hungry!

**Comment by jacobdgm** [comment]
With @lucasmarchd01 having recently updated the database on staging, I tried this again. We still get just two results, so this appears to be a proper bug and not a data issue.

**Comment by dchiller** [comment]
It's different...that's fine!
