### ISSUE TITLE
options in feast selector on "browser chants" page

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#71]
The feast selector contains options constructed by aligning folios and feasts. 
Example: https://cantus.uwaterloo.ca/chants?source=680970&folio=001r
The options in the selector seem to be all the feasts in a manuscript aligned with the first folio in that manuscript where each feast occurs. However, some feasts appear more than once in the selector. This can be hard to implement. Is it ok to confirm this feature with the Cantus people before implementing it, @fujinaga ?

**Comment by fujinaga** [comment]
What are some examples of feats that appear more than once?

**Comment by jwang44** [comment]
Same link in the issue. On the right side of the page, there's a folio selector and a feast selector. If you click on the feast selector, you see some repeated ones. 
![Screen Shot 2021-08-12 at 10 15 36](https://user-images.githubusercontent.com/54256124/129212681-5e9200df-d03b-49a1-b9f6-84dd5514ed4d.png)

**Comment by fujinaga** [comment]
It looks like the name of a feast is listed until it changes in the manuscript. For example, all the chants from the beginning (001r) until 004r all belong to "XI milium Virginum”. Then in 004r it changes to LACUNA for one chant, then goes back to "XI milium Virginum”.

**Comment by jwang44** [comment]
Sure. I will try to implement it like this. Thank you.

**Comment by jwang44** [comment]
Implemented in ef3fe6504c4db5ec616b3459b3dae229eea9cf91. For speed considerations, we may need to store the list of folios and the list of feasts with corresponding folios in the database.
