### ISSUE TITLE
Deleting chants on NewCantus gives `404` Error

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#710]
To reproduce: 

- Create a new chant associated with a source.
- Navigate to the chant edit page for that source.
- Click "Delete"

<img width="1440" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/5a1c80ef-f59b-4174-99d8-28e45ed5ed8f">

This may be related to #481 (closed) and #486 (and possibly others). In any case, if the delete functionality is not desired, the delete button should be removed.

**Comment by dchiller** [comment]
For what it's worth, it seems that the chant is still deleted.

**Comment by jacobdgm** [comment]
Ah, we need to figure out what to do with all the {model} delete pages which are not implemented or partially implemented...

This is a good catch - thanks!

**Comment by lucasmarchd01** [comment]
Maybe hide the delete button if it's not fully implemented?

**Comment by jacobdgm** [comment]
I just sent Debra an email asking whether we want chant/source/etc. delete views.

**Comment by jacobdgm** [comment]
Also - this is directly related to #711 - we redirect to /edit-chants/, and once the last chant is deleted, there are no chants remaining in the source.
