### ISSUE TITLE
When selecting a folio of a manuscript, "Source" name is briefly wrong

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#717]
Steps:
1. Select a source, either from the "Browse sources" dropdown menu on the home page or the "Cantus Sources" page;
2. Select any folio from the dropdown menu;
3. When the page loads, the "Source" will briefly be A-Gu 1584, before switching to the source it actually is.
4. This will keep happening every time you select a new folio. It will also happen if you use the little folio navigation arrow thingies on the right of the dropdown menu.

It would seem that regardless of the source, A-Gu 1584 shows up first. The longest it took to change was 3 seconds.

Demo:

https://github.com/DDMAL/CantusDB/assets/83373378/9c1eb272-5a3f-43ad-8bf8-c7fd85a7abd6

**Comment by annamorphism** [comment]
I ran across this in the wild today, and momentarily thought I'd clicked on the wrong thing because I didn't have the source name I expected! Fascinating and mildly annoying.
