### ISSUE TITLE
Browse Chants Page: When no chants meet filter criteria, we should display a "No Chants Found" message

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#718]
Steps:
1. Select a source;
2. Select a folio from the dropdown menu;
3. Select a feast from the dropdown menu;
3.1 If the manuscript _doesn't_ contain that feast: In OldCantus, you get a "No chants found" message that clears everything up, but in NewCantus you don't get any message, so the page sort of looks like it forgot to load.
3.2 If the manuscript _does_ contain that feast: using Chrome, you get a page that contains the feast you searched for (yay). Using Firefox, you get the same empty page you would get if the manuscript didn't contain the feast.

Demo: comparison of searching for a feast that the manuscript _doesn't_ have, first in OldCantus, then in NewCantus (notice A-Gu 1584 not minding its own business again https://github.com/DDMAL/CantusDB/issues/717).

https://github.com/DDMAL/CantusDB/assets/83373378/b44dd842-92ea-46a4-ae0a-a347717f8257

**Comment by JoyfulGen** [comment]
Update: the above also applies for searching with the Genre dropdown menu. If the manuscript doesn't contain the genre you searched for, NewCantus doesn't give you a "No chants found" message.

**Comment by lucasmarchd01** [comment]
I couldn't replicate 3.2, but the other issue should be a simple fix.
