### ISSUE TITLE
Links to unpublished sources should not appear on Provenance detail pages

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#724]
Example: visit http://206.12.93.196/provenance/3665 (while logged out), click on first link. We get a 403 Forbidden error, since the source is unpublished.

Unpublished sources should not be listed on the Provenance Detail page.

Credit to @zhannaklimanova and her link checker script for catching this bug!

**Comment by annamorphism** [comment]
just out of curiosity--how complicated an exercise would it be to have a page like this one list the *names* of all the sources, but only have the published ones be *links*?

**Comment by jacobdgm** [comment]
> just out of curiosity--how complicated an exercise would it be to have a page like this one list the _names_ of all the sources, but only have the published ones be _links_?

This would be easy!

**Comment by annamorphism** [comment]
oooo. I may confer about this...
