### ISSUE TITLE
"Contributor" is empty in source sidebar

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#737]
The sidebar for a source is supposed to show some basic facts about it, including the editor(s) actively working on it. 
<img width="340" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/cdcd8b5e-d0d8-4603-b0d1-bc21cdabfdb4">

In NewCantus "Contributor" is empty (though it should have me linked, in this case).

<img width="358" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/a4894cb2-1a92-47bd-8718-95c9a3c553bd">

**Comment by jacobdgm** [comment]
@annamorphism do you have a URL for this?

Edit - I found it - http://206.12.88.113/source/710076 / https://cantus.uwaterloo.ca/source/710076 - I just wasn't logged in. But in the future, URLs are really useful!

**Comment by jacobdgm** [comment]
Also, do you have any idea what "Author" means (for sources with "author"s)? Is that meant to be the person who created the source?

**Comment by jacobdgm** [comment]
The empty "Contributor:" is absolutely a thing that someone partly implemented in the past but never finished - currently, in our template, it always generates a no-text link that doesn't appear because there is no text inside it.

**Comment by jacobdgm** [comment]
Drafting a specification for this sidebar, based mostly on what we already have in our template - tell me if this looks right @annamorphism (if not, you can describe the suggested/necessary changes and/or edit it directly)

```
{% if source has a provenance %}
    { link to provenance }
{% endif %}

{% if source.date %}
    Date: 
    { links to all associated centuries } | source.date
{% endif %}

{ source.cursus (only if source has a cursus) }
{% if source has associated notations %}
    { links to all notations }
{% endif %}

{% if user is logged in, and source has a source_status %}
    Source status: { source.source_status }
{% endif %}

{% if source has any "inventoried by"s %}
    Inventoried by: { links to all "inventoried by"s }
{% endif %}
{% if source has any proofreaders %}
    Proofreader{ s }: { links to all proofreaders }
{% endif %}
{% if source has any contributors %}
    Contributor{ s }: { links to all contributors }
{% endif %}

{ source.indexing_notes (only if it has indexing notes) }
```
Main change as to what we currently have now on NewCantus: we actually display the contributor(s), and move it above the indexing notes

Main differences vs OldCantus: We don't display an Author

Thoughts/questions: we keep track of "current editor"s, "full text entered by"s and "melodies entered by"s in our sources as well. It would be easy to add links to these among the proofreaders/contributors/etc., but let's not plan to add these links unless someone asks for them.

**Comment by annamorphism** [comment]
"Author" is weird in OldCantus; most sources don't have it, except for a handful of sources from Portugal. I'm guessing it was imported from some particular project, but it looks weird to have it blank for everything else. 
 Admins also have access to "authoring information" (a separate box), which in most cases is indeed the creator of the source object (see #237). (Or at least, it is by default, though you can manipulate it to be somebody else...). Conceivably this could also be used in the "author" slot in the source sidebar.

**Comment by annamorphism** [comment]
re: "indexing process": in OldCantus there is a field showing whether it is undergoing proofreading, partially indexed, etc. For NewCantus this could just be published/unpublished.

**Comment by jacobdgm** [comment]
I can't find any "author" information in OldCantus's API for this source: https://cantus.uwaterloo.ca/json-node/710076, so I think this is basically data we don't have access to.

That said, I see a `"name":"Anna de Bakker"`, which maybe has something to do with why your name is being displayed on this page?

**Comment by jacobdgm** [comment]
> "Author" is weird in OldCantus; most sources don't have it, except for a handful of sources from Portugal. I'm guessing it was imported from some particular project, but it looks weird to have it blank for everything else.
Admins also have access to "authoring information" (a separate box), which in most cases is indeed the creator of the source object (see https://github.com/DDMAL/CantusDB/issues/237). (Or at least, it is by default, though you can manipulate it to be somebody else...). Conceivably this could also be used in the "author" slot in the source sidebar.

Should we show "Author:" and display the source's creator? Or should we substitute "Creator:"?

> re: "indexing process": in OldCantus there is a field showing whether it is undergoing proofreading, partially indexed, etc. For NewCantus this could just be published/unpublished.

So, we should keep "Indexing process:" and follow it with either "published" or "unpublished"? Or should we substitute "Published status:"?

(I'm in favour of these labels exactly describing what's being displayed, even if it means the label is different from OldCantus. E.g. if a source's "author" isn't correct, and someone needs to go into the admin area to change it, they shouldn't need to guess that "author" is actually "creator")

**Comment by annamorphism** [comment]
I like "published status." 

The information in the json-node you linked seems to correspond to what is in the "authoring information" visible to admins, which is changed via an admin panel at the bottom--you type in a name and it matches it to the users, which I am guessing is why my name appears here in the json-node rather than my userID (which is used in 3 other places). It is called "authored by" in that interface, even if it is "creator" elsewhere... 
<img width="1404" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/49efced3-8feb-4f49-ad99-c38679905ed6">
I'm inclined to not bother with displaying the creator/author information, for now anyway.  What will that mean for the sources where this field appears to be filled in? 
<img width="975" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/56394aa9-0217-4918-a2ea-5ca4df28862f">

**Comment by jacobdgm** [comment]
Wait. We don't have a `contributor` field on our `Source` model at all. What is a "contributor"? Is is the union of "current editors", "full texts entered by" and "melodies entered by"? I.e. you show up among the contributors because you are a current editor?

**Comment by annamorphism** [comment]
Good question. No, "contributor" seems to be a single entity, even for sources with many people who worked on it, e.g. https://cantusdatabase.org/source/123717
<img width="314" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/102fe465-78db-4094-9ad2-d5d331f0de1b">
It appears to be the same as the aforementioned "authoring information", since it's also tied to OldCantus's user ID. Here "Cantus Database Administrator" is "admin", user ID 1; anonymously-authored sources seem to be blank, like so (https://cantusdatabase.org/source/123606) 
<img width="316" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/4bbb57b7-33f5-4e7b-ab87-ad616ffa0b3c">

**Comment by jacobdgm** [comment]
oh! "indexing process" corresponds to `source_status` in our database. So we can display this. Let's forget about "published status".

**Comment by jacobdgm** [comment]
In a video call with Debra yesterday, we arrived at the conclusion that "contributor:" should display the same information as "author:" visible elsewhere on the page (@annamorphism, can you confirm and/or clarify this? feel free to edit this comment in place).

We (developers working on NewCantus) are unsure where to get this data. Debra said she would check in with Jan to ask where we could get this. We're also waiting on Debra/Anna to figure out authorship information about certain Portuguese sources. (again, @annamorphism, can you clarify/correct as necessary?)

**Comment by annamorphism** [comment]
"Contributor" is the same as the "authoring information" which admins can change at the bottom of the page (as shown upthread.) This shows up as the second item in the json-node; e.g. I changed this source to have Jacob as the "creator" https://cantus.uwaterloo.ca/json-node/713114. The resulting node has Jacob's UID (1327) at the top and his name (presumably in case the typed information doesn't match a UID?) toward the end. 
<img width="1002" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/396992bc-c154-4f13-a1a2-bbf5618fe5a5">

Although I actually did create the source in the first instance, my own ID--12877--is only visible in the "revision" field (which is information never displayed to the public, although maybe it should be.) So my powers as admin let me override the information about the origin of the node (slightly troubling?). For chants I don't seem to be able to change the authoring information in the same way, but it shows up in the same spot(s): https://cantus.uwaterloo.ca/json-node/710867/edit

In both cases this uid is tied to the "contributor" name in the sidebar.

**Comment by annamorphism** [comment]
The "author" thing is weirder, since it only affects some sources. 

https://cantus.uwaterloo.ca/source/123732 for example, says it has "author: Kate". The "authoring information" at the bottom is "Anonymous" 
<img width="498" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/e0a4c93c-ba19-4301-a14f-1b7ed03ae223">
<img width="230" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/6c363a9a-88ad-4629-b651-0acf2aa4bf74">
Looking at the json-node (https://cantus.uwaterloo.ca/json-node/123732/) the uid at the top is "0" for Anonymous, in this case, but the text string "Kate" appears in a place normally reserved for an assigned indexer id:
"field_indexed_by":{"und":[{"value":"Kate","format":"plain_text","safe_value":"Kate"}]}

It's tempting to just re-assign these sources so that they have user-ids rather than indexer-ids associated with them, and then ignore this value...but that will require work on the part of assorted Debra(s).

**Comment by annamorphism** [comment]
further insight on what the sidebar calls "author": 
The admin view of all sources has "User name" and "User(old)". 
<img width="952" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/ab56225a-6a38-4a24-8e95-fdadc3f166a6">
The first links to a user profile, the second, when present, is just a name. Typically these are the same in some obvious way, but in a few the user is anonymous and only "user(old)" tells us who did the work. (In some cases they are both uninformative, but I'm not too concerned with losing information that isn't there in the first place.)
<img width="946" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/82dbecae-2ae8-4d7f-b3fc-d36edc00e3dd">
By the look of it this affected sources that were in progress at the last Cantus update; those that got their source pages changed in the meantime have gotten a user id associated, but about 15 are lingering with their ancient usernames associated and needing to be tied to current users. One or two may need dummy usernames created for them.
This is something to consult about with Debra (if these are still-unpublished sources by people who don't have a Cantus username anyway, can we just make them created by "admin"?)

**Comment by lucasmarchd01** [comment]
Linking #825 here as it will be relevant to fix this issue. We should use the "created_by" field to refer to the Contributor on NewCantus.
