### ISSUE TITLE
We need to sync users from OldCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#741]
We discovered yesterday that the [user synchronization process](https://github.com/DDMAL/CantusDB/wiki/Migrating-users-from-old-to-new-CantusDB) is not included in the main [data migration process](https://github.com/DDMAL/CantusDB/wiki/Data-migration-from-the-old-cantus-to-the-new-cantus) instructions. Further, the necessary script depends on several CSV files that are to be "obtained from Junhao".

There was some talk of manually making changes to the user list following the final data migration, but this is impractical because users will have been given access to sources - we don't want anyone (developer or Debra) to have to re-grant access to a bunch of necessary sources for a bunch of users.

@jwang44 has graciously agreed to try to do his best to recreate these files around when we do the final data synchronization. Many thanks, Junhao!

(UPDATE: the following is now complete) **We also need to update these scripts to assign users a random password** (which they will then be able to change via the password reset links), rather than a set placeholder as is done currently.

**Comment by lucasmarchd01** [comment]
We've assigned users random passwords and this has been completed.
