### ISSUE TITLE
Chant Search page: if no results found, we should display a message saying "no chants found"

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#757]
http://206.12.88.113/chant-search/?op=contains&keyword=sabr&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=

It looks as if there's been an error or as if it didn't make an attempt to search for chants containing the search term.

We've recently implemented messages like this on some other pages; we could also go through the rest of our pages to see whether there are other places where "no _ found" messages can be displayed.

**Comment by lucasmarchd01** [comment]
closed with #809
