### ISSUE TITLE
"Siglum" as used in the code is not the correct terminology

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#77]
A "siglum" (plural "sigla") is an identifier used to **uniquely identify a particular library or holding institution**. This comes from the RISM Sigla list, which can be searched here: https://rism.info/community/sigla.html

Sigla take the form of Country code, a dash, an indicator of a city in uppercase, and an indicator of an institution in lower-case. For example, "GB-Ob" means "Great Britain, Oxford, Bodleian Library". "GB-Lbl" is "London, British Library". Sometimes, in the case of larger national libraries, it is sufficient to indicate the library by the city; "D-B" is Germany, Berlin state library; "D-M" is for the Munich State Library. 

By contrast "Shelfmark" is a unique indicator for a given manuscript within an institution, and is based on an older method of filing books, where their location was based on a given physical shelf. A shelfmark might look something like "MS Canon Misc. 213", indicating that the book was number 213 on the "Canon Misc" shelf. 

It is common practice to combine the siglum and the shelfmark so that a complete indicator of institution is available to users, particularly in online databases. For example, "GB-Ob MS Canon Misc. 213". This, however, is still a **shelfmark** -- it uniquely identifies a source. Sigla only identify the institution.

I have noticed several cases in this application where the term "siglum" was used where I believe what is actually meant is "shelfmark". Particularly this comment:

https://github.com/DDMAL/CantusDB/blob/227daaecf4f585ec0afd2fc4547f72eda592133b/django/cantusdb_project/main_app/views/views.py#L324

This should be **shelfmark**. Sigla do not uniquely identify a source, they only identify which institution holds it.

I'm pointing this out because it may make its way to user-facing controls, and they will likely be confused by this use of terminology.

**Comment by jwang44** [comment]
Thanks, Andrew! I notice that on the old Cantus DB, there are things like [A-Gu 29](https://cantus.uwaterloo.ca/source/123610), [CDN-Lu M2150](https://cantus.uwaterloo.ca/source/123619), and [GB-Ob Laud Misc. 284](https://cantus.uwaterloo.ca/source/123707) in the "siglum" field, and that's what I've been using for the "siglum" field on the new Cantus DB. 
If I understand your comment correctly, these are all shelfmarks, instead of sigla. Does this mean the "siglum" field on the old Cantus is also incorrect?

**Comment by ahankinson** [comment]
Yes, I would say so but You should probably check with Debra

**Comment by jwang44** [comment]
Debra confirmed that there is a difference between the "RISM siglum" and the "siglum" field on the old Cantus DB. The RISM letters and the shelfmark are combined and put into the "siglum" field, which is used as a human-readable ID for the manuscript. 

We are planning to make some changes to the database design for the new Cantus DB, and this terminology issue will certainly be taken into account. But for now, I think I will keep this consistent with the design of the old Cantus DB. I will add some documentation about this terminology issue to the models, where the fields are defined.

**Comment by annamorphism** [comment]
@jwang44 I would say the current terminology is actually correct. A siglum is just a short abbreviation for some particular element of a larger set. A *RISM* siglum uniquely identifies a library within the set of "libraries known to RISM", and thus is tied to the location of a manuscript; but, for example, the siglum "W1" uniquely identifies a particular manuscript in the set "manuscripts with Parisian organum", and "El" identifies a particular manuscript (the "Ellesmere Chaucer") within the set "manuscripts containing the Canterbury Tales".  Editors sometimes make their own sigla to refer to particular manuscripts in the set "manuscripts used in this edition."  
So it is totally consistent terminology to have a siglum (short ID) that uniquely identifies some source within Cantus.

**Comment by jwang44** [comment]
For now, we stay consistent with the old Cantus, where the "siglum" field (human-readable ID) uniquely identifies a source.
