### ISSUE TITLE
Chant Detail Page: OldCantus has a "Differentia Database" field not present in NewCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#774]
related to #693, related to #701

OldCantus:
![Screenshot 2023-06-21 at 1 49 35 PM](https://github.com/DDMAL/CantusDB/assets/58090591/91b5d901-de23-44a4-864b-75785d23563a)

NewCantus:
![Screenshot 2023-06-21 at 1 49 24 PM](https://github.com/DDMAL/CantusDB/assets/58090591/833fe9bf-3104-45d9-a0bf-9a0f70a2612a)

**Comment by annamorphism** [comment]
note that you CAN add it into the chant-edit page
<img width="726" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/e7f05ac4-98f6-453e-aae4-676bae9cd681">

**Comment by jacobdgm** [comment]
okay, so we need to figure out how to get the data for this field.

**Comment by jacobdgm** [comment]
Based on a video call with Debra yesterday, some further information on this:

We're pretty sure this matches the `differentia_new` currently in our database. We should verify this, and then consider renaming this field to `differentiae_database`.

We need to figure out how to turn the code currently stored in the table into the bit of volpiano currently displayed on OldCantus. Presumably, there's an API on differentiaedatabase that returns the volpiano.
