### ISSUE TITLE
remove edit links when permissions are wrong

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#775]
As an admin, I can edit every _source_ in NewCantus. However, I can't edit any chants in the source, from any of the pathways (edit-chants in the sidebar, directly on an existing chant-view, from the "view all chants" page, etc.) This means an admin can't just make a quick fix on any chant they spot an error in, which is a change from OldCantus.

**Comment by jacobdgm** [comment]
What is an "admin", and are you sure you're one? Here's a screenshot from the Admin area on staging showing all the permissions-related things I'm aware of: we have three groups that we've set up, and two togglable settings that come built-in with django. 
![Screenshot 2023-06-21 at 4 18 23 PM](https://github.com/DDMAL/CantusDB/assets/58090591/bf283bf8-c521-4be1-9ef6-478777a3cbf4)
(In principle I could do it via the command line, but i can't currently verify your account's groups/permissions in the Admin area due to #587)

**Comment by annamorphism** [comment]
I mean what OldCantus calls a "Debra" (referred to as "admin" in some parts of the old site, e.g. the menu for viewing all sources.)  On further inspection, I don't seem to have access to as much as I thought--which is a different problem [i.e. making sure that people's status can be checked and/or modified, especially in the event they somehow lose permissions they had previously.] Once #587 is dealt with, we can test these kinds of problems.
Revising my earlier statement:  I can see the "edit" button and the "volpiano editor" for sources (which leads to a 403), but it's hidden from me for chants. This led me to think I had edit access to things I didn't, so we want to hide these links in both cases.

**Comment by jacobdgm** [comment]
If I recall, I applied as many elevating-privileges things to your account, which was making you a superuser and staff and maybe some other things. For some of the links, we display (or don't display) them based on what groups you're in - perhaps you're not technically in the project manager group.

**Comment by annamorphism** [comment]
For now I am not so concerned with what privileges I actually have or don't have, but that I'm being shown things I don't have privileges for. If this affects others (I don't know to what degree it does) I'm imagining a lot of people reaching 403s and getting confused, when the link could be hidden in the first place.

**Comment by jacobdgm** [comment]
I just checked - this is set up properly for the chant detail page, but not for the sequence detail or the source detail pages. If a user is logged in, they'll be shown the "Edit" link, whether or not they can access the linked-to page. We need to fix this.
