### ISSUE TITLE
Removing editors

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#788]
Currently one can add editors from the edit-source page, but there is no way to remove them. 
Debra writes:
> "It would be nice to have a "--none--" option for the editors and melodies entering etc. names on the Create Source page. I just clicked on someone and then decided I didn't want them credited with it, but I couldn't remove the name by clicking it. So, I would want a "none" at the top of the list to get back to nothing."

**Comment by lucasmarchd01** [comment]
This issue has been resolved with the use of autocomplete widgets that allow you to de-select editors. (#970)
