### ISSUE TITLE
We should add a new page to credit developers of NewCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#799]
In a video call with Debra yesterday, she suggested/requested we add a page crediting all the people who contributed to NewCantus, @jwang44, @jiwoojeongjj, @lucasmarchd01, @blueNoteb5, @jacobdgm, and any others I'm forgetting at the current moment. Jan should probably be on this list too for all the work he did on OldCantus.

This would also be a good place to add a link to this GitHub repo.

**Comment by dchiller** [comment]
It looks like all of these people except Jiwoo are acknowledged on the Acknowledgements page. I just made some formatting changes and added them to the list there (these edits are made through the flatpage).
