### ISSUE TITLE
We can improve the Admin area

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#800]
During yesterday's video call with Debra, she went through a couple of normal editing/administrative tasks she's used to doing in OldCantus. As she did them in NewCantus, she had several suggestions as to how the Admin Area could be improved to make it easier to interact with.

General:

- [x] - it would be helpful to have required fields marked with asterisks
- [x] - ensure that on the various admin list pages, there's a search box at the top (the models that Debra noted were sources, provenances and feasts)
- [x] - We should make sure as many relevant columns as possible are included on the list pages for easy sorting/finding.

Users:

- [ ] - we should hide the checkbox that would allow Debra to turn a user into a superuser
- [x] - currently, the "staff status" checkbox is above the fields for assigning people to groups. We should move the "staff status" checkbox below the groups fields.
- [ ] - We should make the Full Name field required, and eventually hide the First Name and Last Name fields once we finish implementing #168.
- [x] - on the user list page, we should include a "full name" column (the `full_name` field is where indexers' names are kept, and it's hard to find an indexer if their full name is not displayed).
- [x] - On the user detail page, we should ensure the lists of sources (i.e. where the user can be added as an editor/proofreader/entered-melodies-er, etc.) are sorted alphabetically. It could be helpful for these to be filterable lists as well (if they're not already filterable lists)
- [x] - on the source list page, we should ensure the sources are sorted by sigla, and that there's a box at the top to search for sources.

It may be worth thinking about making a second admin area where we keep options like Users's "superuser" checkboxes, the "sites" area, etc. We could give this its own distinct URL (`/dev-admin/`?), but not include any links to it; its purpose would be to allow developers to change things as necessary like the site configuration.

**Comment by annamorphism** [comment]
Debra specially requests a search for sources, to make it easier to give people permissions to edit:

"
http://206.12.93.196/admin/main_app/source/

Could we please have a search box for this list? Or if it's sorted in alpha order that would also be fine.

(I was also trying to go to "user" and add a source to someone that way, but those are also not in any particular order so it was difficult to find the source since we have so many. That's when I thought maybe I was to go to "source" and add a user.)"

**Comment by jacobdgm** [comment]
> Could we please have a search box for this list?

I've added this and another item or two to the bottom of the list. Thanks for these suggestions/reminders!

**Comment by lucasmarchd01** [comment]
> we should hide the checkbox that would allow Debra to turn a user into a superuser

We have decided that this functionality doesn't really make sense, so we won't be implementing.
> We should make the Full Name field required, and eventually hide the First Name and Last Name fields once we finish implementing https://github.com/DDMAL/CantusDB/issues/168.

We have made a note in our admin page that we're only using the full name representation on our website and the first and last name fields are maintained as data from OldCantus
