### ISSUE TITLE
Cry for help: deleting one of "My Sources" is not obvious (in fact... I can't figure it out)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#804]
As an editor on Cantus, I can "Add new sources," and add chants to those sources. This function works, because I have successfully done so. However, I now can't make my source go away.

I can delete individual chants (see below), but I can't find where I can delete the entire source.

<img width="758" alt="Deleting a chant" src="https://github.com/DDMAL/cantus/assets/83373378/0c864ea7-df34-423c-b985-3214f9a724ff">

So I guess there are two possible issues here:
1. If it's actually not possible to delete a source once you've created it, it'd be great for that to be possible.
2. If it is possible to delete a source, then perhaps the "Delete" button should be somewhere more obvious to dumb users like me.

**Comment by dchiller** [comment]
@JoyfulGen I transferred this from the Cantus Ultimus repo to CantusDb repo. But for what it's worth, I have not figured out how to do this with the fake sources I created...

**Comment by annamorphism** [comment]
I refer you both to #486 . 
In Debra's email she restricted source-deletion to "higher ups" (admins and proofreaders). I think being able to delete your own created source should probably be included, if it's something you can do on OldCantus (I can check if this is the case on a non-admin account, unless @JoyfulGen or @dchiller can confirm?). Maybe this is an intentional change, or maybe it is an oversight in the directives--I will ask.

**Comment by dchiller** [comment]
> I refer you both to https://github.com/DDMAL/CantusDB/issues/486 .

Ah nice -- ty!

> I think being able to delete your own created source should probably be included, if it's something you can do on OldCantus (I can check if this is the case on a non-admin account, unless @JoyfulGen or @dchiller can confirm?).

Just confirmed that I *can* delete a source I created in OldCantus. FYI: this is not listed with other known and intentional differences.

**Comment by JoyfulGen** [comment]
> I refer you both to #486 . In Debra's email she restricted source-deletion to "higher ups" (admins and proofreaders). I think being able to delete your own created source should probably be included, if it's something you can do on OldCantus (I can check if this is the case on a non-admin account, unless @JoyfulGen or @dchiller can confirm?). Maybe this is an intentional change, or maybe it is an oversight in the directives--I will ask.

As a professional goof who likes to make chaos-inducing mistakes, I can confirm that being able to delete your own resource would be very useful. I can imagine doing something stupid (refer to Fake Einsie mayhem) and wanting to make it disappear quickly and without notice.
