### ISSUE TITLE
NewCantus generally slower to load than OldCantus (examples provided)

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#811]
There are several issues (https://github.com/DDMAL/CantusDB/issues/513, https://github.com/DDMAL/CantusDB/issues/544, https://github.com/DDMAL/CantusDB/issues/587, https://github.com/DDMAL/CantusDB/issues/748, https://github.com/DDMAL/CantusDB/issues/802) mentioning isolated cases of a NewCantus page loading slowly, but I feel like many pages generally load slower on NewCantus, so I clicked on various things in New vs. OldCantus to compare their loading speeds. Major discrepancies are in little code boxes. Please enjoy:

What I clicked on | OldCantus time | New Cantus time
--- | --- | --- 
From the home page, click on "Melody Search Tool" | 1 sec | 1 sec
From the home page, select CH-E 611 from the "Browse Sources" dropdown menu | 1 sec | `6 secs`
From the main CH-E 611 page, select folio 003r from the dropdown menu | 2 secs | `6 secs`
Reload that page | 2 secs | `6 secs`
Select "Cantus Sources" from the overhead menu | 2 secs | 2 secs
In Chant Search, select "Contains" and then keyword "ave" | 4 secs | `502 error`
From the List of Feasts, click on the first feast | 1 sec | 2 secs
Thence, click on the first "Source containing the feast" | 2 secs | `502 error`
Back to that previous feast, now click on the "11" at the top of the rightmost column | 2 secs | `6 secs`
Thence, click on the first chant ("Intret") | 2 secs | `16 secs first time, then consistently 6`
Back to the main CH-E 611 page, click on "View all chants" | 3 secs | `inconsistent: 16, 43, 12, and 15 secs`
Log in | 2 secs | 2 secs

Without having tested it super strictly, it also seems that NewCantus doesn't like to be rushed. If I click on several things in quick succession, it slows down significantly. I also have gotten several 502 errors at inconsistent moments that could have been related to my over-enthusiastic clicking (these are hard to reproduce, so I don't currently have more data).

EDIT: I figured it out! Random 502 errors are due to site inactivity https://github.com/DDMAL/CantusDB/issues/813.

I think that gives a general idea. I hope it's useful! (Let it be known that I got to use the word "thence" for this issue and enjoyed that very much).

**Comment by annamorphism** [comment]
Excellent chart, @JoyfulGen ! I will see if I can add to/replicate some of these things.

**Comment by jacobdgm** [comment]
Just tried running through your table of timings, Gen. On Production, everything seems to be similar to (or slightly faster than) OldCantus.

@JoyfulGen, are we good to close this?
Looking forward to discovering that you think all the pages listed are better now, and thence (ughh... what a stretch...) that you have closed the issue ^^

**Comment by JoyfulGen** [comment]
@jacobdgm such speed!!! I also went through everything and it looks great. Closing issue now :)))
