### ISSUE TITLE
Redirect user to source detail page after they create a source

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#814]
As mentioned in Kathleen's email with feedback on our production and staging severs.

When a source or chant is created, we display a success message but with an empty form still on the source/chant create page. This is confusing to users because it looks like none of the data saved into their source. Instead, we should redirect them back to the source/chant detail page after they save. A similar issue has been addressed here (#665) from the chant edit page, so we need a similar functionality on the source and chant create pages

**Comment by annamorphism** [comment]
I agree this should be the case for source-create. On chant-create this is just the behaviour of OldCantus (I think) and is useful for adding a lot of chants in a row--perhaps Debra can confirm whether we would like to change this feature.
