### ISSUE TITLE
Suggested chant ID button not working

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#815]
I am copying this issue mentioned in Kathleen's email from notes on the production server. I was not able to replicate this issue, the ID button works fine for me, but this is worth investigating what might be causing this.

"For both the newly added source and the previously started source, Production site brings up the suggested chants that might follow BUT clicking on the desired ID button does not work. The Input tool works, so I used that, but having the suggestions available to select if correct is better!"

**Comment by jacobdgm** [comment]
Trying this on production now (as I did last month), I'm not able to recreate this bug. Testing in Safari, Chrome and Firefox, it works on all three browsers. So I'm not sure what to do about this.

@fujinaga, do you have any suggestions? Should we email Kathleen and ask her to try again, and give us more information on browser/OS/etc. if it's still broken for her? Or should we just close this issue?

**Comment by fujinaga** [comment]
We should always reply to users immediately then when things are fixed, you should check with them to make sure that things look good from their end.

**Comment by jacobdgm** [comment]
I emailed Kathleen saying that this should be working now, and asking her to send us more information if it still seems broken. Closing this for now; we can reopen it if Kathleen still finds this not to be working.
