### ISSUE TITLE
Remove acknowledgement to Matthew Spencer

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#820]
The Acknowledgements page on NewCantus acknowledges the latin syllabifier of Matthew Spencer (Cantus Ultimus uses this syllabifier). However, that is not the automatic syllabifier used on NewCantus.

![image](https://github.com/DDMAL/CantusDB/assets/11023634/cd394b1f-e6ee-4847-89c6-8104fa852e94)

**Comment by jacobdgm** [comment]
Good catch!

I've updated this on both staging and production. @lucasmarchd01, take note that when we do the final data sync, we'll need to either update this locally, or take a copy of the database from production so that this change to this flatpage is preserved!
