### ISSUE TITLE
Source/Chant Detail: narrow window formatting

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#849]
On the source detail page, if I make my window narrow the page looks like this. The CantusID/Incipit search should not be located where it currently is on the page.

![image](https://github.com/DDMAL/CantusDB/assets/71031342/1b116a8b-fded-4706-ab77-e13b1f6c3e02)

**Comment by lucasmarchd01** [comment]
Note: Chant detail page has the same problem

![image](https://github.com/DDMAL/CantusDB/assets/71031342/feba3dc6-a04e-423b-9044-f76ea2edb08a)

**Comment by jacobdgm** [comment]
It's where I'd expect it to be (speaking as a developer), considering it's at the top of the sidebar and the sidebar tucks below the main body when the window gets small. Are you saying (as a user) that when the window gets narrow, it should go above the main body?

**Comment by lucasmarchd01** [comment]
Right. I agree that it is showing up where it should since the sidebar tucks under the main content, but yes I think it should go above the main body when the page is narrow. I suppose it doesn't really matter too much either way, though. We can close this issue if you think it's best to leave it as is.

**Comment by jacobdgm** [comment]
Assigning a priority of low; this would be a nice thing to address at some point, though!

It's also a bit awkward, currently, how the sidebar is wider than the main content when it tucks underneath (see the left edge in the screenshots). Hopefully this can be fixed, too, when we move the search box.

**Comment by annamorphism** [comment]
agreed that this looks weird currently. Maybe if they were both the same width and there was space between the end of the chant and the search, it would make more sense visually, though.

**Comment by jacobdgm** [comment]
see also #472

**Comment by jacobdgm** [comment]
with #1332, this is complete!
