### ISSUE TITLE
Admin source-user relationship: display source siglum instead of ID

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#850]
Would it be more useful to display the source's siglum on the source-user relationship of the User admin page instead of the source ID? This would probably make it easier to see which sources are already assigned to a use without having to look up the ID. I'm not sure if this is something that can actually be done with this admin functionality, but I can look into it.
![image](https://github.com/DDMAL/CantusDB/assets/71031342/cef9235d-5fe6-4e3d-8f06-ab61203fd561)

**Comment by annamorphism** [comment]
yes, that would be great!

**Comment by lucasmarchd01** [comment]
I see, the page will display like this until the user clicks "save" after adding the source-user relationships and then the siglum will show as desired.
