### ISSUE TITLE
Concordance links on Chant Detail page re-direct to `cantus.uwaterloo.ca`

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#868]
To reproduce:

1. Go to http://206.12.88.113/chant/248029
2. Scroll down to the table of concordances.
3. Click on one of the chant incipit or source links. These will take you to cantus.uwaterloo.ca.

I know that theoretically the UW cantus links will redirect to cantusdatabase.org (and therefore NewCantus), but this seems convoluted in the long run, and depending on when the UW redirect occurs, there may be a sync issue (cantusdatabase.org points to NewCantus, but UW is still pointing to OldCantus -- not sure what the timeline on that is)

**Comment by dchiller** [comment]
This is because cantusindex returns a cantus.uwaterloo.ca url in the chantlink and srclink fields of the cantusindex reponse. See https://cantusindex.org/json-con/007755.

**Comment by jacobdgm** [comment]
I sent an email to Jan - he'll need to switch how cantusindex is compiling its list of concordances.

In the meantime, I'll go on the production server and make a hotfix to use until Jan makes this update.

**Comment by jacobdgm** [comment]
This is fixed on the production server currently.

I created a new branch, `hotfix-concordances`, on the production machine.

Hopefully Jan will have fixed things on CantusIndex's end by the time we next update the production server with new code. If he hasn't, we'll need to make this same substitution: Around line 300 in `main_app/views/chant.py`, 

```python
            ######################################
            ### create context["concordances"] ###
            # (data to be unpacked in chant_detail.html to make concordances table)

            # response.text is an array of JSON objects. Each has a single
            # key, ["chant"], pointing to a nested object. We only need the
            # nested object.
            concordance_chants = [c["chant"] for c in concordances]
            context["concordances"] = concordance_chants
```
becomes
```python
            ######################################
            ### create context["concordances"] ###
            # (data to be unpacked in chant_detail.html to make concordances table)

            # response.text is an array of JSON objects. Each has a single
            # key, ["chant"], pointing to a nested object. We only need the
            # nested object.
            concordance_chants = [c["chant"] for c in concordances]
            for c in concordance_chants:
                c["chantlink"] = c["chantlink"].replace("cantus.uwaterloo.ca", "cantusdatabase.org")
                c["srclink"] = c["srclink"].replace("cantus.uwaterloo.ca", "cantusdatabase.org")
            context["concordances"] = concordance_chants
```

**Comment by jacobdgm** [comment]
marking this as "on hold". As soon as we get confirmation from Jan that this has been fixed (we can test by visiting a chant detail page on staging), we can `git checkout production` on the production server and close this issue.

**Comment by jacobdgm** [comment]
This is fixed on CantusIndex's end, we've taken the hotfix change off of production, and this is currently working as it should be. Closing.
