### ISSUE TITLE
Paginate or scroll melody search results?

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#869]
Melody search results currently don't seem to paginate or scroll, so you can get long, long pages. For example, try searching a two note sequence in transposition and anywhere in a melody. You'll get a very long page.

**Comment by jacobdgm** [comment]
This is a good point! It's also just as it is on OldCantus. Marking this as "enhancement" etc.

**Comment by jacobdgm** [comment]
duplicate of #1134 - closing.
