### ISSUE TITLE
We need to set up cron job to renew https certificate from time to time

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#870]

**Comment by jacobdgm** [comment]
@kqct, I've lost the command we need to use in the cron job - can you add it here?

**Comment by kqct** [comment]
`docker-compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d cantusdatabase.org`

note: the -d flag specifies domains, you can have multiple

also, i'd recommend updating your docker install to use docker compose V2 (`docker compose` instead of `docker-compose`

**Comment by jacobdgm** [comment]
@timothydereuse and I spent a while looking at this this morning.

we noticed a likely problem with this line in `cron/cron.txt`:

```
50      4       *       *       0       /usr/local/bin/docker-compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ -d cantusdatabase.org -d www.cantusdatabase.org --renew-hook "nginx -s reload"
```

Since this command is run in the certbot container, there's no way that `nginx -s reload` will be able to run successfully, since that command needs to run in the _nginx_ container. There are two possible ways this is going wrong:
- the certificate is being updated successfully, but it isn't being displayed by Nginx because it isn't being reloaded
- since the `renew-hook` command is failing, the `certbot` command is rolling back to the previous version of the certificate (i.e., the hook itself is preventing the certbot command from updating our certificates)

I'm planning on updating this line to `/usr/local/bin/docker-compose run --rm certbot certonly --force-renew --webroot --webroot-path /var/www/certbot/ -d cantusdatabase.org -d www.cantusdatabase.org && /usr/local/bin/docker-compose run nginx nginx -s reload"` on Production, and setting it to run a few minutes after I update it. We should be able to check that the certificate was updated following the run of the command. If it worked, I'll open a PR with this updated command (without `--force-renew`).

**Comment by ahankinson** [comment]
I’m not really a shell scripter but I think you probably want a && to separate the commands so that the second one only runs if the first one was successful?

**Comment by jacobdgm** [comment]
That sounds like a good idea! (Although I don't think there's any harm done if we tell nginx to reload even if the first command returns an error code. But yes, `&&` is certainly closer to what we're aiming to do than `;`. Thank you!)

**Comment by dchiller** [comment]
Further investigations into this: 
- The constantly restarting container is not properly configured and also should not have a restart policy of always! Since all we theoretically want to do is run this container periodically (eg. weekly).
- The cron job is not working, potentially with the issue noted above. 

Proposal:
- Get rid of the constantly restarting container.
- Get rid of using a certbot container at all.
- Configure all of the renewal to happen in the nginx container.

**Comment by jacobdgm** [comment]
With #1233, #1270, etc., this should be fixed. Closing.
