### ISSUE TITLE
OldCantus has an "Active users" page that NewCantus does not have

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#876]
**On OldCantus**, when I'm logged in I can go to the "About" dropdown menu and click on "Active users," which brings me to this lovely page https://cantus.uwaterloo.ca/active-users.

**On NewCantus,** the "Active users" option doesn't appear, and the link https://cantusdatabase.org/active-users/ leads to a 404 error.

@jacobdgm also sent me a link for a "users" page for NewCantus (https://cantusdatabase.org/users/) and OldCantus (https://cantus.uwaterloo.ca/users). I _can_ access this page on NewCantus, but I _can't_ on OldCantus. Furthermore, though the link works, I can't find it anywhere on the site. So it exists... somewhere?

There's also an "indexers" page for both sites that I can access when I'm not logged in. @annamorphism, how are these pages different? I'm mostly just curious, but I also am not sure what differentiates a user from an active user or an indexer, so I find this quite confusing.

**Comment by jacobdgm** [comment]
> There's also an "indexers" page for both sites that I can access when I'm not logged in. annamorphism, how are these pages different? I'm mostly just curious, but I also am not sure what differentiates a user from an active user or an indexer, so I find this quite confusing.

Indexers are people who inventoried manuscripts, copied out texts, entered melodies, and so on. They can be living people (e.g. Debra), or people who are no longer living (e.g. Calvin Bower).

Users are people who can log into Cantus Database, who edit things in the database.

In OldCantus, Indexers were stored separately from users, and they existed to give public credit to people who had done substantial work indexing/transcribing manuscripts.

In NewCantus, Indexers and Users have been merged. There are three possible situations: 1. There are many people who are users who aren't and weren't ever listed as indexers (e.g. you, me). 2. For some people (e.g. Debra), their indexer and user have been merged - they have just a single user account, which includes things to publicly credit their work on specific manuscripts. 3. For some people who were only ever indexers on OldCantus (e.g. Calvin Bower), dummy user accounts have been created which can't be logged into.

Hopefully this helps / clears things up!

**Comment by JoyfulGen** [comment]
> Hopefully this helps / clears things up!

It really does, thank you very much :)

**Comment by jacobdgm** [comment]
NewCantus has been live for, what, 7 months, and no one has complained about missing this page. I'm going to assume that this is not an important thing to implement. Closing; we can re-open if necessary.
