### ISSUE TITLE
saving creation date

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#883]
We would like to preserve the creation date of sources in Cantus before the old site goes down. Currently they all show up in NewCantus as newly created from the date of import. (This information loss already happened at the last Cantus move in 2014, so it would be nice not to also lose the dates for everything created since then...)
I think this information my only show for admins, but Debra requested it. 

Would it be possible to import the old created date, as happened for "created by"?
If not, it would be useful to at least create a file containing the source ID, Rism Siglum, and creation date, so somebody can at least have it on file after the old site goes down in November.

**Comment by jacobdgm** [comment]
looking into this

**Comment by jacobdgm** [comment]
It looks like we have the information we need to do this!

**Comment by lucasmarchd01** [comment]
@jacobdgm okay to close? If everything looks in order on production?
