### ISSUE TITLE
We should create a custom 500 page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#890]
We recently found a place where we were getting a 500 error (Internal Server Error - it's been fixed on production). In addition to the custom 502 and 504 pages we already have (see #853), we should create a similar 500 page.

One possible thing to consider - since 500 errors will probably emerge where there is an error in our code (so the issue won't eventually resolve itself on its own, as is the case for 502s and 504s), we might want to include contact info for Debra (or someone else?) so that news of the error can find its way to us and we can fix it.

**Comment by jacobdgm** [comment]
I spent a while on Friday trying to set this up, and I wasn't able to get it to work. I think the 500 page is less important than the 502 and 504 pages, so I think this is not worth more of my time - I'm going to mark this as "won't fix" and close it.

If we eventually return to this, it would be a good idea to automatically trigger an email to notify a developer that someone has discovered something on the site that's broken.

**Comment by ahankinson** [comment]
> If we eventually return to this, it would be a good idea to automatically trigger an email to notify a developer that someone has discovered something on the site that's broken.

https://sentry.io/welcome/.

Use a service like this. Emails are very easy to get spammed with.
