### ISSUE TITLE
Viewing on mobile: sidebar could appear above main card when window is narrow

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#909]
In an email from Debra:

> This reminds me that when I was at MedRen last week I was talking to someone about the new site and showed them the MS description page on my phone, and they mentioned that it would be easier to be mobile-friendly if the navigation appeared at the top of the screen instead of the bottom.
> 
> I'm thinking here of this type of page:
> https://cantusdatabase.org/source/123744
> 
> The "view all chants", "view full inventory" etc. links are almost at the bottom on a phone (but not exactly at the bottom so you have to backtrack a bit). Is it possible to move this block for mobile viewing?

Looking at https://cantusdatabase.org/source/123744, we probably want the global search bar and first card in the sidebar (beginning "View All Chants") to go to the top, while the last two cards in the sidebar (one beginning "Provenance:" and the Source Edit Options (it's worth noting that I'm logged in)) should go to the bottom.

**Comment by lucasmarchd01** [comment]
Linking #849 here, as I believe they are two sides of the same coin.
