### ISSUE TITLE
Chant Create page is missing "copy full text below" button

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#914]
In an email forwarded to us from Debra, a contributor to CantusDB notes:

> The Create Chant page does not have the button for 'Copy full text below'. Please include here. At present, the button only appears when choosing to Edit.  If this button has been deliberately excluded from the Create Chant page in this new CD version, I believe that is a mistake. Including the MS spelling is one of CD's strengths and I think doing so should be standard good practice. The button makes it easier to do so and is very handy.

**Comment by annamorphism** [comment]
Just as a note--in OldCantus, this option was available on the "Volpiano and full text editor" but not the usual chant-create page (for whatever reason.) I agree that it would be handy to have here, though (but I see why it was omitted).
