### ISSUE TITLE
Chant Create page: we could auto-populate the Office selector

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#915]
In an email forwarded to us by Debra, a CantusDB contributor commented:

> Office/Mass box. When adding chants, the selection made here does not carry over from the previous chant. My preference is that it pre-populate from the previous chant in the source. (But I don't remember whether this used to pre-populate from the previous or not.)

**Comment by jacobdgm** [comment]
I haven't checked yet whether this is what OldCantus did, so I'm marking this as an "enhancement" for the time being.

**Comment by annamorphism** [comment]
Just checked--OldCantus did prepopulate this field, as well as the "Feast", "Folio", and "Sequence" fields 
![image](https://github.com/DDMAL/CantusDB/assets/67451875/14a089c9-e428-4c65-bce7-1bbf4f952cf8)

**Comment by jacobdgm** [comment]
Why is this labelled as an enhancement again? OldCantus did it; we should too.

I'm going to get to work on this one, there's a good chance it's a simple fix.
