### ISSUE TITLE
"Select feast" dropdown repeats feasts

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#916]
On the dropdown to "Select a feast" on a given source (in this case https://cantusdatabase.org/source/637892)  many feasts will repeat for no obvious reason--even though all the chants for one feast are in a continuous block, the list acts as if they are separate. On OldCantus these would show as part of one feast. Comparison:

OldCantus:
<img width="229" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/20abb0d9-33df-48d8-a6f5-eedc5be5684b">

NewCantus:
<img width="390" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/ac76f4b6-80b4-4ad8-8338-d6b95d7f3142">

**Comment by jacobdgm** [comment]
Looking at this selector in this source, it's odd that the duplicates always seem to occur in alternation with duplicates from another feast. Weird.

**Comment by annamorphism** [comment]
was going to make an issue about this today but realized I already had! 
<img width="784" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/8c4387e7-6bb5-41f9-a155-a8094b6775b9">
There doesn't seem to be much pattern to it--if there's multiple feasts on the page they sort of show up in random order, sometimes repeating, sometimes not.  it *feels* like the problem is that some sort of information about the sequence number is not incorporated into the group-by-feast function, but I don't really know.

**Comment by annamorphism** [comment]
e.g. 133v actually has 4 "De Tobia" and 5 "De Esther" chants; if these were randomly sorted as (say) TEETTETEE, and then the adjacent ones sharing a feast condensed to one entry, you'd get a list that looks like the above.

**Comment by annamorphism** [comment]
this continues to be both annoying/frustrating to use and extremely silly to look at. 
Often I want to know what, e.g. the 130 feasts in St-Gall 390 are and exactly what order they go in, in addition to navigating straight to them; a dropdown with 484(!) entries in only-sort-of-order is not useful for this, and scrolling through three times as many feasts as necessary in order to find some specific feast is aggravating. 
personally find this higher priority than #1089, which doesn't bother me nearly as much or as often...but maybe my need to look at feasts is more than most!

**Comment by jacobdgm** [comment]
I agree with @annamorphism. Bumping the priority from medium to high - this is a place where the site isn't working, in a way that makes it clear that us developers have messed something up, in a place that's easy to get to.

**Comment by dchiller** [comment]
@annamorphism I'm also noticing that when you select a feast from the dropdown, you get results that include every chant in the source associated with that feast, not just the chants associated with that feast on the specific folio. This feels like false advertising (why would you give me both `001r - Feast A` and `001v - Feast A` if selecting either one will give me the same thing).

Should the results of clicking a drop down give you only the chants of that feast on that folio? Or should we just do away with the folio numbers together and have the feast dropdown give you all the chants in the source associated with that particular feast?

To see what I mean, go to [this source](https://cantusdatabase.org/source/637892/chants/) and select `005r - Thomae de Aquino` and then select `012v - Thomae de Aquino` and see that you get the exact same results.

**Comment by annamorphism** [comment]
I see what you mean--even in cases where there might actually be two copies of the feast in the manuscript (maybe there's one on 99r and a revised version added in on 152v), even the old interface took you to a page with both versions one after the other, never the "revised folio 152v version" by itself. 
However I can imagine that if you happen to read somewhere that this manuscript has a certain feast on 152v, it might be easier to find it in the dropdown if the folio number is included rather than reading down the whole list of headings with no page information. (There are of course other ways of finding feasts in a manuscript! But I do find myself navigating this way.)

**Comment by dchiller** [comment]
So to summarize: keep the same behaviour as it is now when you select an item from the dropdown (show all of the chants with the given feast regardless of folio) but fix that fact that we have all of these duplicated options in the dropdown....

**Comment by annamorphism** [comment]
For now anyway, yes--this would duplicate the OldCantus behaviour. Having it take you to only the chants for feast X starting on some folio Y seems like a potentially interesting feature, so if that is a good way to implement it then it's a bonus--but if it's non-trivial then it's probably worth thinking a bit further about the pros/cons.
