### ISSUE TITLE
sources list could paginate better

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#917]
When looking at the list of all sources, I find it annoying to have to page through half the sources to get to one in, say, the Netherlands--in OldCantus I could scroll all the way through, but now that things are paginated (good!) I have to load up pages of sources in Canada, Switzerland, France, etc. to get to NL-whatever. Of course, I _could_ simply search for the siglum in the search bar, so this is a minor inconvenience, but I am a creature of habit and it would be nice to have the ability to go straight to page 4 of 6 (or whatever).

**Comment by jacobdgm** [comment]
What would make this easier to work with (i.e. can you clarify what "paginate better" means)?

**Comment by annamorphism** [comment]
I meant what MMMO has, so you can go to the relevant part of the list right away. (#936 is sort of related, though. )
<img width="973" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/1b27be8c-644b-419e-9762-31be2c8206d7">
