### ISSUE TITLE
cantusdatabase.org/description does not exist, but appears on Google search

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#929]
https://www.cantusdatabase.org/description leads to a 404. 

I only found this page because I was messing around on Google trying to figure out whether NewCantus shows up in search results (more of that in a comment arriving soon to an issue near you; https://github.com/DDMAL/CantusDB/pull/922). Just to see what would happen, I copied a sentence from the NewCantus homepage and specifically asked Google to search that website. This was my search request:

Cantus Database is a part of the Cantus Index network of manuscript databases. site:cantusdatabase.org.

It gave me three results (none of which were the home page, mysteriously), the first of which is entitled "Fields and Content Descriptions" and does not exist. The other two are "What's new" and "Bibliography and References" and both of those exist.

**Comment by jacobdgm** [comment]
see also #677. I can fix it to point to the old path (thus fixing both issues) - we'll just need to remember to manually change the path name of the flatpage when we roll this change out to staging and production.

**Comment by jacobdgm** [comment]
I created a duplicate flatpage - the same page now exists at /field-descriptions/ and /description/. In the header, we currently link to /field-descriptions/, but I'll open a PR to change it to link to /description/ (to address #677). Once the PR has been merged, we can delete the one at /field-descriptions/.

**Comment by jacobdgm** [comment]
I've deleted the flatpage at /field-descriptions/. This was the source of some confusion - Debra was editing the old one, not realizing that the page she had open in her browser was the new one.
