### ISSUE TITLE
Search should ignore diacritics

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#935]
In an email from Debra:

> I'm in a session at IAML and just realized that the books from Kraków (that the speaker is highlighting as being in Cantus) only come up when I search with ó.
> 
> I was lazy in my first search and just entered Krakow.
> Is a search that finds both (or all) versions something easy to add to the functionality of the site?
> 
> There are other place names with accents, so we would want to apply this type of search to more than just the Krakow sources.

We should make sure that searches throughout the site ignore diacritic marks (i.e. accents) on characters.

**Comment by jacobdgm** [comment]
https://docs.djangoproject.com/en/4.2/ref/contrib/postgres/lookups/#unaccent

**Comment by jacobdgm** [comment]
@annamorphism - we'll never need to do this for chants or sequences, correct? It seems that when you're working with really big database tables (like our 500000 chants), this unaccent tool can affect performance. So if we only need to worry about sources, that will be a good thing for keeping other parts of the site loading quickly.

**Comment by annamorphism** [comment]
This is a good question actually.  Cantus Index has a (still very small) number of texts with lots of accents, taken from a Czech database (see e.g. https://cantusindex.org/text-search?text=svat) . DACT is interested in vernacular translations of chant, so there's a possibility that texts with accents will enter CantusDB in the future. (Will there ever be non-Roman alphabets? Hmmm.)

HOWEVER I think it is probably (?) fair to expect people searching for Czech chants to use correct Czech accents in their search terms, whereas one-word place names are maybe less fair game. (In this case "Krakow" is a valid alternate spelling, too--in an ideal world we would have it in a place index along with Cracow, Krakau, Cracovia, which would come closer to solving the real problem.) So,  I don't think we need it for chants--there may come a time when it is needed for dealing with chants in other languages, but that is not any time soon.

**Comment by jacobdgm** [comment]
Some may find this mildly entertaining: I implemented this, and am currently writing tests for it; as I add tests and make sure they're testing what I expect them to, my terminal is filling up with the following (I'll remove the print statements before I push, I promise!):

```
root@70ddbef3899b:/code/django/cantusdb_project# python manage.py test main_app.tests.test_views.SourceListViewTest
Found 14 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
........Déléçtūs àrçhïtéçtô àlïqūàm fūgïàt.
.Sàpïéñté pàrïàtūr.
.KŪÑÀDÉ
..Àpérïàm çôrrūptï dôlôrïbūs àspérïôrés ïsté témpôrïbūs.
..
----------------------------------------------------------------------
Ran 14 tests in 1.534s

OK
Destroying test database for alias 'default'...
root@70ddbef3899b:/code/django/cantusdb_project# python manage.py test main_app.tests.test_views.SourceListViewTest
Found 14 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
......Sàpïéñté éūm àspérïôrés ūllàm àspérïôrés.
.Débïtïs àççūsàmūs plàçéàt çôrpôrïs çūmqūé vôlūptàté çômmôdï.
.Tôtàm réçūsàñdàé qūàs ét àñïmï vôlūptàs làūdàñtïūm.
.Répūdïàñdàé ïñvéñtôré hïç.
.MFPYMÏ
.Vôlūptàté éxpédïtà dôlôrém àñïmï béàtàé.
.Qūàéràt sïmïlïqūé éà ràtïôñé qūàé pérféréñdïs ïmpédït.
..
----------------------------------------------------------------------
Ran 14 tests in 1.621s

OK
Destroying test database for alias 'default'...
```
