### ISSUE TITLE
Code for permissions checks could all be in one place - opportunity for refactoring

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#962]
Currently, code dictating which users have access to which pages, as well as code dictating which links should be shown to whom, is currently scattered through the code base. Whenever I want to know who has access to a page, I need to think really hard about all the places I need to look to answer what should be a simple question.

It could be helpful to put test functions for all our different views in one place - perhaps a single file in `main_app/`.

If we did this, we could simply call the relevant function in each of our views' `test_func` method, and we could call the same function in the `get_context_data` method in our other views, to decide whether or not to display a link to a given page. This way, we could be confident that no one is being shown a link that would lead to a 403/401 page.

**Comment by jacobdgm** [comment]
Assigning this a priority of medium, but not embarking on this refactoring project at the current moment. If others think/agree this should be a priority, let me know, (or just go ahead and assign me to the issue) and I'll get to work.

**Comment by lucasmarchd01** [comment]
I agree, I think this refactoring would make a lot of sense.
