### ISSUE TITLE
Search Preview could be optimized

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#979]
Interacting with the general search bar, I'm noticing that the search preview is being quite sluggish. We should work to optimize it, so the suggested results appear instantaneously, rather than after 5 seconds.

Maybe it has to do with us searching all three text fields - if we searched just the incipit field, it might go faster, even if we might end up leaving one or two results out of the preview. (update: nope, we're only searching the incipit field after all.)

**Comment by jacobdgm** [comment]
I just checked, and we're only searching the incipit field after all. Applying `db_index` to the `incipit` field on our Chant/Sequence model locally, didn't make a noticeable difference.

**Comment by dchiller** [comment]
We've deemed this no longer to be a problem.
