### ISSUE TITLE
Cron not saving backups properly

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#982]
I checked a little while ago, and I couldn't find the daily database backup on the Production machine which should have been created at 4am today.

@dchiller and I spent a while looking into this, and we think we have a solution. We'll try implementing it, and if it seems to work, we'll update the documentation. I'll also add more details to this issue about what the problem was.

**Comment by jacobdgm** [comment]
Tagging @jackyyzhang03, not because you need to do anything about this, but you set it up and might be interested to hear/learn about what was going on.

**Comment by jacobdgm** [comment]
This is fixed.

There were a couple of component problems:
- First, I had added the contents of `cron.txt` to my crontab, rather than adding them to `ubuntu`'s crontab. To fix this, I got rid of everything in my crontab, logged in as `ubuntu`, and ran the `cat` command as `ubuntu`.
- Second, when cron tried to save a backup, the directory structure had not been set up, and `pg_dump` command failed when it couldn't find `/home/ubuntu/backups/postgres/daily/`. And if I just went `sudo mkdir` to make the directories, `pg_dump` didn't have write permissions for the folder because it had been created by `root`. To fix this, I had to log in as `ubuntu` and create the directories.

Now everything is set up on Production; we tested this by modifying the crontab to save a copy of the database right away (and then set it back), and it worked as expected. I've updated the documentation to make sure it's clear how this was set up. We'll check tomorrow morning just to verify that the daily backup was saved correctly, but there should be nothing more to do about this. Closing.

**Comment by jacobdgm** [comment]
Hm... I just checked, and I found a `/home/ubuntu/backups/postgres/daily/2023-08-16T04:00:01.sql.gz` on Production. But when I `scp`ed it to my own machine and tried to unzip it, I discovered it to be empty...

**Comment by jacobdgm** [comment]
```
jacob@cantus-db-prod:/home/ubuntu/backups/postgres/daily$ ls -l
total 166228
-rw-rw-r-- 1 ubuntu ubuntu 170207255 Aug 15 19:27 2023-08-15T19:26:20.sql.gz <- this one was created yesterday by manually running the pg_dump command
-rw-rw-r-- 1 ubuntu ubuntu        20 Aug 15 19:40 2023-08-15T19:40:01.sql.gz <- this one was triggered by cron yesterday, when we had modified the crontab to download every hour. Notice it's only 20B
-rw-rw-r-- 1 ubuntu ubuntu        20 Aug 16 04:00 2023-08-16T04:00:01.sql.gz <- this one was triggered by cron this morning - the proper daily backup - and it's also only 20B
```

**Comment by jacobdgm** [comment]
potentially useful: https://stackoverflow.com/questions/61303279/docker-compose-dumping-postgres-database-in-a-cron-job-not-working, https://serverfault.com/questions/1069575/docker-postgres-backup-creates-an-empty-file-when-run-as-a-cron-job

**Comment by dchiller** [comment]
This is not directly related to the issue, but I noticed that the backup cron scripts are running `mkdir` for the backup directory on every run. If we've already set up the backup directories with the correct permissions, this is redundant and for clarity's sake should probably be removed.

**Comment by dchiller** [comment]
I remember this being true when we were working on this together, but just to verify: when you ran this manually, were you logged in as the `ubuntu` user? And did you run it by bash-ing `daily.sh` from outside the container? Or by just running 
`usr/local/bin/docker-compose -f $DOCKER_COMPOSE_FILE exec postgres pg_dump cantusdb -U cantusdb | gzip > $BACKUP_DIR/$(date "+%Y-%m-%dT%H:%M:%S").sql.gz` from the command line (this is line 13 of the `daily.sh` file)? Or did you run some command from inside the container? 

The first option mirrors (I think) most closely what is happening when the cron job runs, so I just want to make sure I am clear on the comparison between the successful and unsuccessful backup runs.

**Comment by jacobdgm** [comment]
If I recall, I ran the actual docker-compose command (i.e. the second option), and not running `daily.sh`. I can't remember who I was logged in as at the time. Trying to run `daily.sh` as `ubuntu` would be a better point of comparison - thanks for this!

**Comment by jacobdgm** [comment]
As I was communicating with Debra while thinking about #1158, she explicitly asked for the option to reset the database to an earlier state in case something went wrong. We really need to fix this.

Increasing priority from medium to high.

**Comment by dchiller** [comment]
> Trying to run `daily.sh` as `ubuntu` would be a better point of comparison - thanks for this!

Just did this, and it worked! So it's definitely something with the cron set-up.

**Comment by dchiller** [comment]
Just noticed that the .sh files are not executable...so maybe that's a thing. Just made `daily.sh` executable; we can see tomorrow if that made a difference.

**Comment by dchiller** [comment]
> Just made `daily.sh` executable; we can see tomorrow if that made a difference.

This did not make a difference.

**Comment by jacobdgm** [comment]
The thing I haven't had a chance to try, but might be worth trying:

- When setting up cron things, log in as `cantusdb`/`ubuntu` (depending on staging vs. production) first.
- When restarting the container, log in as that same user first.
