### ISSUE TITLE
"Tutorial for Cantus contributors" page contains a link to OldCantus

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#984]
Behold:

<img width="1440" alt="Old link new cantus" src="https://github.com/DDMAL/CantusDB/assets/83373378/72dcbb9d-72e4-4950-85de-da34e627ae59">

That's pretty much it.

**Comment by JoyfulGen** [comment]
Edit: this is also true of the "Citation Style" page:

<img width="1440" alt="Old link in citation style page" src="https://github.com/DDMAL/CantusDB/assets/83373378/b70b9d71-2076-4445-b930-3e1877831f11">

**Comment by jacobdgm** [comment]
I made some updates to the /tutorials/ and /citations/ pages on Staging and emailed Debra for her review and approval. I'll copy the code (they're stored as flat pages in the database) onto Production once I get the okay from Debra.

**Comment by jacobdgm** [comment]
Both pages are now updated!
