### ISSUE TITLE
500 Error for Chants that have no Source

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#995]
spinning off from #992: Anna found a chant with no source - when you try to visit its Detail page, you get a 500 error.

> update: there are also a few chant objects that do this. e.g. https://cantus.uwaterloo.ca/chant/688442 (broken on NewCantus: https://cantusdatabase.org/chant/688442). I have no idea what this particular chant is supposed to be part of, or how it even got made....

**Comment by lucasmarchd01** [comment]
With #1005, chants and sequences without a source will not be displayed, so the 500 error shouldn't appear anymore.
