### ISSUE TITLE
some chant suggestions don't work?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#998]
In trying to create some test chants to investigate #996 , I found that the chant suggestions sometimes autofill but not always.  For example, having created 
![image](https://github.com/DDMAL/CantusDB/assets/67451875/7b096a37-0551-4d87-ba66-b473d93f3e45)
 the suggestion for g00556.Tp doesn't populate the fields, while all the other suggestions do. And for an earlier chant, the first suggestion didn't work but the others did: 
![image](https://github.com/DDMAL/CantusDB/assets/67451875/b84d5277-ba70-4c8b-8be9-25a2412e82c8)
Still investigating why this is.

**Comment by annamorphism** [comment]
wondering if it might be relevant that both those suggestions contain dots (and in both cases have IDs that are too long to fit in the button.) Seems to be consistent for other cases where this doesn't work...

**Comment by lucasmarchd01** [comment]
Interesting. I think this was also pointed out by someone to Debra, so we opened #815. It was closed because it seemed like it was working fine again, so we should figure out why this is still happening.

**Comment by annamorphism** [comment]
It's also possible that we were simply unable to reproduce the issue at the time because the problem seems to be specific to only some suggestions  (I think it's only suggestions where the ChantID has a decimal point in it.)

**Comment by jacobdgm** [comment]
It's the decimal point. In our template, we're creating a function `autoFill{{ chant.cid }}`. But we're not allowed to create a function called `autoFillg00556.Tp2`, due to the dot.
